### ISSUE TITLE
[npud] Implement of each trix backend function

### ISSUE THREAD

**Issue by jyoungyun** [Samsung/ONE#10064]
## What

Let me implement of overall structure for each function.

https://github.com/Samsung/ONE/blob/31143aef3c019627eb930f96748ae0d473667862/runtime/service/npud/backend/trix/TrixBackend.cc#L74-L141

## To do
- [x] Implement ContextManager (https://github.com/Samsung/ONE/pull/10028)
- [ ] Create and Destroy context
   - [x] Add dbus method in `org.tizen.npud.xml` (https://github.com/Samsung/ONE/pull/10026)
   - [x] Implement DBus function (https://github.com/Samsung/ONE/pull/10026)
   - [x] Implement Core function (https://github.com/Samsung/ONE/pull/10062)
   - [x] Implement DevManager function (https://github.com/Samsung/ONE/pull/10022)
   - [x] Implement Trix backend function (https://github.com/Samsung/ONE/pull/10022)
   - [ ] Add test case (Draft: #10072, https://github.com/Samsung/ONE/pull/10072/commits/c30469a13ba1832d1b0bcc6a7a930af5b17c6de2)
- [ ] Register and Unregister Model
   - [x] Add dbus method in `org.tizen.npud.xml` (https://github.com/Samsung/ONE/pull/10054)
   - [x] Implement DBus function (https://github.com/Samsung/ONE/pull/10054)
   - [x] Implement Core function (#10073)
   - [x] Implement DevManager function (https://github.com/Samsung/ONE/pull/10065)
   - [x] Implement Trix backend function (https://github.com/Samsung/ONE/pull/10063)
   - [ ] Add test case (#10072, https://github.com/Samsung/ONE/pull/10072#issuecomment-1322169135)
- [ ] Create and Destroy request
   - [x] Add dbus method in `org.tizen.npud.xml` (#10104)
   - [x] Implement DBus function (#10104)
   - [x] Implement Core function (#10135)
   - [x] Implement DevManager function (#10105)
   - [x] Implement Trix backend function (#10091)
   - [ ] Add test case (Draft: #10072, 148255d2f38620e454464c5d272ed2570990bd58)
- [ ] Set request data
   - [ ] Add dbus method in `org.tizen.npud.xml`
   - [ ] Implement DBus function
   - [ ] Implement Core function
   - [ ] Implement DevManager function
   - [ ] Implement Trix backend function
   - [ ] Add test case
- [ ] Execute run
   - [ ] Add dbus method in `org.tizen.npud.xml`
   - [ ] Implement DBus function
   - [ ] Implement Core function
   - [ ] Implement DevManager function
   - [ ] Implement Trix backend function
   - [ ] Add test case

### DBus Methods

| DBus method | In | Out | Backend API |
|:---------------:|:---:|:-----:|:------------------:|
| device_get_available_list | - | error(i) | getVersion(std::string &version) |
| context_create | id(i), priority(i) | context_handle(t), error(i) | createContext(int deviceId, int priority, NpuContext **ctx) |
| context_destroy | context_handle(t) | error(i) | destroyContext(NpuContext *ctx) |
| network_create | context_handle(t), model_path(s) | network_handle(u), error(i) | registerModel(NpuContext *ctx, const std::string &modelPath, ModelID *modelId) |
| network_destroy | context_handle(t), network_handle(u) | error(i) | unregisterModel(NpuContext *ctx, ModelID modelId) |

### DBus Spec Basic types

Conventional name | ASCII type-code | Encoding
-- | -- | --
BYTE | y (121) | Unsigned 8-bit integer
BOOLEAN | b (98) | Boolean value: 0 is false, 1 is true, any other value allowed by the marshalling format is invalid
INT16 | n (110) | Signed (two's complement) 16-bit integer
UINT16 | q (113) | Unsigned 16-bit integer
INT32 | i (105) | Signed (two's complement) 32-bit integer
UINT32 | u (117) | Unsigned 32-bit integer
INT64 | x (120) | Signed (two's complement) 64-bit integer (mnemonic: x and t are the first characters in "sixty" not already used for something more common)
UINT64 | t (116) | Unsigned 64-bit integer
DOUBLE | d (100) | IEEE 754 double-precision floating point
UNIX_FD | h (104) | Unsigned 32-bit integer representing an index into an out-of-band array of file descriptors, transferred via some platform-specific mechanism (mnemonic: h for handle)

Conventional name | ASCII type-code | Validity constraints
-- | -- | --
STRING | s (115) | No extra constraints
OBJECT_PATH | o (111) | Must be a syntactically valid object path
SIGNATURE | g (103) | Zero or more single complete types

from https://dbus.freedesktop.org/doc/dbus-specification.html

<details>
<summary>All TRIX backend APIs</summary>

- getVersion
- createContext
- destroyContext
- createBuffer
- destroyBuffer
- registerModel
- unregisterModel
- createRequest
- destroyRequest
- setRequestData
- submitRequest

</details>

**Comment by jyoungyun** [comment]
Close this issue.
