### ISSUE TITLE
Checklist for ONE 1.22.0 Release

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#10540]
### Release Action

- [x] Release Note #10545 
- [x] Update debian package changelog ( before branch out ) #10544 
- After Branch out  
  - [x] `master` branch version up 
    - [x] tizen spec file
    - [x] nnfw_version.h
    - [x] document version in `/docs/conf.py`
    - [x] onert aar version
    - [x] vconone version

### Release Package

- Compiler
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
     - [x] test with public models
     - [x] test with in-hose models
  - [x] x64-linux (tar.gz) for Ubuntu 20.04
     - [x] test with public models
     - [x] test with in-hose models

### Release Criteria

- Compiler : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0) 
  - [x] TEM coverage link : http://npuci.mooo.com:8080/job/nnfw/job/release_1.22/job/daily-compiler-coverage/1/
  - [x] TCM link : https://analysishub.sec.samsung.net/service/analyses/1959200
  - [x] Svace link : https://analysishub.sec.samsung.net/service/analyses/1958097
  - [x] Coverity link : https://analysishub.sec.samsung.net/service/analyses/1958100
  - [x] SAM link : https://analysishub.sec.samsung.net/service/analyses/1958097
  - [x] License Verification : [one_1220Report.zip](https://github.com/Samsung/ONE/files/11085770/one_1220Report.zip)

### Miscellaneous

- [x] nncc preset update if needed
- Security 
  - Compiler
    - [x] Svace_security : https://analysishub.sec.samsung.net/service/analyses/1958099

**Comment by hseok-oh** [comment]
Will we release ubuntu 18.04 package?

**Comment by mhs4670go** [comment]
Well, we don't have to, but I'm not sure about that. 

@seanshpark @lemmaa What is your take on this?

**Comment by lemmaa** [comment]
We need both 18.04 and 20.04 on this release.

**Comment by mhs4670go** [comment]
@seanshpark @jinevening I've written a draft of release note. Please append things that you you need or refine it.

### Release 1.22.0

- Introduce optimization passes: `ForwardTransposeOpPass`, `RemoveDuplicateConstPass`, `FoldFullyConnectedPass`, `FusePReluPass`
- Support more Ops for fake quantization: `depth2space`, `space2depth`
- Support more Ops for quantization: `Abs`, `ReduceProd`
- Introduce _visq_ module for qerror visualization
- Introduce _Environment_ section into configuration file
- `ForwardTransposeOpPass` supports unary Ops
- Support ubuntu 20.04

**Comment by seanshpark** [comment]
> Support ubuntu 20.04

maybe `Experimental support Ubuntu 20.04` ?

**Comment by lemmaa** [comment]
Yes, Ubuntu 20.04 support in this release is experimental. But now that official support for 18.04 has ended, we now need to switch to 20.04. 

In the next release 20.04 should become official support. Of course, for users who still need 18.04, I will have to keep 18.04 for a while.

**Comment by seanshpark** [comment]
> maybe Experimental support Ubuntu 20.04 ?

Ah... sorry. I mis-read it with `22.04` 😭

**Comment by seanshpark** [comment]
> ForwardTransposeOpPass -> forward_transpose_op
> @seanshpark Could you tell me your opinion?

`forward_transpose_op` seems better :)
