### ISSUE TITLE
Checklist for ONE Runtime 1.22.1 Release (runtime)

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#10701]
### Release Action

- [x] Release Note

### Release Package

- Runtime 
  - [x] arm64-android (tar.gz) for Android 10
  - [x] arm64-android (aar) for Android 10
  - [x] arm-tizen (rpm) for Tizen
  - [x] arm-linux (tar.gz)  for Ubuntu 18.04
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
  - [x] nnfw-devel
  - [x] nnfw-plugin-devel

### Release Criteria

- Runtime : TEM (>4.0), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0, DC > 4.0)
  - [x] TEM coverage link :  [Passed](https://code.sec.samsung.net/testhub/release-test/detail?release_key=SRRELEASE-1204&baseDate=2023-04-17&page=0)
  - [x] TCM link : [Passed](https://analysishub.sec.samsung.net/service/analyses/2016076)
  - [x] Svace link : [critical 0](https://analysishub.sec.samsung.net/service/analyses/2016055)
  - [x] Coverity link : [critical 0](https://analysishub.sec.samsung.net/service/analyses/2016072)
  - [x] SAM link : SAM 4.52, DC 4.34 [link](https://analysishub.sec.samsung.net/service/analyses/2016055)
  - [x] License Verification : 
[SR_Tizen_Public_Release_MV_16409_platform+core+ml+nnfwReport.zip](https://github.com/Samsung/ONE/files/11313304/SR_Tizen_Public_Release_MV_16409_platform%2Bcore%2Bml%2BnnfwReport.zip)

### Miscellaneous

- [x] Security
  - [x] SSMS :  [link](https://ssms.sec.samsung.net/#/sdl/project/1413)
  - Runtime : 
    - [x] Svace_security :  [critical 0](https://analysishub.sec.samsung.net/service/analyses/2016056)

**Comment by chunseoklee** [comment]
@Samsung/one_onert somebody in HQ, please check TEM score since I cannot access to the server.

**Comment by hseok-oh** [comment]
Issue: `arm64-android (aar)` package generation fail

**Comment by hseok-oh** [comment]
> Issue: `arm64-android (aar)` package generation fail

It was CI issue. It will be resolved soon.

**Comment by hseok-oh** [comment]
Runtime updates from 1.21.0 (check `git log 1.21.0..release/1.22.0 runtime/*`)

- Support general multimodel nnpackage
  - 3 or more models
  - Models with subgraphs
- Support quantization type casting

**Comment by chunseoklee** [comment]
@hseok-oh I found that I cannot gbs import for the latest 1.22.1 branch. It is very strange since it works before. Anyway, here is the plan for tomorrow. 

1. merge https://github.com/Samsung/ONE/pull/10718 into 1.22.1
2. gbs import "1.22.1" branch into tizen's upstream branch and push it into tizen's upstream branch
3. push upstream branch into tizen branch.
4. SBS into quickbuild(https://quickbuild.tizen.org)

**Comment by chunseoklee** [comment]
Tizen SR is accepted in https://quickbuild.tizen.org/build/213697

**Comment by hseok-oh** [comment]
Released: https://github.com/Samsung/ONE/releases/tag/1.22.1
