### ISSUE TITLE
[Compiler] Introduce and Fuse BCQ operations

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE#1079]
Draft : #782

Let's support BCQ operations and fuse it

- [x] Introduce circle schema #1080 #1118
- [x] circledump #1158
- [x] circle2circle #1364
- [x] luci/export #1230
- [x] luci/lang #1160
- [x] luci/logex #1193
- [x] luci/Service #1316 #1444
- [x] luci/pass (FuseBCQ) - Structure #1329
- [x] luci/pass (FuseBCQ) - Implementation #1455

**Comment by llFreetimell** [comment]
Implementaion of luci/pass can be changed after offline meeting.

**Comment by llFreetimell** [comment]
### 2020-05-25 Update

Schema of BCQ operations would be changed in near future, due to internal issue.
For now, go as it is.
And in the near future, additional working should be needed.

**Comment by llFreetimell** [comment]
Done~!
