### ISSUE TITLE
[onert-micro] Checklist for oner-micro 0.1

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#10850]
### Release Action

- [ ] Merge before branch out 
  - [ ] Release Note 
- [ ] merge after branch out 
  - [ ] `master` branch version up (Q. where is onert-micro version ? )

### Release Package

  - [ ] arm-linux (tar.gz)  for Ubuntu 18.04
  - [ ] x64-linux (tar.gz) for Ubuntu 18.04
  - [ ] devel package (headers)
  - [ ] test with TizenRT, arm-linux, x64-linux

### Release Criteria

- Runtime : TEM (>4.0), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0, DC > 4.0)
  - [ ] TEM coverage link : 
  - [ ] TCM link : 
  - [ ] Svace link : 
  - [ ] Svace_security : 
  - [ ] Coverity link : 
  - [ ] SAM link : 
  - [ ] License Verification

**Comment by chunseoklee** [comment]
cc @BalyshevArtem @Torrero @SlavikMIPT
