### ISSUE TITLE
[onert] Introduce optimizers for training

### ISSUE THREAD

**Issue by ragmani** [Samsung/ONE#11014]
## What

Let's introduce optimizers for training.

## Optimizer types
- SGD
- Adam

## Tasks
- Introduce `TrainableTensor` that allows weights to be updated.
  - [x] Introduce `TrainableTensor` into `train` backend
    - #11007
    - #11066
  - [x] Disallow dynamic shape of tensors in `train` backend
    - #11006
  - [x] Introduce `MemoryManager` into `train` backend
    - #11008
  - [x] Introduce `TensorManager` into `train` backend
    - #11009
  - [x] Introduce `TensorReigstries` into `train` backend
    - #11005 
    - #11013
    - #11026
  - [x] Initialize TrainableTensors
    - #11128

- Introduce optimizers
  - [x] Introduce `OptimizerCode`
    - #11064
  - [x] Introduce optimizers
    - #11065
    - #11071
    - #11076
    - #11075
    - #11074 is postponed
  - [x] Create optimizer
    - #11084
    - #11093
  - [x] Apply optimizer in backend
    - #11091
    - #11135
  - [x] Introduce training step
    - #11111

- Unify `TensorRegistry`
  - [x] Introduce `TensorRegisty` for training
    - #11067
    - #11069
    - #11068
  - [x] Unify `TensorRegistry` in train backend
    - #11083
  - [x] Unify `TensorRegistry` in builtin backend
    - #11086
    - #11092 
  - [x] Apply unified `TensorRegistry`
    - #11098 

- Implement `PermuteLayer` for training
  - [x] Implement backward
    - #11087
    - #11110
    - #11124
    - #11153

Draft #10984

**Comment by ragmani** [comment]
Done except for adam optimizer.
