### ISSUE TITLE
Checklist for ONE 1.24.0 Release

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#11085]
### Release Action

- [x] Merge before branch out 
  - [x] Release Note #11094
  - [x] Update debian package changelog ( before branch out ) #11095 
- [x] merge after branch out 
  - [x] `master` branch version up 
    - [x] vconone version #11103 

### Release Package

- Compiler
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
     - [x] test with public models
     - [x] test with in-hose models
  - [x] x64-linux (tar.gz) for Ubuntu 20.04
     - [x] test with public models
     - [x] test with in-hose models

### Release Criteria

- Compiler : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0) 
  - [x] TC line coverage link : http://npuci.mooo.com:8080/job/nnfw/job/release_1.24/job/daily-compiler-coverage/
  - [x] TCM link : https://analysishub.sec.samsung.net/service/analyses/2227368
  - [x] Svace link : https://analysishub.sec.samsung.net/service/analyses/2227357
  - [x] Coverity link : https://analysishub.sec.samsung.net/service/analyses/2227367
  - [x] SAM link : https://analysishub.sec.samsung.net/service/analyses/2227357
  - [x] License Verification :  (verified) [one_1240Report.zip](https://github.com/Samsung/ONE/files/12077223/one_1240Report.zip)

### Miscellaneous

- [x] SSMS
  - Compiler : 
    - [x] Svace_security : https://analysishub.sec.samsung.net/service/analyses/2227362

**Comment by mhs4670go** [comment]
Release note 1.24.0

- Introduce _one-import-onnx-ext_
- _onecc_ supports profiling of multiple backends with a single cfg file
- Enable more Quantize operator: FloorMod, Squeeze
- _visq_ supports multi-out nodes
- _onecc_ introduces `dynamic_batch_to_single_batch option` option.

@seanshpark @jinevening If you have any other things to be added, please post a comment below. I'll append them.

**Comment by seanshpark** [comment]
> Introduce _one-import-onnx-ext_

Introduce _one-import-onnx_ extension interface
