### ISSUE TITLE
Checklist for Release 1.4.0

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#112]
## Checklist
  - [x] Branch out : https://github.com/Samsung/ONE/tree/release/1.4.0
  - [x] Release Note 
  - [x] **runtime binary for android**
      - [x] document for android 
  - [x] runtime binary for tizen (rpm)
  - [x] runtime binary for arm-linux (tar.gz)
  - [x] compiler binary for x64-linux (tar.gz)
  - [x] runtime : svace, coverity critical 0
       - [x] svace link : https://code.sec.samsung.net/ahub/service/analyses/81230           
       - [x] coverity link : https://code.sec.samsung.net/ahub/service/analyses/80918
  - [x] runtime : line coverage 80% 
  - [x] tizen version up ( spec file ) : #126
