### ISSUE TITLE
[one-optimize] Decompose Softmax

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#11492]
## What

Let's decompose softmax into multiple operators for special backends.

![image](https://github.com/Samsung/ONE/assets/5449554/6ef5dfd8-b9af-44b5-af98-28c03b679cb6)

Example
```sh
onecc optimize --decompose_softmax input.circle output.circle
```

This option will not be included in O1.

## Tasks

- [x] Implement luci/pass
- [x] Add luci-pass-value-test
- [x] Add circle2circle-dredd-recipe-test
- [x] Update one-optimize

**Comment by stamalakhov** [comment]
@jinevening 
May be i could try to implement this feature?

**Comment by jinevening** [comment]
Of course :) Thanks.

**Comment by jinevening** [comment]
I think this task is done. Thanks! @stamalakhov
