### ISSUE TITLE
Checklist for onert-micro 1.0 release

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#11502]
### Release Action

- [ ] Merge before branch out 
  - [ ] Release Note
  - [ ] update onert-micro version file(use 1.0.0)  : https://github.com/Samsung/ONE/pull/11501
- [ ] branch out : 
- [ ] merge after branch out
  - [ ] `master` branch version up

### Release Criteria

 TEM (>4.0), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0, DC > 4.0)

#### measurement on master Before branch out 
  - [ ] TEM coverage link : [4.0]
  - [ ] TCM link : [44/88]
  - [ ] Svace link : [critical 0]
  - [ ] Svace_security : [critical 0]
  - [ ] Coverity link : [critical0]
  - [ ] SAM link : [4.46(DC 4.46)]
  - [x] License Verification : verified

#### measurement on release branch
  - [ ] TEM coverage link : [4.0]
  - [ ] TCM link : [44/88]
  - [ ] Svace link : [critical 0]
  - [ ] Svace_security : [critical 0]
  - [ ] Coverity link : [critical0]
  - [ ] SAM link : [4.46(DC 4.46)]
