### ISSUE TITLE
[onert] Remove tflite_benchmark tool

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#1151]
Parent issue: #871

`tflite_run` include features of `tflite_benchmark`. So we can remove `tflite_benchmark` tool.

- [x] Remove remain difference between `tflite_run` and `tflite_benchmark`
  - [x] Geomean #944 
  - [x] Model validation check #1150 
- [x] Remove `tlfite_benchmark`
  - [x] Remove `tflite_benchmark` usage from test scripts #938
  - [x] Remove `tlfite_benchmark` #1252
