### ISSUE TITLE
Checklist for ONE 1.24.1 Release

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#11707]
### Release Action

- [x] Merge before branch out 
  - [x] Release Note 38b334e5e556355f5f42203d004625bceae9ce73
  - [x] Update debian package changelog ( before branch out ) 8c49ff0a60884cfe49f5404ca127c7be1e6a2b59
  - [x] vconone version up 6a9e8c5c21891cf8a40115695f79d01d23882f46

### Release Package

- Compiler
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
     - [x] test with public models
     - [x] test with in-hose models
  - [x] x64-linux (tar.gz) for Ubuntu 20.04
     - [x] test with public models
     - [x] test with in-hose models

### Release Criteria

- Compiler : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0) 
  - [x] TC line coverage link : http://npuci.mooo.com:8080/job/nnfw/job/release_1.24/job/daily-compiler-coverage/
  - [x] TCM link : https://analysishub.sec.samsung.net/service/analyses/2437460
  - [x] Svace link : https://analysishub.sec.samsung.net/service/analyses/2437453
  - [x] Coverity link : https://analysishub.sec.samsung.net/service/analyses/2437459
  - [x] SAM link : https://analysishub.sec.samsung.net/service/analyses/2437453
  - [x] License Verification :  (verified)

### Miscellaneous

- [x] SSMS
  - Compiler : 
    - [x] Svace_security : https://analysishub.sec.samsung.net/service/analyses/2437454
