### ISSUE TITLE
[onert] Revisit Loss operation

### ISSUE THREAD

**Issue by jyoungyun** [Samsung/ONE#12067]
### What

Now, we implemented the basic loss pass and it worked well.
However, there are many things left to consider about.
To list it up,

- [ ] Separate LossInformation from TrainingInfo
- [ ] Consider ReductionType
   - Need to change every process that Loss goes through must be modified
- [ ] Design Parameters related to Loss
   - MeanSquaredError: x
   - CategoricalCrossentropy: axis, label_smoothing
   - SparseCrossentropy: ignore_class

**Comment by jyoungyun** [comment]
## About reduction type

### Scenario

- User sets the loss type with some parameters like reduction type, axis, label_smoothing etc.
   `NNFW_STATUS nnfw_train_prepare(nnfw_session *session, const nnfw_train_info *info);`
   - [ ] Implement parameter structure per each loss type
   - [ ] Contain this information in nnfw_train_info structure
- User gets the loss value using api.
   `NNFW_STATUS nnfw_train_get_loss(nnfw_session *session, uint32_t index, float *loss);`
   - [ ] Change std::vector<float> loss data type

**Comment by jyoungyun** [comment]
### Todo

- [ ] Use polymorphism instead of union in LossParam
   - from https://github.com/Samsung/ONE/pull/12141#discussion_r1408708279
