### ISSUE TITLE
Checklist for ONE 1.26.0 Release

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#12299]
### Release Action

- [x] Merge before branch out 
  - [x] Release Note #12336
  - [x] Update debian package changelog ( before branch out ) #12344 
- [x] merge after branch out 
  - [x] `master` branch version up 
    - [x] vconone version #12399

### Release Package

- Compiler
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
     - [x] test with public models
     - [x] test with in-hose models
  - [x] x64-linux (tar.gz) for Ubuntu 20.04
     - [x] test with public models
     - [x] test with in-hose models

### Release Criteria

- Compiler : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0) 
  - [x] TC line coverage link : http://npuci.mooo.com:8080/job/nnfw/job/master/job/daily-compiler-coverage/ (84%)
  - [x] TCM link : https://analysishub.sec.samsung.net/service/analyses/2640699 (50.27%)
  - [x] Svace link : https://analysishub.sec.samsung.net/service/analyses/2620618
  - [x] Coverity link : https://analysishub.sec.samsung.net/service/analyses/2620621
  - [x] SAM link : https://analysishub.sec.samsung.net/service/analyses/2620618 (4.38)
  - [x] License Verification :  [one_1260Report.zip](https://github.com/Samsung/ONE/files/13815801/one_1260Report.zip)

### Miscellaneous

- [x] SSMS
  - Compiler : 
    - [x] Svace_security : https://analysishub.sec.samsung.net/service/analyses/2620619
