### ISSUE TITLE
[onert][training] Changing classification layer of pre-trained model and fine-tuning

### ISSUE THREAD

**Issue by mbencer** [Samsung/ONE#12386]
I'm considering introducing a new preprocessing API to onert. I'm pretty new in the project so I am open for your opinions if it makes sense (or is it worth to consider other design).

**Assumptions:** Input and output tensors format are very often not compatible with input data format/expected output format.
**Current possibilities:**
1. Prepare input data manually (rather using host processor) for each inference and process output data to align it with expectations. Disadvantages: Preprocessing on host can be slow. The solution is not easy to share (like there is no preprocessing info in output circle). Code duplication (similar preprocessing code for each model).
2. Use input framework capabilities, like [TF-lite preprocessing](https://www.tensorflow.org/lite/inference_with_metadata/lite_support). Disadvantages: The solution is not scalable.

**Proposition:**
Provide a new API to pre/post processing based on **inserting new ops into the graph** (like `Transpose` for aligning layout, `Resize` for scaling). Note, that preprocessing inserted into a model can be useful also for training.

Possible capabilities:
preprocessing:
- [ ] converting layout
- [ ] color conversion (like from `RGB` to `BGR`)
- [ ] resizing image
- [ ] converting data type
- [ ] mean/scale normalization
post-processing:
- [ ] converting layout
- [ ] converting data type

**Comment by jyoungyun** [comment]
Thank you for your interest and suggestion.

TF-lite preprocessing provides image processing library to make it easier to use input and output of TensorFlow lite model in android. I think the functions related to image processing can be sufficiently performed using other libraries. Therefore, it would not be appropriate for nnfw to support new apis of the function related to image processing.

However, if what you want to do is to **insert new ops to the graph**, it will be useful in various cases. In training, Fine-tuning can be supported by adding a few ops to the existing graph and training only the ops. In this case, inserting new ops into the graph is very useful.

Are you focusing on image processing? Or do you want to introduce new apis to insert new ops to the graph?

**Comment by mbencer** [comment]
@jyoungyun Thank you for a quick and very useful response!
> Are you focusing on image processing? Or do you want to introduce new apis to insert new ops to the graph?
I am considering contribution to ONE in general I am trying to find interesting topics (but with use cases/business justification).
Inserting new ops to the graph itself looks very interesting!
Do you consider such API on [nnfw level](https://github.com/Samsung/ONE/tree/master/runtime/onert/api/include) ?
What's more, I have a few questions around this topic (my purpose is to establish scope with real use cases and to set priorities).
1. Inserting ops only before input/after output of the graph or to any place in the graph?
2. Inserting single ops or subgraphs? if subgraphs, it should be represented as [IGraph](https://github.com/Samsung/ONE/blob/master/runtime/onert/core/include/ir/IGraph.h) or maybe in other way?
3. How place to insert new ops should be determined? Based on experience with similar staff, to avoid ambiguity it can be graph edge represented by operator index + input port index for incoming edges or operator index + output port index for outgoing edges. We can use also op names if provided and unambiguous. I am not familiar with ONE API enough to make decision here.
Please note, that a pair op index + op index can be ambiguous, like for case below:
![image](https://github.com/Samsung/ONE/assets/11331953/a5d8848a-a2f5-4a7b-8d19-59daa1d60a26)
4. Do you see use-cases for other methods to manipulate graph topology (like remove, replace, cut subgraph)?

**Comment by ragmani** [comment]
@mbencer 
First of all, thank you for your interest and suggestions. I think that adding new API to insert new ops to the graph as you suggested is a interesting and useful topic as @jyoungyun mentioned.
Anyway my opinion on your questions is as follows:

> Do you consider such API on [nnfw level](https://github.com/Samsung/ONE/tree/master/runtime/onert/api/include) ?

Yes, I think there is any other way. Are there any other levels you were thinking of?

> 1. Inserting ops only before input/after output of the graph or to any place in the graph?

From the perspective of internal functionality, it would be good to make it possible to insert ops anywhere. But I'm not sure if it's a good idea to allow the user to insert ops anywhere. I think only before input/after output would be enough.
Are there any use-cases to insert ops to any place you were thinking of?

> 2. Inserting single ops or subgraphs? if subgraphs, it should be represented as [IGraph](https://github.com/Samsung/ONE/blob/master/runtime/onert/core/include/ir/IGraph.h) or maybe in other way?

In onert and circle, the meaning of subgraph so far is that it is part of a model rather than part of a graph. In other words, a model has multiple subgraphs only when branched by conflowflow ops(`If`, `While`). Moreover, it is not easy to provide users with API that inserts subgraphs. 



> 4. Do you see use-cases for other methods to manipulate graph topology (like remove, replace, cut subgraph)?

To manipulate graph topology, you should update use-def of operands and inputs/outputs of graph. [PermutationInsertionPass](https://github.com/Samsung/ONE/blob/master/runtime/onert/core/src/compiler/pass/PermutationInsertionPass.cc) is a use-case to insert a new op. It's a bit complicated because a new op is inserted after lowering, but I guess that it might be easier to implement if you insert a new op before lowering.

**Comment by jyoungyun** [comment]
If we introduce new API for inserting ops to graph, I would proceed in the following direction:

1. Insert op after output of the graph.
   - This is because I want to use this API for Transfer learning in on-device training. As you know, the device has a lot of constraints for running application. So it might not be enough memory for full-training. In this case, the user uses the pre-trained model and adds several operations to the bottom of the model for classification. (I haven't yet seen the case of adding to a position other than the bottom.)
2. Insert single op using the IOIndex
   - The user can get the IOIndex using `nnfw_output_size` API. Using IOIndex, we can expand this api to add operation to the graph before and after input/output.

I think that finding the meaningful use-case is more important than implementing the function.
IMHO, adding a new operation to the bottom of the graph is a necessary case now, and other things may be considered gradually. (Of course, the API design should be implemented extensibly.)

**Comment by mbencer** [comment]
> First of all, I want to mention a fact. In circle, the meaning of subgraph so far is that it is part of a model rather than part of a graph. In other words, a model has multiple subgraphs only when branched by conflowflow ops(If, While). In onert, there is one more case when model is partitioned.
I think it is not easy to provide users with API that inserts subgraphs. Do you have any plan to provide users with API for it?
@ragmani In this context I've rather thought if possibility of inserting more than one ops at once should be considered. Implementation details (like using `IGraph`) are secondary.
> I don't recommend using op names because there can be multiple same ops in a subgraph or a model. 
Agree ;)
>  Anyway, I have a question about your suggestion. How are you going to topological sort between graphs if you use graph edges to insert new ops?
A good observation. Probably, it requires re-sorting. Edge is probably better point to cutting graph than inserting new ops.

> IMHO, adding a new operation to the bottom of the graph is a necessary case now, and other things may be considered gradually.
@jyoungyun Sounds like a good starting point. Thank you for for detailed description.

**Comment by jyoungyun** [comment]
It seems that the function of inserting new ops to the graph is not required in the inference feature. Therefore, related work needs to be done with focus on training. And rather than writing a specific api to add one op to the graph, I am thinking of adding a general api in consideration of the user's usability. An enw op is required in the case of transfer learning / fine-tuning. The last layer of the classification model is newly trained to make more specific results. Considering these cases, the parts we need to work on can be divided as follows.

1. Add new operation to the given model graph

- API
   - Add `nnfw_train_add_classification_layer`(TBD)
      - `nnfw_experimental.h` file
      - Add the pre-defined operation sets (i.e., fully_connected + softmax)
      - Replace final classification layer
      - Judge whether this model is classification model
         - Only supports the classification model
- ONERT
   - _to be filled_ 😄 

2. Selective training

- Circle+ schema
   - Add `trainable` option
      - It specifies that this variable will be updated or not
- API
   - `nnfw_train_xxxx`
      - Set `trainable` operation
- ONERT
   - Generate `gradient tensor` in case the `trainable` is true
   - Update `btopolSortOperations()`
   - Generate `backprop tensor` only when this is requires

**Comment by mbencer** [comment]
After a some delay, I've finally started working on this transfer learning/fine tuning feature.

I have already implemented initial version of `nnfw_train_add_classification_layer` but I encountered problem with `nnfw_train_export_circle` when the operator is replaced.
The [current implementation](https://github.com/Samsung/ONE/blob/4a85290faf0b47619e25c8ff2bfcbf0778cd7df4/runtime/onert/api/nnfw/src/nnfw_api_internal.cc#L1618-L1735) of `nnfw_train_export_circle` loads the origin `circle` model and replaces tensors via mmap on raw flatbuffer memory.

To make `nnfw_train_add_classification_layer` working we need here also operators replacement.
Probably it can look like:
```
for(auto op_it=subgs->begin()->operators();op_it!=subgs->end()->operators();++op_it) {
  memcpy(const_cast<uint8_t *>(op_it->Data()), current_op_buffer, size);
}
```
but not sure how to extract `current_op_buffer`. The only solution which I see now is using `luci::CircleExporter` but not sure if we expect such dependency in `onert`.
@jyoungyun Do you maybe have some suggestions about it?

**Comment by mbencer** [comment]
The second thing that I want to confirm is:

> API
>     nnfw_train_xxxx
>         Set trainable operation

@jyoungyun Am I right that an operation here should be determined by the tensor (or tensors) name produced by the operation?

**Comment by jyoungyun** [comment]
@mbencer 

I'm sorry for the late reply. I was thinking about how valuable this job is on the On-Device Training scope, but I didn't find the clear reason so I couldn't response to you.

Here's what I think:

The user who uses the training feature is a model developer. Model developers will verify which structure gives the best performance for focused issue. To figure out, I think they will do this in their machine environment, not on-device. Once the model structure is determined, the model file is moved to the device and the dataset collected on the device is used to train the model file.

So, I couldn't find the situation where this api is needed yet.

Have you thought about what kind of case this api will be needed? I'd like to hear your opinion. :)

**Comment by mbencer** [comment]
@jyoungyun Thank you for response ;)

Just for confirmation - are we still discussing case where `nnfw_train_export_circle` doesn't work correctly if a user uses `nnfw_train_add_classification_layer` (which I am already working on)? It doesn't work because `nnfw_train_export_circle` just replaces tensors buffer in origin circle model (without changing operations).

>Once the model structure is determined, the model file is moved to the device and the dataset collected on the device is used to train the model file.

So do you think here that it's enough to operate here only on in-memory representation and conversion to device format (like 'tvn')? Btw. Is it possible to create `.tvn` from in-memory representation (without `.circle` file)?

**Comment by mbencer** [comment]
@jyoungyun Thank you! It clarifies a lot ;) 
Just for confirmation - so why our initial assumptions were:
>API

    Add nnfw_train_add_classification_layer(TBD)
        nnfw_experimental.h file
I mean why `nnfw_train_add_classification_layer` is planned to be part of `nnfw` API?
And how to realize the point:
> export model to onnx, tf, or tflite
for model trained via nnfw api?

Sorry for misunderstanding - probably my questions can be naive, but I don't understand  design assumptions of the project well yet ;)

**Comment by mbencer** [comment]
I've implemented the draft implementation of fine tuning feature in [PR](https://github.com/Samsung/ONE/pull/12951). The only missing part as I understand is writing unit tests.
I've also prepared test environment to verify this feature:
- [test models](https://github.com/mbencer/OneLearningNotes/tree/mbencer/FineTuning/test_models)
- [training data](https://github.com/mbencer/OneLearningNotes/tree/mbencer/FineTuning/test_models)
- [C++ tool to compare weights before and after training](https://github.com/mbencer/OneLearningNotes/tree/mbencer/FineTuning/circle_compare_weights)
- [Python script](https://github.com/mbencer/OneLearningNotes/blob/mbencer/FineTuning/report.py) which run training for different `epoch`/`batch size`/`frozen ops` config to measure time and accuracy of the training

The test methodology was described [here](https://github.com/mbencer/OneLearningNotes/blob/mbencer/FineTuning/FineTuning.md) and the results are collected in [tests report](https://github.com/mbencer/OneLearningNotes/blob/mbencer/FineTuning/report.md)

@jyoungyun Am I right that the last step to fulfill all requirements on this issue is preparation tutorial (+demo application) where I'll take some test model (like `mobilenet_v2`), change the classification layer in TF/Keras (or using other format), convert such model to circle and demonstrate using fine tuning on device (like you descried in https://github.com/Samsung/ONE/issues/12386#issuecomment-1991071957)?

**Comment by jyoungyun** [comment]
@mbencer 

I didn't notice that you were working on the fine tuning feature. Your draft code is similar to what I was trying to implement. I will look at the code more and give you an answer. :)

**Comment by mbencer** [comment]
@jyoungyun That's true, that many topics were mixed in this issue, but I used your idea from https://github.com/Samsung/ONE/issues/12386#issuecomment-1878140041 and https://github.com/Samsung/ONE/issues/12386#issuecomment-1991071957 ;)

I will be grateful for your review and feedback about https://github.com/Samsung/ONE/pull/12951 (I have no permissions to add reviewers to PR) ;)

If you find a moment please also consider next discussed in this issue (allow to change classification layer)

> @jyoungyun Am I right that the last step to fulfill all requirements on this issue is preparation tutorial (+demo application) where I'll take some test model (like mobilenet_v2), change the classification layer in TF/Keras (or using other format), convert such model to circle and demonstrate using fine tuning on device (like you descried in https://github.com/Samsung/ONE/issues/12386#issuecomment-1991071957)?

**Comment by jyoungyun** [comment]
@mbencer 

When I tested your PR, it works well. I tried to compare TensorFlow and ONERT training using the same model file containing the same weight. And the result is that they're both the almost same loss.

<details>
<summary>Test Result</summary>

I used vgg16 model because mobilenet has a residual network that onert does not support yet.
The little different loss value comes from the difference in float precision between different os.

Model
  ```python
  def createModel():
      IMG_SIZE = (224, 224)
      IMG_SHAPE = IMG_SIZE + (3,)
  
      base_model = tf.keras.applications.VGG16(input_shape=IMG_SHAPE,
                                               include_top=False,
                                               weights='imagenet')
      base_model.trainable = False
      inputs = tf.keras.Input(shape=(224, 224, 3))
      x = base_model(inputs)
      x = tf.keras.layers.GlobalAveragePooling2D()(x)
      outputs = tf.keras.layers.Dense(1000)(x)
      model = tf.keras.Model(inputs, outputs)
  
      return model
  ```

TensorFlow
  ```
  Epoch 1/5
  10/10 [==============================] - 1s 45ms/step - loss: 0.1898 - accuracy: 0.0000e+00
  Epoch 2/5
  10/10 [==============================] - 0s 42ms/step - loss: 0.1801 - accuracy: 0.0000e+00
  Epoch 3/5
  10/10 [==============================] - 0s 41ms/step - loss: 0.1710 - accuracy: 0.0000e+00
  Epoch 4/5
  10/10 [==============================] - 0s 41ms/step - loss: 0.1623 - accuracy: 0.0000e+00
  Epoch 5/5
  10/10 [==============================] - 0s 42ms/step - loss: 0.1541 - accuracy: 0.0000e+00
  ==========================
  Total time: 2.3778
  ```

onert
  ```
  == training parameter ==
  - learning_rate   = 0.01
  - batch_size      = 1
  - loss_info       = {loss = mean squared error, reduction = sum over batch size}
  - optimizer       = sgd
  ========================
  Epoch 1/5 - time: 146.231ms/step - loss: [0] 0.1898
  Epoch 2/5 - time: 147.723ms/step - loss: [0] 0.1802
  Epoch 3/5 - time: 145.275ms/step - loss: [0] 0.1711
  Epoch 4/5 - time: 141.840ms/step - loss: [0] 0.1625
  Epoch 5/5 - time: 143.406ms/step - loss: [0] 0.1544
  ===================================
  ```

</details>

I want to merge your PR by dividing it into several PRs. And unless it's a necessary modification, how about merging it later, such as introducing the `TranableOperation` class?

I'm tying to the `trainable` attribute in TrainInfo schema file.
If this attribute is introduced, we can do fine-tuning circle+ file without additional settings.

**Comment by mbencer** [comment]
@jyoungyun Thank you for the tests!

About dividing into smaller PRs and waiting for circle schemat changes - sure ;)
FYI: I am on vacation until the next Tuesday so it will take a moment ;)

**Comment by jyoungyun** [comment]
I made a draft code to introduce the `trainable` attribute in circle+ training info. And I tested this code with your draft PR and it works fine.

I fixed your draft code to store trainable operation indexes instead of frozen operation indexes so that circle file is not trained by default. This is because the circle file is a model for inference. So it would be better to train the circle model only when there is an explicit request from the user. The commit for this change is as follows: https://github.com/Samsung/ONE/pull/12984/commits/f87513c520363cc9609f1f8b5d158b37245a248e.

Detailed test results can be seen here:
<details>
<summary>details</summary>

- vgg16_transfer_meta.circle training info meta:
  ```
  $ python3 circleplus.py --show_meta ./vgg16_transfer_meta.circle 
  version:
  operatorCodes:
  subgraphs:
  description:
  buffers:
  metadataBuffer:
  metadata:
                  [CIRCLE_TRAINING]
                  version: 1
                  optimizer: 0
                  optimizerOptType: 1
                  optimizerOpt: <circle_traininfo_generated.SGDOptionsT object at 0x7fa04aab6760>
                          learningRate: 0.009999999776482582
                  lossfn: 2
                  lossfnOptType: 3
                  lossfnOpt: <circle_traininfo_generated.MeanSquaredErrorOptionsT object at 0x7fa04aab67c0>
                  epochs: 0
                  batchSize: 1
                  lossReductionType: 0
                  trainable: [18 19]
  signatureDefs:
  ```
- onert_train test
  ```
  $ ./Product/out/bin/onert_train --modelfile ./tools/generate_circleplus/vgg16_transfer_meta.circle  --load_input:raw ../Personal/models/data/imagenet_a/test.input.10.bin --load_expected:raw ../Personal/models/data/imagenet_a/t
  est.output.10.bin
  Model Expected Filename ../Personal/models/data/imagenet_a/test.output.10.bin
  Model Input Filename ../Personal/models/data/imagenet_a/test.input.10.bin
  Model Filename ./tools/generate_circleplus/vgg16_transfer_meta.circle
  == training parameter ==
  - learning_rate   = 0.01
  - batch_size      = 1
  - loss_info       = {loss = mean squared error, reduction = sum over batch size}
  - optimizer       = sgd
  ========================
  Epoch 1/5 - time: 142.327ms/step - loss: [0] 0.1898
  Epoch 2/5 - time: 145.744ms/step - loss: [0] 0.1802
  Epoch 3/5 - time: 141.669ms/step - loss: [0] 0.1711
  Epoch 4/5 - time: 140.023ms/step - loss: [0] 0.1625
  Epoch 5/5 - time: 145.260ms/step - loss: [0] 0.1544
  ===================================
  MODEL_LOAD   takes 21.3030 ms
  PREPARE      takes 115.7390 ms
  EXECUTE      takes 7154.6070 ms
  - Epoch 1      takes 1423.2750 ms
  - Epoch 2      takes 1457.4430 ms
  - Epoch 3      takes 1416.6950 ms
  - Epoch 4      takes 1400.2250 ms
  - Epoch 5      takes 1452.6020 ms
  ===================================
  ```
- tensorflow test
  ```
  vgg16$ python3 tensorflow_run.py  -m ./transfer -i ../data/imagenet_a/test.input.10.bin -l ../data/imagenet_a/test.output.10.bin --data_length 10 --batch_size 1 --epoch 5 --loss mse --optimizer sgd --learning_rate 0.01
  Epoch 1/5
  10/10 [==============================] - 1s 45ms/step - loss: 0.1898 - accuracy: 0.0000e+00
  Epoch 2/5
  10/10 [==============================] - 0s 42ms/step - loss: 0.1801 - accuracy: 0.0000e+00
  Epoch 3/5
  10/10 [==============================] - 0s 41ms/step - loss: 0.1710 - accuracy: 0.0000e+00
  Epoch 4/5
  10/10 [==============================] - 0s 41ms/step - loss: 0.1623 - accuracy: 0.0000e+00
  Epoch 5/5
  10/10 [==============================] - 0s 42ms/step - loss: 0.1541 - accuracy: 0.0000e+00
  ==========================
  Total time: 2.3778
  ```

</details>

**Comment by jyoungyun** [comment]
### Todo

- [ ] Introduce trainable_ops attribute to circle_traininfo schema

**Comment by mbencer** [comment]
@jyoungyun Thank you for explonation ;)

I would like to precise two cases:
1. Am I right that trainable indexes set via `nnfw_train_disable_node_update` and `nnfw_train_enable_node_update` should overrides settings from circle plus?
2. If yes, should such custom indexes replace the original ones during `train_export_circle`?

**Comment by jyoungyun** [comment]
@mbencer 

> 1. Am I right that trainable indexes set via `nnfw_train_disable_node_update` and `nnfw_train_enable_node_update` should overrides settings from circle plus?

Right. The default training info is from the circle+ file. However, when the user requests the trainng info to be updated, the existing training info is overwritten from the circle+ to a given setting from the user.
User requests using APIs have a higher priority than the training info in circle+ file.

> 2. If yes, should such custom indexes replace the original ones during `train_export_circle`?

The `train_export_circle` API does not export training info. This API only exports the circle file including the updated weights. And I'm going to introduce an API for exporting circle+ file. This API replaces the original training info with new data.

> 3. Will circle plus model representation contain loos function operator (as a usual op in the graph)? If yes, it has influence on op indexes.

The circle+ file does not contain the loss operation in the graph. The loss information is included in the training info. ONERT generates a loss operation in the graph according to the training info data in the preparation stage. Therefore, the op indexes does not affect this.

> And I have one proposition to consider: In the current version a user need to know number of operators in the model in order to indicate trainable ops (in typical scenario it will be the last ops). Maybe we should allow to use syntax like `--trainable_ops_idx=55-*` but we need a new method in `nnfw api` to check this number - sth like `nnfw_operators_size`. Does it make sense for you?

Unfortunately, there is no way to get the operation index from the circle file directly. We need to use additional tool like Netron. Currently, it is an inevitable constraint. I don't think there are many cases where users change the trinable op index at runtime. And in this case, the developer must know the operation indexes of what they want to train. So your point is appropriate, but I think we can think about it later. How about it?

**Comment by mbencer** [comment]
@jyoungyun Thank you for the answers!

> So your point is appropriate, but I think we can think about it later. How about it?

Sure ;)

**Comment by mbencer** [comment]
@jyoungyun I have one more case to confirm. If a user run `onert_train` on non-circle+ model without `--trainable_ops_idx` argument. the training should be run for all ops?

**Comment by jyoungyun** [comment]
@mbencer 

> @jyoungyun I have one more case to confirm. If a user run `onert_train` on non-circle+ model without `--trainable_ops_idx` argument. the training should be run for all ops?

The circle model file is for inference. Therefore, if the user wants to train the model, I think setting `trainable_ops_idx` is a priority. Basically, if there is no `trainable_ops_idx` option, the circle model is not trained even if the user calls this model using the `onert_train` tool with hyper-paramteters for training.

We have a runtime weekly meeting today. I will discuss this issue and share the details here.

**Comment by mbencer** [comment]
The feature was implemented so I'm closing the issue. Please re-open if some questions/other requests
