### ISSUE TITLE
[onert] Truncate backpropagation

### ISSUE THREAD

**Issue by Aeren1564** [Samsung/ONE#12612]
### What

Some node does not need to be visited during backpropagation due to every node that can reach it having no trainable parameters.

Let's make backpropagation ignore such nodes.

draft: https://github.com/Samsung/ONE/pull/12621

## Task
- [x] https://github.com/Samsung/ONE/pull/12622
- [x] https://github.com/Samsung/ONE/pull/12623
- [x] https://github.com/Samsung/ONE/pull/12682

**Comment by jyoungyun** [comment]
This item may reduce training time by not visiting unnecessary backpropagation. 👍

**Comment by Aeren1564** [comment]
This task has been completed. Closing.
