### ISSUE TITLE
Checklist for ONE 1.27.0 Release

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#13283]
### Release Action

- [x] Merge before branch out 
  - [x] Release Note #13310
  - [x] Update debian package changelog ( before branch out ) #13311
- [x] merge after branch out 
  - [x] `master` branch version up 
    - [x] vconone version #13312

### Release Package

- Compiler
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
     - [x] test with public models
     - [x] test with in-hose models
  - [x] x64-linux (tar.gz) for Ubuntu 20.04
     - [x] test with public models
     - [x] test with in-hose models

### Release Criteria

- Compiler : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0) 
  - [x] TC line coverage link : http://npuci.mooo.com:8080/job/nnfw/job/release_1.27/job/daily-compiler-coverage/ (84%)
  - [x] TCM link : https://analysishub.sec.samsung.net/service/analyses/3071109 (50.15%)
  - [x] Svace link : https://analysishub.sec.samsung.net/service/analyses/3071107
  - [x] Coverity link : https://analysishub.sec.samsung.net/service/analyses/3071108
  - [x] SAM link : https://analysishub.sec.samsung.net/service/analyses/3071107
  - [x] License Verification :  [one_1270Report.zip](https://github.com/user-attachments/files/16023602/one_1270Report.zip)

### Miscellaneous

- [x] SSMS
  - Compiler : 
    - [x] Svace_security : https://analysishub.sec.samsung.net/service/analyses/3071107

**Comment by mhs4670go** [comment]
@seanshpark Feel free to let me know things to be added more in the contents below.

# Release Note 1.27.0

## ONE Compiler

- Support more Op(s): CircleGRU, CircleRelu0To1
- Support more optimization option(s): `resolve_former_customop`, `--forward_transpose_op`, 
    `fold_shape`, `remove_gather_guard`, `fuse_add_with_conv`, `fold_squeeze`, `fuse_rsqrt`
- Support converting onnx fake quantize model
- Introduce global configuration target feature
- Introduce command schema feature
