### ISSUE TITLE
[onert/train] Attach auxiliary tensors to tensor builder

### ISSUE THREAD

**Issue by zetwhite** [Samsung/ONE#13282]
## Background 

`backendtrain/ops/*Layer` has extra(auxiliary) tensors used for `backward()`.

For example,

https://github.com/Samsung/ONE/blob/60683ad7293d2a18a7939dc49bcea77d8e09b352/runtime/onert/backend/train/ops/FullyConnectedLayer.h#L61-L65 

https://github.com/Samsung/ONE/blob/60683ad7293d2a18a7939dc49bcea77d8e09b352/runtime/onert/backend/train/ops/ConvolutionLayer.h#L56-L60 
 

These tensors are allocated when `KernelGenerator` visits each operation. 

https://github.com/Samsung/ONE/blob/60683ad7293d2a18a7939dc49bcea77d8e09b352/runtime/onert/backend/train/ops/FullyConnectedLayer.cc#L88-L96

## What 

These auxiliary tensors always hold memory after being configured.
So, Adding these tensors into TensorBuilder to use a memory planner might be helpful.

**Comment by zetwhite** [comment]
# How 

* draft https://github.com/Samsung/ONE/pull/13326 
* (note) all works are done in `onert/backed/train` area. 
* `using ExtraTensor = Tensor;` 

-----------------------

### `ops`

Each layer needs to be added two functions : 

```cpp 
// backend/train/ops/FullyConnectedLayer.h
class FullyConnectedLayer : public exec::train::ITrainableFunction,
                            public cpu::ops::FullyConnectedLayer
{
	... 
  // Return how many extra tensors are necessary in FullyConnected Layer
  static ExtraTensorRequests requestExtraTensors(const IPortableTensor *weights,
                                                 const IPortableTensor *input,
                                                 const IPortableTensor *back_prop_output,
                                                 ir::Activation activation);

  // Assign extra tensors to the tensor pointer member variable 
  void configureExtraTensors(std::vector<ExtraTensor *> extra_tensors);
  ... 
}
```

```cpp 
struct ExtraTensorRequest
{
  ir::OperandInfo info;
  ir::Layout layout;
  ExtraTensorLifeTime lifetime;
};
```

----------------------

### `ExtraTensorGenerator`  

This generator is used inside of `train::BackendContext::genTrainingTensors()`. 
Visiting each operator in the graph, 
  - get `ExtraTensorReqeusts` info from corresponding Layer 
  - register tensors to the `TensorBuilder`

---------------------------------------

### `TensorBuilder` 

```cpp 
class ExtraTensorIndex
{
  ir::OperationIndex op_index;
  uint32_t sub_index;
};
``` 

```cpp 
class TensorRegistry
{
  ... 
  std::unordered_map<ExtraTensorIndex, std::unique_ptr<ExtraTensor>> _extra; 
};
```
TensorRegister in TensorBuilder stores (ExtraTensorIndex, ExtraTensor) pairs. 


------------------------------------

## `genKernels`

While generating Kernels, make each layer point to each tensor from TensorRegistry. 

```cpp 
void KernelGenerator::visit(const ir::train::operation::FullyConnected &node)
{
	... 
    auto out_back_prop_tensor = getBackPropOut(out_index);

    fn->configureBackward(in_tensor, weights_tensor, out_tensor, in_back_prop_tensor,
                          weights_grad_tensor, bias_grad_tensor, out_back_prop_tensor, activation,
                          weights_format);

	// also set extra tensors
    auto extra_tensors = getExtraTensors(node);
    fn->configureExtraTensors(extra_tensors);
	... 
```

**Comment by zetwhite** [comment]
After some work on https://github.com/Samsung/ONE/pull/13486, 
I checked how much memory was reduced compared to the master branch. 

### mnist 

* model : https://github.com/Samsung/ONE/issues/11389 

* master
  * optimizer : adam
  * batchsize : 32
  * 54.2 MB (56874848 bytes)

* on draft 
  * optimizer : adam
  * batchsize : 32
  *  38.4 MB (40314240 bytes)

```bash 
	[      ALLOC     ] allocation capacity: 11360128 # non-const 
	[      ALLOC     ] allocation capacity: 1938880  # trainable 
	[      ALLOC     ] allocation capacity: 11360000 # back-prop 
	[      ALLOC     ] allocation capacity: 1938880  # gradient
	[      ALLOC     ] allocation capacity: 3877760  #  opt variable
	[      ALLOC     ] allocation capacity: 3211264  # disposable 
	[      ALLOC     ] allocation capacity: 6627328  # extra tensors 
```

* extra tensors allocation reduces : 23187968(22.1MB) -> 6627328 (6.3 MB) 
   

### mobile net v2 

* model : https://github.com/Samsung/ONE/issues/12325 

* master
  * optimizer : adam
  * batchsize : 10 
  * 1217.3 MB (1276482848 bytes) 
 
*  on draft 
	  * optimizer : adam 
	  * batch : 10 
	  * 923913328 (881.1MB) 

```bash 
	[      ALLOC     ] allocation capacity: 361362288 # non-const
	[      ALLOC     ] allocation capacity: 13951408  # trainable 
	[      ALLOC     ] allocation capacity: 361362240 # back-prop
	[      ALLOC     ] allocation capacity: 13951408  # gradient 
	[      ALLOC     ] allocation capacity: 27902816  # opt variable 
	[      ALLOC     ] allocation capacity: 49032960  # disposable
	[      ALLOC     ] allocation capacity: 96350208  # extra tensors 
``` 

 
* extra tensors allocation reduces : 448920128(428.1MB) -> 96350208 (91.8MB)

/cc @ragmani

**Comment by ragmani** [comment]
After applying all PRs related to the draft #13305, the other allocation capacity will be reduces as follows:

### mnist
33686880(32.1 MB) -> 25187616(24.0MB)
```
non-const : 11360128 -> 11341056
trainable : 1938880 -> 1938880
back-prop : 11360000 -> 6423808
gradient : 1938880 -> 1606144
optimizer variables : 3877728 -> 3877728
disposable : 3211264 -> 0
```

### mobile net v2
827562720(789.2MB) -> 490938032(468.1MB)
```
non-const : 361362288 -> 361362240
trainable : 13951312 -> 13951312
back-prop : 361362240 -> 97241920
gradient : 13951312 -> 5124000
optimizer variables : 27902608 -> 10248000
disposable : 49032960 -> 3010560
```

**Comment by zetwhite** [comment]
I'll start to make PR based on the draft.
Draft is somehow rough, I'll trim it while making a PR. 

### TODO 

* Core 
	- [ ] Introduce ExtraTensor
	- [ ] Introduce ExtraTensorReqeust 
	- [ ] Add `RequestExtraTensor` to the ITrainableFunction 
	- [ ] Update TrainabeGraph to hold `OpIndex to TensorRequest` mapping 

* Backend/train 
   - [ ] Introduce ExtraTensorIndex 
   - [ ] Update MemoryManager, MemoryPlanner, MemoryPlannerFactory to use template 
   - [ ] Update TensorRegistry to have `ExtraTensorIndex to ExtraTensor` 
   - [ ] Update TensorManager to have `ExtraMemoryManager` 
   - [ ] Update TensorBuilder Interface to include `notifyFirst(ExtraTensorIndex&)` `notifyLast(ExtraTensorIndex&)` .. etc 
   - [ ] Update `genKernels` to register, plan, allocate extra tensors 
   - support ops
      - [ ] BianryArithmetic
      - [ ] Convolution
      - [ ] Depthwise Covolution
      - [ ] FC 
      - [ ] Pool

**Comment by zetwhite** [comment]
> I'll start to make PR based on the draft. ( #13486 ) Draft is somehow rough, I'll trim it while making a PR.
> 
> ### TODO
> * Core
>   
>   * [x]  Introduce ExtraTensor [[onert] Introduce ExtraTensor #13576](https://github.com/Samsung/ONE/pull/13576)
>   * [x]  Rename ExtraTensor -> LayerScopeTensor [[onert] Rename ExtraTensor to LayerScopeTensor #13845](https://github.com/Samsung/ONE/pull/13845)
>   * [x]  Add LiftimeInfo to LayerScopeTensor  [[onert] Add lifetime enum to LayerScopeTensor #13861](https://github.com/Samsung/ONE/pull/13861)
>   * [x]  Update ITrainableFunction [[onert] Add registerLayerScopeTensors to ITrainableFuntion #13980](https://github.com/Samsung/ONE/pull/13980)
> * Backend/train
>   
>   * [x]  Introduce ExtraTensorIndex [[onert] Introduce ExtraTensorIndex #13605](https://github.com/Samsung/ONE/pull/13605)
>   * [x]  Templatize memory planners, memory planner factory, memory manager
>     
>     * [[onert] Templatize memory planners in train backend #13892](https://github.com/Samsung/ONE/pull/13892)
>     * [[onert/backend] Templatize MemoryPlannerFactory in train #13984](https://github.com/Samsung/ONE/pull/13984)
>     * [ [onert/backend] Introduce LayerScopeMemoryManager #14021](https://github.com/Samsung/ONE/pull/14021)
>   * [ ]  Update TensorRegistry to have `LayerScopeTensorIndex, LayerScopeTensor`
>     
>     * [[onert/backend] Add LayerScopeTensors into TensorRegistry #14024](https://github.com/Samsung/ONE/pull/14024)
>   * [ ]  Update TensorManager to have `LayerScopeMemoryManager`
>   * [ ]  Update TensorBuilder Interface to include `notifyFirst(LayerScopeTensorIndex&)` `notifyLast(LayerScopeTensorIndex&)` .. etc
>   * [ ]  Update `genKernels` to register, plan, allocate extra tensors
>   * support ops
>     
>     * [ ]  BianryArithmetic
>     * [ ]  Convolution
>     * [ ]  Depthwise Covolution
>     * [ ]  FC
>     * [ ]  Pool
