### ISSUE TITLE
[onert-micro] Checklist for onert-micro 2.0-pre

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#13313]
### Release Action

- [x] Merge before branch out 
  - [x] Release Note : https://github.com/Samsung/ONE/pull/13334 
  - [x] update onert-micro version file : https://github.com/Samsung/ONE/pull/13347
- [x] branch out  : https://github.com/Samsung/ONE/tree/release/onert-micro/2.0.0-pre
- [ ] merge after branch out
  - [ ] `master` branch version up : 

### Release Criteria

 TEM (>4.0), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0, DC > 4.0)

#### measurement on master Before branch out 
  - [x] TEM coverage link : [>4.0](https://github.sec.samsung.net/RS7-RuntimeNTools/ONE-workflow-playground/actions/runs/10996360)
  - [x] TCM link : [50.64](hhttps://analysishub.sec.samsung.net/service/analyses/3085204)
     + https://github.com/Samsung/ONE/pull/13316
  - [x] Svace link : [4.0](https://analysishub.sec.samsung.net/service/analyses/3085614)
     + #13320
  - [x] Coverity link : [4.0](https://analysishub.sec.samsung.net/service/analyses/3085203)
     + #13321
  - [x] SAM link : [> 4.0 (DC > 4.0)](https://analysishub.sec.samsung.net/service/analyses/3085614)
     + #13272
  - [x] License Verification : [onert-micro-1.1-protex Report.zip](https://github.com/user-attachments/files/16023485/onert-micro-1.1-protex.Report.zip) (commit: e234798281bc)

#### measurement on release branch
  - [ ] TEM coverage link : 
  - [ ] TCM link : 
  - [ ] Svace link : 
  - [ ] Coverity link :
  - [ ] SAM link : 

#### TizenRT 4 Integration
  - [ ] PR to TizenRT repo

**Comment by chunseoklee** [comment]
@BalyshevArtem How about using version 2.0.0-pre since refactoed and api has been changed ?

**Comment by BalyshevArtem** [comment]
> @BalyshevArtem How about using version 2.0.0-pre since refactoed and api has been changed ?

Yes, I am good with it :)
