### ISSUE TITLE
Checklist for 1.27.1 compiler release

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#13381]
### Release Action

- [x] Release Note : #13400

### Release Package

- Compiler
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
     - [x] test with public models
     - [x] test with in-hose models
