### ISSUE TITLE
Checklist for 1.27.2 compiler release

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#13422]
### Release Action

- [x] Release Note : #13427

### Release Package

- Compiler
  - [x] x64-linux (tar.gz) for Ubuntu 20.04
     - [x] test with public models
     - [x] test with in-hose models

---

Current release is for recent changes.

- [one-cmds] Adding codegen, profile interface
- [debian] Update man pages
