### ISSUE TITLE
Checklist for ONE 1.28.0 Runtime Release 

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#13442]
### Release Action

- [x] Merge before branch out 
  - [x] Release Note #13443
- [x] merge after branch out 
  - [x] `master` branch version up 
    - [x] Runtime  #13464
      - [x] document version in `/docs/conf.py`
      - [x] tizen spec file
      - [x] nnfw_version.h
      - [x] onert aar version
    - [x] Compiler #13465
      - [x] vconone version
  - ~Tizen upstream branch update to released one~

### Release Package

- [x] Runtime 
  - [x] arm64-android (tar.gz) for Android 
  - [x] arm64-android (aar) for Android 
  - [x] arm-tizen (rpm) for Tizen 8.0
  - [x] arm-linux (tar.gz) for Ubuntu
  - [x] x64-linux (tar.gz) for Ubuntu
  - [x] nnfw-devel
  - [x] nnfw-plugin-devel

### Release Criteria

- [x] Runtime : TEM (>4.0), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0, DC > 4.0)
  - [x] ~TEM coverage link~ TC line coverage link: [Passed](http://npuci.mooo.com:8080/job/nnfw/job/release_1.28/job/daily-arm-runtime-coverage/2/)
  - [x] TCM link: [Passed](https://analysishub.sec.samsung.net/service/analyses/3120635)
  - [x] Svace link: [Passed](https://analysishub.sec.samsung.net/service/analyses/3120636)
  - [x] Coverity link: [Passed](https://analysishub.sec.samsung.net/service/analyses/3121005)
  - [x] SAM link: [4.15](https://analysishub.sec.samsung.net/service/analyses/3120636)
  - ~License Verification~

### ~Miscellaneous~
