### ISSUE TITLE
Checklist for ONE 1.29.0 Release

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#13796]
### Release Action

- [x] Merge before branch out 
  - [x] Release Note #13832
  - [x] Update debian package changelog ( before branch out ) #13833
- [x] merge after branch out 
  - [x] `master` branch version up 
    - [x] vconone version #13841

### Release Package

- Compiler
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
     - [x] test with public models
     - [x] test with in-hose models
  - [x] x64-linux (tar.gz) for Ubuntu 20.04
     - [x] test with public models
     - [x] test with in-hose models
  - [x] x64-linux (tar.gz) for Ubuntu 22.04
     - [x] test with public models
     - [x] test with in-hose models

### Release Criteria

- Compiler : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0) 
  - [x] TC line coverage link : http://npuci.mooo.com:8080/job/nnfw/job/relase_1.29/job/daily-compiler-coverage/ (84%)
  - [x] TCM link : https://analysishub.sec.samsung.net/service/analyses/3224541 (50.14%)
  - [x] Svace link : https://analysishub.sec.samsung.net/service/analyses/3224537
  - [x] Coverity link : https://analysishub.sec.samsung.net/service/analyses/3224540
  - [x] SAM link : https://analysishub.sec.samsung.net/service/analyses/3224537
  - [x] License Verification :  [one_1290Report.zip](https://github.com/user-attachments/files/16791000/one_1290Report.zip)

**Comment by mhs4670go** [comment]
# Release Note 1.29.0

## ONE Compiler

- Support more optimization option(s): `--transform_sqrt_div_to_rsqrt_mul`, `--fold_mul`,
    `--fuse_add_to_fullyconnected_bias`, `--fuse_mul_to_fullyconnected_weights`,
    `--fuse_mul_with_fullyconnected`,
- Add more optimization: `CanonicalizePass`
- _tflite2circle_ supports more data types: FLOAT64, UINT64, UINT32, UINT16
- _luci-interpreter_ supports more data types on some ops
- Support multiple option names in command schema
