### ISSUE TITLE
[compiler] support RoPE Op

### ISSUE THREAD

**Issue by ys44kim** [Samsung/ONE#13972]
### What

Lets' support RoPE (Rotary Position Embedding) and fuse

The image below is part of the token generation model.   
This graph is fused with rope op.   
![rope](https://github.com/user-attachments/assets/a00be28e-3494-4a68-961a-a48d0703a479)   

#### Input
- (1, attention head num, 1,  head_dim)
- sin_table : (1,1,1,head_dim), the value determined depending on what position the token is in in the sequence.
- cos_table : (1,1,1,head_dim), the value determined depending on what position the token is in in the sequence.

### Task
- [x] luci.lang
- [x] circle_schema
- [x] luci.import
- [x] res/TensorFlowLiteRecipes, res/CircleRecipes
- [x] luci.service
- [x] luci.pass
- [x] luci.partition
- [x] luci.logex
- [x] luci.export 
- [x] luci_interpreter
- [x] circle.dump
- [x] circle2circle
- [x] luci.tests
- [x] luci-pass-value-test
- [x] circle2circle-dredd-recipe-test

**Comment by jinevening** [comment]
FYI, There are two different types of RoPE implementation.

1. GPT-NeoX style
2. GPT-J style
(See https://github.com/huggingface/transformers/issues/25199 for more details)

The RoPE you want to support is NeoX style. It would be better to mention that somewhere (maybe luci.lang).

**Comment by seanshpark** [comment]
> two different types of RoPE implementation.

Do they have different I/O, attribute configuration?
or just has different decomposed graph?

**Comment by jinevening** [comment]
I think they may have the same I/O, but have different op patterns.

**Comment by glistening** [comment]
@jinevening and @seanshpark 

I talked with @hseok-oh in runtime perspective and circle schema maintenance.

- I think two different style of neo-x and gpt could be in a circle op by adding `mode` parameter as `llama.cpp` does.
- We can go with only neo-x only for a while.
- Historically, we add new op in backward from 255. I would like to use 1 op if possible to allocate two op slots for rope.

Consequently, if compiler is okay, we may go with rope op (implicitly `neo-x` by default).
Then, we can try to add `gpt` style when `gpt` became necessary in the same op.
If it does not go as we expected, we may add a second new op like `rope_gpt_style`.

**Comment by ys44kim** [comment]
Draft: #13978

**Comment by jinevening** [comment]
I'm ok with https://github.com/Samsung/ONE/issues/13972#issuecomment-2340091808 if @seanshpark approves :)

**Comment by glistening** [comment]
@ys44kim Could you please use `GPTJ` instead of `GPT`? [^1]

[^1]: https://github.com/vllm-project/vllm/issues/747
https://github.com/huggingface/transformers/issues/25199
https://velog.io/@nawnoes/ALiBi-Postion-Embedding

**Comment by ys44kim** [comment]
> @ys44kim Could you please use `GPTJ` instead of `GPT`? `GPT` seems too broad [1](#user-content-fn-1-035865deea0c540cd8a2be7de7f3737e).

@glistening 
I was thinking about what to do with the enum name. so, I wanted to hear your opinion on what to do.
i think NEOX and GPTJ, NEOX has no prefix and  GPTJ has prefix, so I was worried about how to deal with GPT.
So, Why don't we both attach GPT, GPT_NEOX, GPT_J?

**Comment by glistening** [comment]
@ys44kim `GPT_NEOX` and `GPT_J` is also okay for me.
