### ISSUE TITLE
[onert-micro] Checklist for onert-micro 2.0 release

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#14114]
### Release Action

- [ ] Merge before branch out 
  - [ ] Release Note :
  - [ ] update onert-micro version file : 
- [ ] branch out  : 
- [ ] merge after branch out
  - [ ] `master` branch version up : 

### Release Criteria

 TEM (>4.0), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0, DC > 4.0)

#### measurement on master Before branch out 
  - [x] TEM coverage link : [>4.0](https://github.sec.samsung.net/RS7-RuntimeNTools/ONE-workflow-playground/actions/runs/12776406)
  - [x] TCM link : [50](hhttps://analysishub.sec.samsung.net/service/analyses/3300291)
  - [x] Svace link : [4.0](https://analysishub.sec.samsung.net/service/analyses/3300287)
  - [x] Coverity link : [4.0](https://analysishub.sec.samsung.net/service/analyses/3300289)
  - [x] SAM link : [> 4.0 (DC > 4.0)](https://analysishub.sec.samsung.net/service/analyses/3300287)
  - [x] License Verification : [onert_micro_20_ProtexReport.zip](https://github.com/user-attachments/files/17158713/onert_micro_20_ProtexReport.zip)

#### measurement on release branch
  - [x] TEM coverage link : [>4.0]()
  - [x] TCM link : [50%]() 
  - [x] Svace link : [>4.0]()
  - [x] Coverity link : [>4.0]()
  - [x] SAM link : [>4.0]()
