### ISSUE TITLE
checklist for release v1.5.0

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#1450]
## Checklist
  - [x] Branch out : https://github.com/Samsung/ONE/tree/release/1.5.0
  - [x] Release Note (#1649)
  - [x] runtime binary for android
  - [x] runtime binary for tizen (rpm)
  - [x] runtime binary for arm-linux (tar.gz)
  - [x] compiler binary for x64-linux (tar.gz)
  - [x] runtime : svace, coverity critical 0
       - [x] svace link  : https://code.sec.samsung.net/ahub/service/analyses/105410  
       - [x] coverity link : https://code.sec.samsung.net/ahub/service/analyses/105411
  - [x] runtime : line coverage 80% (http://npuci.mooo.com:8080/job/nnfw/job/master/job/daily-arm-runtime-coverage/664/)
  - [x] version up
    - [x] tizen spec file (#1624)
    - [x] nnfw_version.h (#1685)
    - [x] document version in `/docs/conf.py` (#1923)
  - [x] compiler : svace, coverity critical 0
    - [x] svace link : https://code.sec.samsung.net/ahub/service/analyses/107970
    - [x] coverity link : https://code.sec.samsung.net/ahub/service/analyses/110047

**Comment by chunseoklee** [comment]
@Samsung/nnfw svace and coverity criteria should be meet for release ?

**Comment by hseok-oh** [comment]
@chunseoklee We're checking svace and coverity everyday internally, so it is not difficult to meet svace and coverity criteria.

**Comment by chunseoklee** [comment]
> @chunseoklee We're checking svace and coverity everyday internally, so runtime is not difficult to meet svace and coverity criteria.

Opps, I have updated the comment. 
I mean compiler's svace and coverity. Have we decided to include comiler's svace/coverity result into release criteria ?

**Comment by chunseoklee** [comment]
> > @chunseoklee We're checking svace and coverity everyday internally, so runtime is not difficult to meet svace and coverity criteria.
> 
> Opps, I have updated the comment.
> I mean compiler's svace and coverity. Have we decided to include comiler's svace/coverity result into release criteria ?

There are too much(100 >) defects on https://code.sec.samsung.net/ahub/service/analyses/107872. It is hard to say we will meet coverity criteria soon.

**Comment by seanshpark** [comment]
>There are too much(100 >) defects on https://code.sec.samsung.net/ahub/service/analyses/107872. It is hard to say we will meet coverity criteria soon.

@mhs4670go can you please take a look?

**Comment by chunseoklee** [comment]
> > There are too much(100 >) defects on https://code.sec.samsung.net/ahub/service/analyses/107872. It is hard to say we will meet coverity criteria soon.
> 
> @mhs4670go can you please take a look?

Fortunately, all the defects seems like false-alarm. 

@mhs4670go could you please update coveirty link and status ?

**Comment by lemmaa** [comment]
@chunseoklee , we need to update document version, too.
PTAL https://github.com/Samsung/ONE/pull/1923

**Comment by seanshpark** [comment]
There are lots of `runtime binary for `... and I don't see any links how to make them.
Can anyone add a link explaining how to? or is there no document yet?

**Comment by lemmaa** [comment]
> There are lots of `runtime binary for `... and I don't see any links how to make them.
> Can anyone add a link explaining how to? or is there no document yet?

@seanshpark , sorry, that is my fault. I haven't been able to follow up #246 for a long time. I will proceed as soon as possible. Thank you for remind me! 

@Samsung/one , However, now that the overall structure is in place, all your active participation will also be of great help. Thank you in advance!

**Comment by glistening** [comment]
@chunseoklee, @lemmaa Please see #1933. Please let me know if there is more to update about version.

**Comment by hyunsik-yoon** [comment]
Can I add one proposal? The release doc mentions one runtime and one compiler but the name of release files use old names such as `nnfw` and `nncc`. I am afraid that people will be curious of many names.
Maybe from 1.6.0, I think that it would be better to use, e.g., `ONE_runtime.tar.gz`, `ONE_compiler.tar.gz`.

![image](https://user-images.githubusercontent.com/63768207/83827463-63e20800-a719-11ea-9d83-fd5512cdfd01.png)
