### ISSUE TITLE
[compiler] Add BCQ testcase

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE#1517]
Currently, BCQ testcases for compiler are absent.
Let's add testcases by using `circlechef`.

### Todo (Draft)
- [x] circlechef/circle #2859
- [x] circlechef/core #2858
- [x] circlechef/proto #2846
- [x] res/CircleRecipes/BCQFullyConnected #2788
- [x] res/CircleRecipes/BCQGather #2923
- [x] Enable luci/tests #2924

### Draft

- #2739

**Comment by llFreetimell** [comment]
I think that it would be better to create BCQ testcases at internal repository.

**Comment by seanshpark** [comment]
> I think that it would be better to create BCQ testcases at internal repository.

I was thinking of creating simple tflite recipe file for the test material.
Can we create this recipe in this repo?

**Comment by llFreetimell** [comment]
I agree for creating simple recipe file for test.

However, as BCQ format is upgraded, interpretation of BCQ operation inputs becomes harder than before.
As a result, creating a recipe file may consume much time I think and we have a high priority to run some models.

Therefore, I want to proceed with real test material which is generated by real model at first, and then make a simple recipe file :)

By the way, there is a possibility to use `circlechef`, not `tflchef` for the test material :)

**Comment by llFreetimell** [comment]
### 20200630 Update

Main comment is edited

**Comment by llFreetimell** [comment]
Related PRs are all merged, close!
