### ISSUE TITLE
[Documentation] Let's start working on improving the documentation.

### ISSUE THREAD

**Issue by lemmaa** [Samsung/ONE#246]
In the process of moving to open source, we intentionally excluded existing documents for several reasons. Now it's time to organize those documents.

I have two goals for organizing documents:

1. Organize it to be structured as it is in the repository itself.
2. Organize for convenience when using a tool such as Doxygen to create a reference book.

For that, I'm going to make a list of what will be included in the documentation we'll be writing from now on. 

**\*UPDATE: I plan to use [Sphinx](https://www.sphinx-doc.org) as a tool for document rendering. The rendered document will be provided through http://readthedocs.org.**

### Task list

- [ ] ~Define document layout under `docs` folder https://github.com/Samsung/ONE/issues/246#issuecomment-620023394~
- [x] Push the entire layout consisting of empty documents to the repo #882
- [ ] Write the contents of each document
- [ ] Remove outdated documents `docs/nnfw` , `docs/nncc`.
- [ ] Update Doxyfile so that all documents are included as index tables in the output of doxygen

I hope your opinion on it.

**Comment by lemmaa** [comment]
https://github.com/Samsung/ONE/issues/2472#issuecomment-658534229

> I expect the documentation of runtime/* and compiler/* to be about the implementation structure or design philosophy, even roadmap, if the how-to/* documentation is for usage or troubleshooting.
> overview/* If we're dealing with an history or overview, runtime/* and compiler/* takes care of professional details.
