### ISSUE TITLE
checklist for release v1.6.0

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#2547]
## Checklist
  - [x] Branch out : https://github.com/Samsung/ONE/tree/release/1.6.0
  - [x] Release Note : #2667
       - Compiler @seanshpark @llFreetimell 
       - Runtime @chunseoklee @hseok-oh @wateret 
  - [x] runtime binary for android
  - [x] runtime binary for tizen (rpm)
  - [x] runtime binary for arm-linux (tar.gz)
  - [x] runtime binary for x64-linux (tar.gz)
  - [x] compiler binary for x64-linux (tar.gz)
  - [x] runtime : svace, coverity critical 0
       - [x] svace link  :  #2603
         + link for release branch : https://code.sec.samsung.net/ahub/service/analyses/135831
       - [x] coverity link :  #2522 ( critical, major defect 0 on 8876d6e )
         + link for release branch :  https://code.sec.samsung.net/ahub/service/analyses/135867
  - [x] runtime line coverage 80% (http://npuci.mooo.com:8080/job/nnfw/job/master/job/daily-arm-runtime-coverage/)
  - [x] version up #2657
    - [x] tizen spec file
    - [x] nnfw_version.h
    - [x] document version in `/docs/conf.py`
  - [x] compiler : svace, coverity critical 0
    - [x] svace link
    - [x] coverity link : https://code.sec.samsung.net/ahub/service/analyses/130850

**Comment by hseok-oh** [comment]
I've checked tizen (xu4) test and confirm it passed all test now.

**Comment by hseok-oh** [comment]
Current runtime line coverage: 82%

**Comment by seanshpark** [comment]
Compiler frontend new operators since 1.5.0
- AddN, ArgMin, BatchMatmul, Ceil, DepthToSpace, Floor, InstanceNormalize,
L2Normalization, L2Pool, LessEqual, Log, LogSoftmax, PReLU, Rank, ReduceMin(Min),
ResizeBilinear, Round, ScatterND, Sqrt, TransposeConv, BCQGather,
BCQFullyConnected

**Comment by hseok-oh** [comment]
Runtime CPU backend new operation support

- BatchMatMul, BroadcastTo, Einsum, FusedBatchNorm, MatrixBandPart, Range, ReduceAll

Runtime CPU backend new quant8 support 

- Add

**Comment by wateret** [comment]
Runtime WG1

- Support dynamically shaped tensors
    - Support static shape inference (input resizing)
    - Support dynamic shape inference (general resizing)
- Support Control Flow operations
    - IF and WHILE
    - Fully support static and dynamic tensors
- API updates
    - Introduce `nnfw_set_input_tensorinfo` for input resizing
    - `nnfw_input_tensorinfo` and `nnfw_output_tensorinfo` behavior have changed to return updated tensorinfo

**Comment by chunseoklee** [comment]
https://github.com/Samsung/ONE/tree/release/1.6.0 branch has been created.

**Comment by hseok-oh** [comment]
Package is generated
http://npuci.mooo.com:8080/job/nnfw/job/release_1.6/job/daily-publish-package/

**Comment by chunseoklee** [comment]
#2746 notice for tf2.3 rc0

**Comment by chunseoklee** [comment]
1.6.0 is released w/o #2746

**Comment by chunseoklee** [comment]
closed by done
