### ISSUE TITLE
[onert] Use and free ExternalData mmapped while running if possible

### ISSUE THREAD

**Issue by YongseopKim** [Samsung/ONE#2580]
as-is
- #2077 #2385 makes onert use mmap() instead of loading all of tflite file contents
- CachedDatas are allocated by using mmapped pointer
- BackendTensors which are constants are allocated by CachedDatas

to-be
- [x] ExternalDatas would be allocated by using mmaped pointer if CachedData is unnecessary https://github.com/Samsung/ONE/issues/2751
- [x] If layout is not changed, BackendTensor's buffer would be set by the ExternalData #3039 
- [x] After some ops' prepare() such as Optimized Conv2D or FCHybrid of ruy, unnmap ExternalData if possible. https://github.com/Samsung/ONE/issues/2749 
- (optinoal) I also think this is supported by onert_api such as `onert_set_preference(USE_EXTERNAL_DATA)`

(This task could start after https://github.com/Samsung/ONE/pull/1325.)

/cc @chunseoklee @periannath @dhdh-oh @Samsung/nnfw

**Comment by YongseopKim** [comment]
draft: https://github.com/YongseopKim/ONE/tree/test/use_external_data_pulled

target
- odroid-xu4 & ubuntu
- cpu backend

## inception_v3

Latency
- unit: ms
- warming up 5 & running 5

|                 | MODEL_LOAD | PREPARE | EXECUTE |
|-----------------|------------|---------|---------|
| tflite          | 16         | 0.5     | 1565    |
| onert-master    | 235        | 1000    | 1278    |
| onert-draft     | 33         | 769     | 1251    |

RSS
- unit: kb
- physically on ram

|                 | MODEL_LOAD | PREPARE | EXECUTE |
|-----------------|------------|---------|---------|
| tflite          | 8580       | 9752    | 228017  |
| onert-master    | 101760     | 204152  | 136860  |
| onert-draft     | 7292       | 21860   | 132173  |

## mv2

Latency

|                 | MODEL_LOAD | PREPARE | EXECUTE |
|-----------------|------------|---------|---------|
| tflite          | 13         | 0.1     | 154     |
| onert-master    | 62         | 722     | 283     |
| onert-draft     | 26         | 742     | 285     |

RSS

|                 | MODEL_LOAD | PREPARE | EXECUTE |
|-----------------|------------|---------|---------|
| tflite          | 5692       | 5692    | 38816   |
| onert-master    | 21668      | 42280   | 33234   |
| onert-draft     | 7060       | 15128   | 30891   |

**Comment by YongseopKim** [comment]
If you are interested in the internal models, please see [here](https://github.sec.samsung.net/gist/YongseopKim/7a3df77d5d293af3c00ae73847896037)

**Comment by ragmani** [comment]
> - If layout is not changed, BackendTensor's buffer would be set by the ExternalData

You should add a condition that BackendTensor is `IPortableTensor` introduced at f0333336adc5b23697b25582468be76e6042ce50

**Comment by YongseopKim** [comment]
Done
