### ISSUE TITLE
[circle-quantizer] Separate quantization functionalities from circle2circle

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#2617]
Currently, quantization is supported by `circle2circle`, which not only performs quantization but also various optimizations. To keep the tool smaller and simpler, it would be better to make a separate tool for quantization.

For this, following things must be done.

- [x] 1. Remove the codes related to quantization from circle2circle #2621

- [x] 2. Update `quantize` function in luci (`quantize` should be revised for being called alone) #2629

- [x] 3. Introduce a new executable circle-quantizer #2645

- [x] 4. Update pota-quantization-value-test #2668

**Comment by jinevening** [comment]
@seanshpark I think 1-2-3 is the least number of steps. 3 must be done after 2 (otherwise, the circle-quantizer will not work properly). And it is better to do 2 after 1 (2 may affect the current circle2circle).

**Comment by seanshpark** [comment]
Have to thought of the name for this? `circlequantizer` ?

**Comment by jinevening** [comment]
@seanshpark I got it. For now, I will use `circle-quantizer` for the consistency with circle-inspect, circle-verify, etc. I will avoid using `_` as much as possible :)

**Comment by jinevening** [comment]
I close this issue because all tasks were done.
