### ISSUE TITLE
Checklist for release 1.7.0

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#2756]
## Checklist
  - [x] Branch out : https://github.com/Samsung/ONE/tree/release/1.7.0
  - [x] Release Note : https://github.com/Samsung/ONE/pull/3420
      - Compiler @seanshpark @llFreetimell
      - Runtime @chunseoklee @hseok-oh @wateret
  - [x] runtime binary for android (tar.gz)
  - [x] runtime binary for android (aar)
  - [x] runtime binary for tizen (rpm)
  - [x] runtime binary for arm-linux (tar.gz)
  - [x] runtime binary for x64-linux (tar.gz)
  - [x] compiler binary for x64-linux (tar.gz)
  - [x] runtime : svace, coverity (critical=0), SAM(>4.0), TCM
      - [x] svace link : https://code.sec.samsung.net/ahub/service/analyses/154205
      - [x] coverity link : https://code.sec.samsung.net/ahub/service/analyses/154271
      - [x] AM link : https://code.sec.samsung.net/architecturemanager/app/sam/NNAS/nnfw_runtime/20200724_1.7.0/overview
      - [x] TCM link : http://npuarchive.mooo.com/share/1.7.0/ONE-Runtime-1.7.0-tcm-output.zip
  - [x] runtime line coverage (>80%) link : http://npuci.mooo.com:8080/job/nnfw/job/release_1.7/job/daily-arm-runtime-coverage/
  - [x] version up : https://github.com/Samsung/ONE/pull/3419
      - [x] tizen spec file
      - [x] nnfw_version.h
      - [x] document version in `/docs/conf.py`
  - [x] compiler : svace, coverity(critical=0), SAM(>4.0), TCM
      - [x] svace link : https://code.sec.samsung.net/ahub/service/analyses/152400
      - [x] coverity link : https://code.sec.samsung.net/ahub/service/analyses/156889
      - [x] AM link : https://code.sec.samsung.net/architecturemanager/app/sam/NNAS/nnfw_compiler/20200724_1.7.0/overview
      - [x] TCM link : http://npuarchive.mooo.com/share/1.7.0/ONE-Compiler-1.7.0-tcm-output.zip
        - TCM result for base commit : http://npuarchive.mooo.com/share/tcm-base/ONE-Compiler-ab2a31ca6f34d3b5fa6d5f4f4268a919b806177c-tcm-output.zip
  - [x] compiler : line coverage (>80%) link : http://npuci.mooo.com:8080/job/nnfw/job/release_1.7/job/daily-compiler-coverage/3/cobertura
  - [x] nncc preset update if needed

**Comment by chunseoklee** [comment]
Please add release note content. 

Compiler @seanshpark @llFreetimell
Runtime @chunseoklee @hseok-oh @wateret

**Comment by seanshpark** [comment]
Compiler supports more operations
- MatrixDiag, MatrixSetDiag, ReverseSequence, ReverseV2, SegmentSum, SelectV2, SparseToDense, Where

New command line interface for user interface consistancy
- one-import: imports conventional models files to circle
   - one-import-tf: imports TensorFlow model to circle
   - one-import-tflite: imports TensorFlow lite model to circle
- one-optimize: circle optimize command
- one-quantize: circle quantize command
   - supports float32 to uint8, layer wise (for Conv series)
- one-pack: package command
- one-prepare-venv: prepares python virtual environment for import TensorFlow model
- one-codegen: backend(if available) code generator

**Comment by llFreetimell** [comment]
- Nothing special with BCQ works.
- Minor bug fix

**Comment by hseok-oh** [comment]
Runtime CPU backend operation support

- LogSoftmax, SpaceToBatchND

Runtime CPU backend quant8 operation support

- Logistic, Mul, Tanh, SpaceToBatchND, Transpose, Sub, Max, Min, Less, Greater, GreaterEqual, LessEqual, Equal, NotEqual

**Comment by lemmaa** [comment]
Added links to SAM and TCM reports to the check list.

**Comment by lemmaa** [comment]
Added  `runtime binary for android (aar)` to the check list

**Comment by wateret** [comment]
Runtime WG1

- NNFW API
    - Introduce basic asynchronous execution API
- Optimization
    - Remove dynamic tensor overhead from static models

**Comment by seanshpark** [comment]
`nncc-1.7.0.tar.gz` at http://npuci.mooo.com:8080/job/nnfw/job/release_1.7/job/daily-publish-package/lastSuccessfulBuild/artifact/ works OK

**Comment by cgbahk** [comment]
AM part updated

**Comment by lemmaa** [comment]
TCM result for runtime updated. Will prepare the result for compiler soon.

**Comment by lemmaa** [comment]
> ... Will prepare the result for compiler soon.

TCM result for compiler updated.

@seanshpark , 27 TCs with No Assertion were detected. PTAL. It should be fixed in the 1.8.0 release.

<details>

Test | Test Case | Checker | File | Line
-- | -- | -- | -- | --
NN Compiler | FormattedTensorShapeTest.BracketFormat | GTEST.NO_ASSERTION | /compiler/locop/src/FormattedTensorShape.test.cpp | 25
NN Compiler | CircleIfTestDeath.invalid_output_count_NEG | GTEST.NO_ASSERTION | /compiler/luci/lang/src/Nodes/CircleIf.test.cpp | 46
NN Compiler | CircleIfTestDeath.invalid_arity_NEG | GTEST.NO_ASSERTION | /compiler/luci/lang/src/Nodes/CircleIf.test.cpp | 41
NN Compiler | L2NormalizeTest.Uint8Quantized | GTEST.NO_ASSERTION | /compiler/luci-interpreter/src/kernels/L2Normalize.test.cpp | 48
NN Compiler | GetNthPercentileTest.FloatWithNegative | GTEST.NO_ASSERTION | /compiler/record-minmax/tests/RecordFunction.test.cpp | 66
NN Compiler | GetNthPercentileTest.SigleElement | GTEST.NO_ASSERTION | /compiler/record-minmax/tests/RecordFunction.test.cpp | 80
NN Compiler | GetNthPercentileTest.Simple | GTEST.NO_ASSERTION | /compiler/record-minmax/tests/RecordFunction.test.cpp | 37
NN Compiler | GetNthPercentileTest.Float | GTEST.NO_ASSERTION | /compiler/record-minmax/tests/RecordFunction.test.cpp | 52
NN Compiler | GetNthPercentileTest.Edge | GTEST.NO_ASSERTION | /compiler/record-minmax/tests/RecordFunction.test.cpp | 29
NN Compiler | LogisticTest.Uint8 | GTEST.NO_ASSERTION | /compiler/luci-interpreter/src/kernels/Logistic.test.cpp | 52
NN Compiler | ModuleTest.consturctor | GTEST.NO_ASSERTION | /compiler/luci/lang/src/Module.test.cpp | 21
NN Compiler | LeakReluTest.Uint8Simple | GTEST.NO_ASSERTION | /compiler/luci-interpreter/src/kernels/LeakyRelu.test.cpp | 66
NN Compiler | LeakReluTest.FloatSimple | GTEST.NO_ASSERTION | /compiler/luci-interpreter/src/kernels/LeakyRelu.test.cpp | 51
NN Compiler | NodeExecution_BiasEncode.f32 | GTEST.NO_ASSERTION | /compiler/locomotiv/src/Node/BiasEncode.test.cpp | 95
NN Compiler | NodeExecution_BiasEncode.s32 | GTEST.NO_ASSERTION | /compiler/locomotiv/src/Node/BiasEncode.test.cpp | 93
NN Compiler | CircleWhileTestDeath.invalid_arity_NEG | GTEST.NO_ASSERTION | /compiler/luci/lang/src/Nodes/CircleWhile.test.cpp | 41
NN Compiler | CircleWhileTestDeath.invalid_output_count_NEG | GTEST.NO_ASSERTION | /compiler/luci/lang/src/Nodes/CircleWhile.test.cpp | 46
NN Compiler | NodeExecution_MatMul.s32_4x2_2x6 | GTEST.NO_ASSERTION | /compiler/locomotiv/src/Node/MatMul.test.cpp | 159
NN Compiler | NodeExecution_MatMul.f32_2x3_3x3 | GTEST.NO_ASSERTION | /compiler/locomotiv/src/Node/MatMul.test.cpp | 121
NN Compiler | TensorFlowLiteImport.Dummy | GTEST.NO_ASSERTION | /compiler/luci/import/src/Importer.test.cpp | 23
NN Compiler | TransposeConvTest.Uint8FiltersTest | GTEST.NO_ASSERTION | /compiler/luci-interpreter/src/kernels/TransposeConv.test.cpp | 93
NN Compiler | TransposeConvTest.Uint8Simple | GTEST.NO_ASSERTION | /compiler/luci-interpreter/src/kernels/TransposeConv.test.cpp | 87
NN Compiler | TransposeConvTest.FloatTwoFiltersTest | GTEST.NO_ASSERTION | /compiler/luci-interpreter/src/kernels/TransposeConv.test.cpp | 73
NN Compiler | TransposeConvTest.FloatSimple | GTEST.NO_ASSERTION | /compiler/luci-interpreter/src/kernels/TransposeConv.test.cpp | 61
NN Compiler | CircleCustomTest.constructor_NEG | GTEST.NO_ASSERTION | /compiler/luci/lang/src/Nodes/CircleCustom.test.cpp | 38
NN Compiler | LinearV1FormatterTest.simple | GTEST.NO_ASSERTION | /compiler/locop/src/FormattedGraph.test.cpp | 24
NN Compiler | HermesTest.simple_usecase | GTEST.NO_ASSERTION | /compiler/hermes/src/hermes.test.cpp | 21

</details>
