### ISSUE TITLE
[cker/ruy] Upgrade ruy library

### ISSUE THREAD

**Issue by periannath** [Samsung/ONE#3231]
I think it is better to upgrade ruy library to latest version.

#### Pros
- Performance improvement?
- Changes in `ruy::PrepacekdCached` class
  - ~~It seems we can check whether weight is cached or not~~
  - ~~Candidate solution for #3225~~

Source code link and cmake file should be updated to use latest ruy library.

~~I'll upgrade ruy library and checks its performance.~~

Reopens this issue since cache policy in latest ruy library is needed.

- [x] Add cpuinfo library to infra #4248
- [x] Add cpuinfo tar ball to packaging #4250
- [x] Upgrade cmake file for ruy library #4273
- [x] Upgrade ruy tar ball #4274

/cc @YongseopKim

**Comment by periannath** [comment]
I'll use https://github.com/google/ruy/commit/34ea9f4993955fa1ff4eb58e504421806b7f2e8f for ruy library since it is used in tensorflow v2.3.0-rc1.

**Comment by periannath** [comment]
### Changes in `PrepackedCache`

#### Cache key in previous ruy library
```cc
     auto cache_key = std::make_pair(reinterpret_cast<void*>(params->run_kernel),                                                                                                                               
                                     params->src[Side::kLhs].data);  
```
  - Function initialized in ruy library and weight data are used as key

#### Cache key in updated ruy library
```cc
  struct Key {
    // The source matrix's data pointer.
    const void* src_data;
    // The packed matrix's layout, see PEMat::layout.
    PMatLayout packed_layout;
    // The packed matrix's zero point (for integer-quantized matrices only).
    std::int32_t zero_point;
  };
```
  - Weight data, packed matrix layout, and zero point are used as key
  - PackedMatrix created inside ruy library is needed to search cache
  - Still, it is hard to search `PrepackedCache` outside of ruy library...

**Comment by periannath** [comment]
### Changes in cache policy
- Cache policy is changed in recent ruy library

#### Cache policy in previous ruy library
- kNoCache : No cache
- kCacheLHSOnNarrowMul (**default**) : Cache when `batch_size <= 4`

#### Cache policy in updated ruy library
- kNeverCache : No cache
- kCacheIfLargeSpeedup (**default**) : Cache when `batch size <= cols of packed matrix`
  - `cols of packed matrix` : Can be 2, 4, or 8. Depends on platform and kernel type
- kCacheIfSignificantSpeedup : Cache when `batch size <= 4 * cols of packed matrix`
- kAlwaysCache : Always cache

**Comment by periannath** [comment]
### Performance improvement?
- Updated ruy library is a little bit slower
  - Some weight tensors are not cached by new cache policy
  - Memory consumption is slightly reduced

**Comment by periannath** [comment]
I'm closing this issue since there's no significant difference between current and updated ruy library.

**Comment by periannath** [comment]
Reopens this issue since cache policy in latest ruy library is needed.

**Comment by periannath** [comment]
I've uploaded draft PR #4074. Updated ruy library increases inference time for my target model.
I've found that it does not use neon dotprod instruction.

**Comment by periannath** [comment]
ruy libray is using `cpuinfo` library to detect cpu features. https://github.com/google/ruy/commit/6f14203f7f1b180a211875d0236e48ee0652549a

I'll update `CMakeLists.txt` of ruy library to download and use `cpuinfo` library.

**Comment by periannath** [comment]
#4074 now correctly builds `cpuinfo` and updated ruy library.

Patch for `cpuinfo` is copied from tflite v2.3. (Should I have to add license to `.patch` file?)

There's one thing to fix. The cache policy is hard-coded at `NeonTensorUtils.h`. I think it is better to set cache policy at `ExternalContext`.

**Comment by periannath** [comment]
@Samsung/nnfw How can I add source tars for tizen build? I needs to add or upgrade three source tars (clog, cpuinfo, and ruy).

**Comment by chunseoklee** [comment]
> @Samsung/nnfw How can I add source tars for tizen build? I need to add or upgrade three source tars (clog, cpuinfo, and ruy).

1. Put tar sources to packaging dir

2. Untar them on setup step in nnfw.spec file 

Please see how ruy lib is built on nnfw.spec

**Comment by periannath** [comment]
Done.
