### ISSUE TITLE
[onert] Support while operation

### ISSUE THREAD

**Issue by ragmani** [Samsung/ONE#344]
Draft PR : #154

### Information
- `WHILE` op's illustration
https://github.com/tensorflow/community/raw/master/rfcs/20190315-tflite-control-flow/while_buffer.png

- Test cases
  ~NNAPI tests : while* of https://android.googlesource.com/platform/frameworks/ml/+/refs/heads/master/nn/runtime/test/specs/V1_3/~

### TODO
- [ ] Introduce WHILE op into NN API
- [x] Introduce WHILE op into ONE API
- [x] Support While operation on backends
- [x] Support copying tensors between subgraphs
