### ISSUE TITLE
[Compiler] Supporting version control in FuseBCQPass

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE#3481]
For now, we do not consider about version control for BCQ.
Let's support version control in `FuseBCQPass` in `luci`.

- Preceded work : #3174
- Draft : #3329 

### Todo

- [x] Move lambda function to anonymous namespace #3504
- [x] Introduce BCQFuser #3511
- [x] Remove unused converter #3522
- [x] Add version control #3532

**Comment by llFreetimell** [comment]
Done!
