### ISSUE TITLE
Checklist for Release v1.8.0

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#3746]
### Release Action

- [x] Release Note : https://github.com/Samsung/ONE/pull/3765
- [x] Branch out : https://github.com/Samsung/ONE/tree/release/1.8.0
  - [x] `master` branch version up : https://github.com/Samsung/ONE/pull/3768
    - [x] tizen spec file
    - [x] nnfw_version.h
    - [x] document version in `/docs/conf.py`

### Release Package

- Runtime 
  - [x] arm64-android (tar.gz) for Android 10
  - [x] arm64-android (aar) for Android 10
  - [x] arm-tizen (rpm) for Tizen 6.0 M2
  - [x] arm-linux (tar.gz)  for Ubuntu 18.04
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
  - [x] nnfw-devel
  - [x] nnfw-plugin-devel
- Compiler
  - [x] x64-linux (tar.gz) for Ubuntu 18.04

### Release Criteria

- Runtime : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0)
  - [x] TC line coverage link : 82% (http://npuci.mooo.com:8080/job/nnfw/job/release_1.8/job/daily-arm-runtime-coverage/)
  - [x] TCM link : http://npuci.mooo.com/tcm/1.8.0/runtime/tcm-output/result.html (12/156/52) 50%
    - TCM result for base commit : http://npuci.mooo.com/tcm/base/runtime/tcm-output-base-ab1a04a7/result.html (0/56/2)
  - [x] Svace link : https://code.sec.samsung.net/ahub/service/analyses/166726
  - [x] Coverity link : https://code.sec.samsung.net/ahub/service/analyses/166727
  - [x] SAM link : [4.1/5](https://code.sec.samsung.net/architecturemanager/app/sam/NNAS/nnfw_runtime/20200813_a38bbba/overview)
- Compiler : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0) 
  - [x] TC line coverage link : 89% (http://npuci.mooo.com:8080/job/nnfw/job/release_1.8/job/daily-compiler-coverage/)
  - [x] TCM link : http://npuci.mooo.com/tcm/1.8.0/compiler/tcm-output/result.html (0/1004/425) 68%
    - TCM result for base commit : http://npuci.mooo.com/tcm/base/compiler/tcm-output-base-ab2a31ca/result.html (10/391/4)
  - [x] Svace link : https://code.sec.samsung.net/ahub/service/analyses/165501 (@llFreetimell)
  - [x] Coverity link : https://code.sec.samsung.net/ahub/service/analyses/165522 (@mhs4670go)
  - [x] SAM link : [4.1/5](https://code.sec.samsung.net/architecturemanager/app/sam/NNAS/nnfw_compiler/20200813_a38bbba/overview)

### Miscellaneous

- [x] nncc preset update if needed

**Comment by chunseoklee** [comment]
@seanshpark @hseok-oh @wateret @chunseoklee Please comment release note's content for 1.8.0

**Comment by wateret** [comment]
Runtime WG1

- Rename headers
    - Rename `nnfw_dev.h` to `nnfw_experimental.h`
    - ~~Rename `nnfw_debug.h` to `nnfw_internal.h`~~ This is not release target

**Comment by seanshpark** [comment]
### Compile frontend

New command line interface for user interface consistancy
- one-import-bcq: Imports BCQ(Binary coding quantized) TensorFlow model 
- Commands now support `--version` option to show version number

Compiler supports more operations
- No additional operators on this release. We are working on several operators.

Changes
- Experimental support for TensorFlow 2.3.0 (TensorFlow 1.3.2 is our official support version)
- Support more operators in luci-interpreter
- Enhancing one-quantizer

**Comment by hseok-oh** [comment]
Runtime CPU backend operation support
- BatchToSpaceND, L2Normalization, ReLU6, ResizeBilinear, SpaceToDepth, SplitV, StatelessRandomUniform

Runtime CPU backend quant8 operation support
- BatchToSpaceND, L2Normalization, Pad, PadV2, ResizeBilinear, Slice, Quantize, SpaceToDepth, Sum

**Comment by hseok-oh** [comment]
Packages:
http://npuci.mooo.com:8080/job/nnfw/job/release_1.8/job/daily-publish-package/2/

**Comment by seanshpark** [comment]
package test of nncc done :)

**Comment by lemmaa** [comment]
>   - [ ] TCM link : http://npuci.mooo.com/tcm/1.8.0/runtime/tcm-output/result.html (12/156/52) 50%

@wateret , @chunseoklee , @mhs4670go , we have issue in TCM result. We need to clear 12 `No Assertion Test Cases` (http://npuci.mooo.com/tcm/1.8.0/runtime/tcm-output/result.html#defects ) to release.

**Comment by chunseoklee** [comment]
> > * [ ]  TCM link : http://npuci.mooo.com/tcm/1.8.0/runtime/tcm-output/result.html (12/156/52) 50%
> 
> @wateret , @chunseoklee , @mhs4670go , we have issue in TCM result. We need to clear 12 `No Assertion Test Cases` (http://npuci.mooo.com/tcm/1.8.0/runtime/tcm-output/result.html#defects ) to release.

After brief review, all the defects except GenModelTests.cc is caused by inability of MACRO EXPENSION of tool.

**Comment by seanshpark** [comment]
> is caused by inability of MACRO EXPENSION of tool.

```cxx
TEST_F(ValidationTestSessionCreated, close_and_create_again)
{
  NNFW_ENSURE_SUCCESS(nnfw_close_session(_session));
  NNFW_ENSURE_SUCCESS(nnfw_create_session(&_session));
}
```
where
```cxx
#define NNFW_ENSURE_SUCCESS(EXPR) ASSERT_EQ((EXPR), NNFW_STATUS_NO_ERROR)
```

**Comment by hseok-oh** [comment]
Updated package:
http://npuci.mooo.com:8080/job/nnfw/job/release_1.8/job/daily-publish-package/5/artifact/
