### ISSUE TITLE
Checklist for 1.9.0 release

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#4030]
### Release Action

- [x] Release Note : https://github.com/Samsung/ONE/pull/4067
- [x] Branch out 
  - [x] `master` branch version up : https://github.com/Samsung/ONE/pull/4093
    - [x] tizen spec file
    - [x] nnfw_version.h
    - [x] document version in `/docs/conf.py`
    - [x] onert aar version

### Release Package

- Runtime 
  - [x] arm64-android (tar.gz) for Android 10
  - [x] arm64-android (aar) for Android 10
  - [x] arm-tizen (rpm) for Tizen 6.0 M2
  - [x] arm-linux (tar.gz)  for Ubuntu 18.04
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
  - [x] nnfw-devel
  - [x] nnfw-plugin-devel
- Compiler
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
     - [x] test with public models
     - [x] test with in-hose models

### Release Criteria

- Runtime : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0)
  - [x] TC line coverage link : 82% on master(http://npuci.mooo.com:8080/job/nnfw/job/master/job/daily-arm-runtime-coverage/740/)
  - [x] TCM link : http://npuci.mooo.com/tcm/1.9.0/runtime/tcm-output/result.html (0/179/65) 51%
    - TCM result for base commit : http://npuci.mooo.com/tcm/base/runtime/tcm-output-base-ab1a04a7/result.html (0/56/2)
  - [x] Svace link : https://code.sec.samsung.net/ahub/service/analyses/179175
  - [x] Coverity link : https://code.sec.samsung.net/ahub/service/analyses/179176
  - [x] SAM link : [4.23/5.0](https://code.sec.samsung.net/architecturemanager/app/sam/NNAS/nnfw_runtime/20200902_fccce3d/overview)
  - [x] License Verification
- Compiler : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0) 
  - [x] TC line coverage link : 89% on master(http://npuci.mooo.com:8080/job/nnfw/job/master/job/daily-compiler-coverage/69/)
  - [x] TCM link : http://npuci.mooo.com/tcm/1.9.0/compiler/tcm-output/result.html (0/1030/441) 68%
    - TCM result for base commit : http://npuci.mooo.com/tcm/base/compiler/tcm-output-base-ab2a31ca/result.html (10/391/4)
  - [x] Svace link : https://code.sec.samsung.net/ahub/service/analyses/179179
  - [x] Coverity link : https://code.sec.samsung.net/ahub/service/analyses/179178
  - [x] SAM link : [4.35/5.0](https://code.sec.samsung.net/architecturemanager/app/sam/NNAS/nnfw_compiler/20200902_fccce3d/overview)
  - [x] License Verification : complete for tizen's tizen branch(1.8.0) 

### Miscellaneous

- [x] nncc preset update if needed
- [ ] SSMS
  - Runtime : https://ssms.sec.samsung.net/#/sdl/project/765
    - [ ] Svace_security : https://code.sec.samsung.net/ahub/service/analyses/183379  - Compiler : https://ssms.sec.samsung.net/#/sdl/project/767
    - [ ] Svace_security : https://code.sec.samsung.net/ahub/service/analyses/182582

**Comment by chunseoklee** [comment]
@seanshpark @wateret @chunseoklee @hseok-oh Please attach release note content.

**Comment by llFreetimell** [comment]
@chunseoklee `License` added :)

**Comment by seanshpark** [comment]
### Compile frontend

Compiler supports more operations
- NonMaxSuppressionV4, NonMaxSuppressionV5, PadV2, Unique

Changes
- Quantization enhancements: channel wise UINT8 quantization(Conv2D, DepwiseConv, TransposeConv, FullyConnected)
- Experimental requantization from INT8 to UINT8
- Adding more operator value tests
- tf2tfliteV2 supports conversion from Keras model, saved model
- Refactoring for better maintenance long codes using visitor patterns

**Comment by hseok-oh** [comment]
Runtime backend operation support
- CPU backend: RANK
- CPU backend qasymm uint8: LOG_SOFTMAX
- ACL-CL backend: LEAKY_RELU, RESIZE_NEAREST_NEIGHBOR

**Comment by wateret** [comment]
Optimization

- Copy Elimination between compatible backends

Operation Implementation

- Operations with same parameters are unified

**Comment by cgbahk** [comment]
SAM part updated

**Comment by hseok-oh** [comment]
Package files: http://npuci.mooo.com/nnfw_ci_daily/package/1.9.0/
cc/ @wateret

**Comment by hseok-oh** [comment]
Package generated: http://npuci.mooo.com:8080/job/nnfw/job/release_1.9/job/daily-publish-package/2/artifact/
Uploaded: http://npuci.mooo.com/nnfw_ci_daily/package/1.9.0/

**Comment by lemmaa** [comment]
> TCM link : http://npuci.mooo.com/tcm/1.9.0/runtime/tcm-output/result.html (21/168/54) 46% <--- WARNING

TCM report generated. The runtime result does not meet the 50% criterion.

/cc @wateret , @chunseoklee

**Comment by chunseoklee** [comment]
published binary link : http://npuci.mooo.com:8080/job/nnfw/job/release_1.9/job/daily-publish-package/

**Comment by chunseoklee** [comment]
@wateret Please resolve TCM warning for runtime

**Comment by mhs4670go** [comment]
```shell
#!/bin/bash

mkdir temp && pushd temp

# arm64-android (tar.gz) for Android 10
wget http://npuci.mooo.com:8080/job/nnfw/job/release_1.9/job/daily-publish-package/lastSuccessfulBuild/artifact/nnfw-1.9.0-android-aarch64.tar.gz
# arm64-android (aar) for Android 10

# arm-tizen (rpm) for Tizen 6.0 M2
wget http://npuci.mooo.com:8080/job/nnfw/job/release_1.9/job/daily-publish-package/lastSuccessfulBuild/artifact/nnfw-1.9.0-rpm-armv7l.tar.gz
# arm-linux (tar.gz) for Ubuntu 18.04
wget http://npuci.mooo.com:8080/job/nnfw/job/release_1.9/job/daily-publish-package/lastSuccessfulBuild/artifact/nnfw-1.9.0-linux-armv7l.tar.gz
# x64-linux (tar.gz) for Ubuntu 18.04
wget http://npuci.mooo.com:8080/job/nnfw/job/release_1.9/job/daily-publish-package/lastSuccessfulBuild/artifact/nnfw-1.9.0-linux-x86_64.tar.gz
# nnfw-devel
wget http://npuci.mooo.com:8080/job/nnfw/job/release_1.9/job/daily-publish-package/lastSuccessfulBuild/artifact/nnfw-devel-1.9.0.tar.gz
# nnfw-plugin-devel
wget http://npuci.mooo.com:8080/job/nnfw/job/release_1.9/job/daily-publish-package/lastSuccessfulBuild/artifact/nnfw-plugin-devel-1.9.0.tar.gz
# nncc x64-linux (tar.gz) for Ubuntu 18.04
wget http://npuci.mooo.com:8080/job/nnfw/job/release_1.9/job/daily-publish-package/lastSuccessfulBuild/artifact/nncc-1.9.0.tar.gz

popd

./git_release.sh --tag 1.9.0 \
--release_note ../../docs/release/1.9/release-note-1.9.0.md \
--asset temp/nnfw-1.9.0-android-aarch64.tar.gz \
--asset temp/nnfw-1.9.0-rpm-armv7l.tar.gz \
--asset temp/nnfw-1.9.0-linux-armv7l.tar.gz \
--asset temp/nnfww-1.9.0-linux-x86_64.tar.gz \
--asset temp/nnfw-devel-1.9.0.tar.gz \
--asset temp/nnfw-plugin-devel-1.9.0.tar.gz \
--asset temp/nncc-1.9.0.tar.gz \
--draft \
--commitish release/1.9.0 \
--token ${YOUR_TOKEN} 

rm -rf temp

```

**Comment by hseok-oh** [comment]
>Please resolve TCM warning for runtime

I'll check this

**Comment by lemmaa** [comment]
> - [ ] TCM link : http://npuci.mooo.com/tcm/1.9.0/runtime/tcm-output/result.html (1/179/65) 51%

TCM report for runtime updated. 
Now passed 50% criterion, but need to clear one `no assertion` warning.

**Comment by lemmaa** [comment]
TCM result after applying https://github.com/Samsung/ONE/pull/4080

 - TCM link : http://npuci.mooo.com/tcm/1.9.0/runtime/tcm-output/result.html (0/179/65) 51%
