### ISSUE TITLE
Checklist for 1.9.1  compiler release

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#4181]
### Release Action

- [x] Release Note : https://github.com/Samsung/ONE/pull/4184

### Release Package

- Compiler
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
     - [x] test with public models
     - [x] test with in-hose models

**Comment by llFreetimell** [comment]
```md

# Release Note 1.9.1

## ONE Compiler

### Changes

- `tf2nnpkg` now supports to import TensorFlow model which includes BCQ information.
- Minor change for preserving BCQ information.

```

**Comment by hseok-oh** [comment]
artifact: http://npuci.mooo.com:8080/job/nnfw/job/release_1.9/job/daily-publish-package/17/artifact/

**Comment by llFreetimell** [comment]
## This checklist is outdated since new 1.9.1 compiler release will be handled at #4195.
