### ISSUE TITLE
Checklist for 1.9.1 release (compiler only quick fix release)

### ISSUE THREAD

**Issue by lemmaa** [Samsung/ONE#4195]
### Release Action

- [x] Release Note : https://github.com/Samsung/ONE/blob/master/docs/release/1.9/release-note-1.9.1.md
- [x] Branch out 

### Release Package

- Compiler
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
     - [x] test with public models
     - [x] test with in-house models
     - [x] test with SE TCs (based on #4155 and test materials)

### Release Criteria

- Compiler : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0) 
  - [x] TC line coverage link : 89% http://npuci.mooo.com:8080/job/nnfw/job/release_1.9/job/daily-compiler-coverage/6/
  - [x] TCM link : http://npuci.mooo.com/tcm/1.9.1/compiler/tcm-output/result.html (0/1030/441) 68%
    - TCM result for base commit : http://npuci.mooo.com/tcm/base/compiler/tcm-output-base-ab2a31ca/result.html (10/391/4)
  - [x] Svace link : https://code.sec.samsung.net/ahub/service/analyses/188164
  - [x] Coverity link : https://code.sec.samsung.net/ahub/service/analyses/188165
  - [x] SAM link : [4.35/5.0](https://code.sec.samsung.net/architecturemanager/app/sam/NNAS/nnfw_compiler/20200911_b07033d/overview)
  - [x] License Verification : Nothing changed for License

### Miscellaneous

- [x] nncc preset update if needed
- [x] SSMS
  - Compiler : https://ssms.sec.samsung.net/#/sdl/project/767
    - [x] Svace_security : https://code.sec.samsung.net/ahub/service/analyses/182582

**Comment by seanshpark** [comment]
Compiler more change notes

- Fix invalid input arguments for one-cmds

**Comment by hseok-oh** [comment]
Artifact: http://npuci.mooo.com:8080/job/nnfw/job/release_1.9/job/daily-publish-package/19/artifact/

**Comment by lemmaa** [comment]
Script | TC Scenario | TC Origin | TC Steps | Output (1.9.1)
-- | -- | -- | -- | --
one-pack |   |   |   |  
  | 1.   negative usage with invalid input path | SRBD | $   ./one-pack \     -i ./inception_v2.circle \     -o nnpack | Error:   input model not found
  | 2.   negative usage with  filename without   extension | SRBD | $   touch sample     $ ./one-pack \     -i sample \     -o nnpack | error:   modelfile does not have extension.     Please provide extension so that model2nnpkg.sh can identify what type of   model you use.
  | 3.   negative usage without output folder path | SRBD | $   ./one-pack \     -i ./inception_v3.circle | mkdir:   cannot create  directory   '/inception_v3': Permission denied
one-import-tf |   |   |   |  
  | 1. Positive   usage | HQ | $ one-import tf   \     --input_path ./inception_v3.pb \     --output_path ./inception_v3.circle \     --input_arrays input --input_shapes "1,299,299,3" \     --output_arrays InceptionV3/Predictions/Reshape_1 | On success,   there will be no (error) messages and two files     - inception_v3.circle     -  inception_v3.circle.log             - inception_v3.circle.log   will show internal conversion log of internal commands used.
  |   |   | $   one-optimize --all \     --input_path ./inception_v3.circle    \     --output_path ./inception_v3-opt.circle | On   suceess, there will be no (error) messages and two new files     - inception_v3-opt.circle     - inception_v3-opt.circle.log          - inception_v3-opt.circle.log   will show optimization log.
  |   |   | $   one-pack -i ./inception_v3-opt.circle -o nnpack | On   suceess, there will be no (error) messages and one new folder nnpack
  | 2.   Typical negative usage | HQ | $   one-import tf \     --input_path ./inception_v3.tflite \     --output_path ./inception_v3.circle \     --input_arrays input --input_shapes "1,299,299,3" \     --output_arrays InceptionV3/Predictions/Reshape_1 | ValueError:   Invalid tensors 'input' were found.
  |   |   | $   one-optimize --all \     --input_path ./inception_v3.pb \     --output_path ./inception_v3-opt.circle | ERROR:   Invalid input file './inception_v3.pb'
  | 3. Typical   negative usage with unsupported dynamic tensor | HQ | $ one-import tf   \     --input_path ./while_3.pbtxt \     --output_path ./while_3.circle \     --input_arrays Hole,Hole_2 --input_shapes "1,1:1,1" \     --output_arrays Output | tensorflow.lite.python.convert.ConverterError:   :0: error: loc("While/LoopCond"): body function result type   tensor<1x2xi32> is incompatible with result type tensor<1x1xi32>   at index 0
  | 4.   negative usage with invalid output array | SRBD | $   one-import tf \     --input_path ./inception_v3.pb \     --output_path ./inception_v3.circle \     --input_arrays input --input_shapes "1,299,299,3" \     --output_arrays InceptionV3/Predictions/Reshape_2 | ValueError:   Invalid tensors 'InceptionV3/Predictions/Reshape_2' were found.
  | 5.   negative usage with  invalid input   shape | SRBD | $   one-import tf \     --input_path ./inception_v3.pb \     --output_path ./inception_v3.circle \     --input_arrays input --input_shapes "1,299,299,1" \     --output_arrays InceptionV3/Predictions/Reshape_1 | ValueError:   The shape of tensor 'input' cannot be changed from (None, 299, 299, 3) to [1,   299, 299, 1]. Dimension 3 in both shapes must be equal, but are 3 and 1.   Shapes are [?,299,299,3] and [1,299,299,1].
  |   | SRBD | $   one-import tf \     --input_path ./inception_v3.pb \     --output_path ./inception_v3.circle \     --input_arrays input --input_shapes "1,299,299" \     --output_arrays InceptionV3/Predictions/Reshape_1 | ValueError:   The shape of tensor 'input' cannot be changed from (None, 299, 299, 3) to [1,   299, 299]. Shapes must be equal rank, but are 4 and 3
  |   | SRBD | $   one-import tf \     --input_path ./inception_v3.pb \     --output_path ./inception_v3.circle \     --input_arrays input --input_shapes "0,299,299,3" \     --output_arrays InceptionV3/Predictions/Reshape_1 | tensorflow.lite.python.convert.ConverterError:   <unknown>:0: error:   loc("InceptionV3/InceptionV3/Mixed_7c/concat"): 'tfl.concatenation'   op failed to verify that values and output must have same element type     <unknown>:0: note: loc("InceptionV3/InceptionV3/Mixed_7c/concat"):   see current operation: %0 = "tfl.concatenation"() {axis = 3 : i32,   fused_activation_function = "NONE"} : () ->   tensor<0x8x8x2048xf32>
  |   | SRBD | $   one-import tf \     --input_path ./inception_v3.pb \     --output_path ./inception_v3.circle \     --input_arrays input --input_shapes "None,299,299,3" \     --output_arrays InceptionV3/Predictions/Reshape_1 | ValueError:   invalid literal for int() with base 10: 'None'
  |   | SRBD | $   one-import tf \     --input_path ./inception_v3.pb \     --output_path ./inception_v3.circle \     --input_arrays input,InceptionV3/Predictions/Shape --input_shapes   "1,299,299,3" \     --output_arrays InceptionV3/Predictions/Reshape_1 | ValueError:   --input_shapes and --input_arrays must have the same number of items
  | 6.   negative usage with invalid output path | SRBD | $   one-import tf \     --input_path ./inception_v3.pb \     --output_path . \     --input_arrays input --input_shapes "1,299,299,3" \     --output_arrays InceptionV3/Predictions/Reshape_1 | ERROR:   Failed to write circle '.'
  | 7.   negative usage with invalid input_arrays | SRBD | $   one-import tf  \     --input_path ./inception_v3.pb \     --output_path ./inception_v3.circle \     --input_arrays input2 --input_shapes "1,299,299,3" \     --output_arrays InceptionV3/Predictions/Reshape_1 | ValueError:   Invalid tensors 'input2' were found.
one-quantize |   |   |   |  
  | 1. Positive   case | HQ | $ one-quantize   \     --input_dtype float32 \     --quantized_dtype uint8 \     --input_path ./inception_v3.circle \     --input_data ./inception_v3_test_data.h5 \     --output_path ./inception_v3.quantized.circle | This will   generate inception_v3.quantized.circle, whose tensors are quantized to uint8   values.
  | 2. Negative   case (Unsupported input dtype) | HQ | $ one-quantize   \     --input_dtype float64 \     --quantized_dtype uint8 \     --input_path ./inception_v3.circle \     --input_data ./inception_v3_test_data.h5 \     --output_path ./inception_v3.quantized.circle | ERROR:   Unsupported input type. List of supported input type: float32
  |   |   | $   one-quantize \     --input_dtype float32 \     --quantized_dtype uint16 \     --input_path ./inception_v3.circle \     --input_data ./inception_v3_test_data.h5 \     --output_path ./inception_v3.quantized.circle | ERROR:   Unsupported output type. List of supported output type: uint8
  | 3.   Negative case (Wrong representative dataset) | HQ | $   one-quantize \     --input_dtype float32 \     --quantized_dtype uint8 \     --input_path ./inception_v3.circle \     --input_data ./mobilenet_test_data.h5 \     --output_path ./inception_v3.quantized.circle | ERROR:   Input shape mismatch.
  | 4.   negative usage with invalid output path | SRBD | $   one-quantize \     --input_dtype float32 \     --quantized_dtype uint8 \     --input_path ./inception_v3.circle \     --input_data ./inception_v3_test_data.h5 \     --output_path . | ERROR:   Failed to export '.'
  | 5.   negative usage with invalid input path | SRBD | $   one-quantize \     --input_dtype float32 \     --quantized_dtype uint8 \     --input_path ./while_3.pbtxt \     --input_data ./inception_v3_test_data.h5 \     --output_path ./inception_v3.quantized.circle | ERROR:   Invalid input file './while_3.pbtxt'
  |   |   | $   one-quantize \     --input_dtype float32 \     --quantized_dtype uint8 \     --input_path ./inception_v2.circle \     --input_data ./inception_v3_test_data.h5 \     --output_path ./inception_v3.quantized.circle | Error:   input model not found
  | 6.   negative usage with invalid input_data | SRBD | $   one-quantize \     --input_dtype float32 \     --quantized_dtype uint8 \     --input_path ./inception_v3.circle \     --input_data ./inception_v3.circle \     --output_path ./inception_v3.quantized.circle | nncc-1.8.0/bin/one-quantize:   line 160: 19445 Aborted                   (core dumped)
  | 7.   negative usage with invalid mode | SRBD | $   one-quantize \     --input_dtype float32 \     --quantized_dtype uint8 \     --input_path ./inception_v3.circle \     --input_data ./inception_v3_test_data.h5 \     --mode average \     --output_path ./inception_v3.quantized.circle | ERROR:   Unsupported mode
  | 8.   negative usage with invalid max_percentile | SRBD | $   one-quantize \     --input_dtype float32 \     --quantized_dtype uint8 \     --input_path ./inception_v3.circle \     --input_data ./inception_v3_test_data.h5 \     --max_percentile 101 \     --output_path ./inception_v3.quantized.circle | ERROR:   Percentile must be ranged from 0 to 100
  |   |   | $   one-quantize \     --input_dtype float32 \     --quantized_dtype uint8 \     --input_path ./inception_v3.circle \     --input_data ./inception_v3_test_data.h5 \     --max_percentile -1 \     --output_path ./inception_v3.quantized.circle | ERROR:   Percentile must be ranged from 0 to 100
  | 9.   negative usage with invalid min_percentile | SRBD | $   one-quantize \     --input_dtype float32 \     --quantized_dtype uint8 \     --input_path ./inception_v3.circle \     --input_data ./inception_v3_test_data.h5 \     --min_percentile 101 \     --output_path ./inception_v3.quantized.circle | ERROR:   Percentile must be ranged from 0 to 100
  |   |   | $   one-quantize \     --input_dtype float32 \     --quantized_dtype uint8 \     --input_path ./inception_v3.circle \     --input_data ./inception_v3_test_data.h5 \     --min_percentile -1 \     --output_path ./inception_v3.quantized.circle | ERROR:   Percentile must be ranged from 0 to 100
  | 10.   negative usage with invalid granularity | SRBD | $   one-quantize \     --input_dtype float32 \     --quantized_dtype uint8 \     --input_path ./inception_v3.circle \     --input_data ./inception_v3_test_data.h5 \     --granularity layered \     --output_path ./inception_v3.quantized.circle | ERROR:   Unsupported granularity. List of supported granularity: layer, channel
one-import-bcq |   |   |   |  
  | 1. Positive   case | HQ | $   one-import-bcq \     --input_path ./bcq.pb \     --output_path ./bcq.circle \     --input_arrays Placeholder \     --output_arrays MatMul | bcq.cirle file   is generated
  | 2.   Negative case (Invalid Input) | HQ | $   one-import-bcq \     --input_path ./bcq.pb \     --output_path ./bcq.circle \     --input_arrays Placeholder_null \     --output_arrays MatMul | ValueError:   Invalid tensors 'Placeholder_null' were found.
  | 3. Negative   case (Invalid Output) | HQ | $   one-import-bcq \     --input_path ./bcq.pb \     --output_path ./bcq.circle \     --input_arrays Placeholder \     --output_arrays MatMul_null | ValueError:   Invalid tensors 'MatMul_null' were found.
  | 4. Negative   case (Invalid Input Path) | HQ | $   one-import-bcq \     --input_path ./bcq_null.pb \     --output_path ./bcq.circle \     --input_arrays Placeholder \     --output_arrays MatMul | Error: input   model not found
  | 5. negative   usage with invalid input | SRBD | $   ./one-import-bcq \     --input_path ./while_3.pbtxt \     --output_path ./bcq.circle \     --input_arrays Placeholder \     --output_arrays MatMul | google.protobuf.message.DecodeError:   Error parsing message
  | 6.   Invalid usage with invalid output_path | SRBD | $   ./one-import-bcq \     --input_path ./bcq.pb \     --output_path . \     --input_arrays Placeholder \     --output_arrays MatMul | ERROR:   Failed to write circle '.'
  | 7.   negative usage with  invalid input   shape | SRBD | $ one-import   bcq \     --input_path ./bcq.pb \     --output_path ./bcq.circle \     --input_arrays Placeholder --input_shapes "1,32,32" \     --output_arrays MatMul | ValueError: The   shape of tensor 'Placeholder' cannot be changed from (32, 32) to [1, 32, 32].   Shapes must be equal rank, but are 2 and 3.
  |   |   | $   one-import bcq \     --input_path ./bcq.pb \     --output_path ./bcq.circle \     --input_arrays Placeholder --input_shapes "30,30" \     --output_arrays MatMul | ValueError:   The shape of tensor 'Placeholder' cannot be changed from (32, 32) to [30,   30]. Dimension 0 in both shapes must be equal, but are 32 and 30. Shapes are   [32,32] and [30,30].
  |   |   | $   one-import bcq \     --input_path ./bcq.pb \     --output_path ./bcq.circle \     --input_arrays Placeholder --input_shapes "32,O" \     --output_arrays MatMul | ValueError:   invalid literal for int() with base 10: 'O'
  |   |   | $   one-import bcq \     --input_path ./bcq.pb \     --output_path ./bcq.circle \     --input_arrays Placeholder --input_shapes "32,32:1" \     --output_arrays MatMul | ValueError:   --input_shapes and --input_arrays must have the same number of items
one-optimize |   |   |   |  
  | 1. Invalid   usage with invalid input path | SRBD | $ one-optimize   --all \     --input_path ./inception_v3.circletxt    \     --output_path ./inception_v3-opt.circle | Error: input   model not found
  | 2.   negative usage without output folder path | SRBD | $   one-optimize --all \     --input_path  ./inception_v3.circle | ERROR:   Failed to export ''

**Comment by mhs4670go** [comment]
```bash
#!/bin/bash

mkdir temp && pushd temp

wget http://npuci.mooo.com:8080/job/nnfw/job/release_1.9/job/daily-publish-package/lastSuccessfulBuild/artifact/nncc-1.9.1.tar.gz

popd

./git_release.sh --tag 1.9.1 \
  --release_note ../../docs/release/1.9/release-note-1.9.1.md \
  --asset temp/nncc-1.9.1.tar.gz \
  --draft \
  --commitish release/1.9.0 \
  --token ${YOUR_TOKEN}                            

rm -rf temp
```
