### ISSUE TITLE
[Compiler][luci] Introduce new optimization pass, FoldDequantize

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE#4373]
Parent Issue : #4353

---

### What to do

Remove `Dequantize` operation when following pattern is appeared.

#### Pattern 1
- `Gather` is input of `Dequantize`
- Quantized constant value is input of `Gather`
![Dequant](https://user-images.githubusercontent.com/24720192/93846447-016c4200-fcdf-11ea-9ed2-6276d6122611.png)

#### Pattern 2
- Input of `Dequqntize` is constant value

### How it works

`Gather` operation do not change the value itself. So we can apply `Dequantize` operation in advance and thus we can substitute input of `Gather` to dequantized constant value.

### Todo
- [x] Support `Dequantize` operation in Compiler FE (Only some of them are mandatory) #4382
- [x] Introduce `FoldDequantize` pass in `luci/pass` #4404
- [x] ~~Reorder optimizations in circle optimizer #4423~~ Not needed
- [x] Support `S8` in `CircleTensorExporter` #4453
- [x] Introduce `FoldDequantize` pass in `circle2circle` #4448

### Draft

#4374

**Comment by llFreetimell** [comment]
Done!
