### ISSUE TITLE
[Template] Release checklist 

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#4552]
### Release Action

- [x] Release Note
- [x] Branch out 
  - [x] `master` branch version up 
    - [x] tizen spec file
    - [x] nnfw_version.h
    - [x] document version in `/docs/conf.py`
    - [x] onert aar version

### Release Package

- Runtime 
  - [x] arm64-android (tar.gz) for Android 10
  - [x] arm64-android (aar) for Android 10
  - [x] arm-tizen (rpm) for Tizen 6.0 M2
  - [x] arm-linux (tar.gz)  for Ubuntu 18.04
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
  - [x] nnfw-devel
  - [x] nnfw-plugin-devel
- Compiler
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
     - [x] test with public models
     - [x] test with in-hose models

### Release Criteria

- Runtime : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0)
  - [x] TC line coverage link : 
  - [x] TCM link : 
    - TCM result for base commit :
  - [x] Svace link : 
  - [x] Coverity link : 
  - [x] SAM link : 
  - [x] License Verification
- Compiler : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0) 
  - [x] TC line coverage link : 
  - [x] TCM link : 
  - [x] Svace link : 
  - [x] Coverity link : 
  - [x] SAM link : 
  - [x] License Verification : 

### Miscellaneous

- [ ] nncc preset update if needed
- [ ] SSMS
  - Runtime : 
    - [ ] Svace_security : 
  - Compiler : 
    - [ ] Svace_security :

**Comment by chunseoklee** [comment]
duplicated
