### ISSUE TITLE
Checklist for 1.10.0 release

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#4554]
### Release Action

- [x] Release Note : https://github.com/Samsung/ONE/pull/4643
- [x] Branch out : https://github.com/Samsung/ONE/tree/release/1.10.0
  - [x] `master` branch version up  (#4635)
    - [x] tizen spec file
    - [x] nnfw_version.h
    - [x] document version in `/docs/conf.py`
    - [x] onert aar version

### Release Package

- Runtime 
  - [x] arm64-android (tar.gz) for Android 10
  - [x] arm64-android (aar) for Android 10
  - [x] arm-tizen (rpm) for Tizen 6.0 M2
  - [x] arm-linux (tar.gz)  for Ubuntu 18.04
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
  - [x] nnfw-devel
  - [x] nnfw-plugin-devel
- Compiler
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
     - [x] test with one-cmd test scripts
     - [x] test with public models
     - [x] test with in-house models

### Release Criteria

- Runtime : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0)
  - [x] TC line coverage link : 83% http://npuci.mooo.com:8080/job/nnfw/job/release_1.10/job/daily-arm-runtime-coverage/2/
  - [x] TCM link :  http://npuci.mooo.com/tcm/1.10.0/runtime/tcm-output/result.html (0/270/111) 50.9%
    - TCM result for base commit : http://npuci.mooo.com/tcm/base/runtime/tcm-output-base-ab1a04a7/result.html (0/56/2)
  - [x] Svace link
    + On master branch : https://code.sec.samsung.net/ahub/service/analyses/217944 ( 0 critical, 0 major)
    + On release branch : https://code.sec.samsung.net/ahub/service/analyses/218411
  - [x] Coverity link : 
    + On master branch : https://code.sec.samsung.net/ahub/service/analyses/218139 ( 0 critical, 0 major)
    + On release branch : https://code.sec.samsung.net/ahub/service/analyses/218412
  - [x] SAM link : [4.18/5.0](https://code.sec.samsung.net/architecturemanager/app/sam/NNAS/nnfw_runtime/20201020_bef7322/overview)
  - [x] License Verification : https://github.sec.samsung.net/STAR/nnfw/issues/11854
- Compiler : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0) 
  - [x] TC line coverage link : 89% http://npuci.mooo.com:8080/job/nnfw/job/release_1.10/job/daily-compiler-coverage/1/
  - [x] TCM link : http://npuci.mooo.com/tcm/1.10.0/compiler/tcm-output/result.html (0/1189/517) 64.2%
    - TCM result for base commit : http://npuci.mooo.com/tcm/base/compiler/tcm-output-base-ab2a31ca/result.html (10/391/4)
  - [x] Svace link : 
    + On master branch: https://code.sec.samsung.net/ahub/service/analyses/213223
    + On release branch: https://code.sec.samsung.net/ahub/service/analyses/219149
  - [x] Coverity link : https://code.sec.samsung.net/ahub/service/analyses/219150   
  - [x] SAM link : [4.24/5.0](https://code.sec.samsung.net/architecturemanager/app/sam/NNAS/nnfw_compiler/20201020_bef7322/overview)
  - [x] License Verification : https://github.sec.samsung.net/STAR/nnfw/issues/11854

### Miscellaneous

- [x] nncc preset update if needed
- [x] SSMS
  - Runtime : 
    - [x] Svace_security : 
      + On master branch: https://code.sec.samsung.net/ahub/service/analyses/217609
      + On release branch: https://code.sec.samsung.net/ahub/service/analyses/219146
  - Compiler : 
    - [x] Svace_security : https://code.sec.samsung.net/ahub/service/analyses/219199

**Comment by seanshpark** [comment]
WIP

### Release note for Compiler frontend

Compiler supports more operations
- Dequantize,  UnidirectionalSequenceLSTM

Changes
- New `--fold_dequantize` option in `one-optimize`
- New `--fuse_add_with_tconv` option in `one-optimize` (WIP)
- Support `int16` quantization in `one-quantize`
- Test scripts are added for basic testing of one-cmd command line tools
- Bug fixes for one-cmd command line tools

**Comment by chunseoklee** [comment]
@Samsung/nnfw please comment Release Note Items.

**Comment by wateret** [comment]
## Release note for Runtime WG1

Nothing. 💦

**Comment by hseok-oh** [comment]
Nothing to comment

**Comment by hseok-oh** [comment]
Package files (except aar)
https://art.sec.samsung.net/artifactory/rs7-runtimentools_generic/ONE/package/release/1.10/

**Comment by lemmaa** [comment]
1 No Assertion TC occurred for each Runtime and Compiler.

Test | Test Case | Checker | File | Line
-- | -- | -- | -- | --
NN Runtime | GenModelTest.OneOp_Concat_ShareSubTensor | GTEST.NO_ASSERTION | /home/sjlee/star/one-1.10.0/tests/nnfw_api/src/one_op_tests/Concat.cc | 21


Test | Test Case | Checker | File | Line
-- | -- | -- | -- | --
NN Compiler | ResizeBilinearTest.HalfPixelCenterFloatTest | GTEST.NO_ASSERTION | /home/sjlee/star/one-1.10.0/compiler/luci-interpreter/src/kernels/ResizeBilinear.test.cpp | 108

**Comment by seanshpark** [comment]
`GTEST.NO_ASSERTION` for `ResizeBilinearTest.HalfPixelCenterFloatTest` --> #4674 , #4675

**Comment by chunseoklee** [comment]
> `GTEST.NO_ASSERTION` for `ResizeBilinearTest.HalfPixelCenterFloatTest` --> #4674 , #4675

patches are merged now. need to wait for final binary.

**Comment by hseok-oh** [comment]
Updated packages are uploaded

**Comment by chunseoklee** [comment]
somebody to check tcm ? I have failed to run

**Comment by lemmaa** [comment]
The TCM result was updated. Thanks!

**Comment by lemmaa** [comment]
@chunseoklee , @hseok-oh , @wateret , However, is there really nothing to mention about runtime changes in this release?

**Comment by glistening** [comment]
> @chunseoklee , @hseok-oh , @wateret , However, is there really nothing to mention about runtime changes in this release?

Here are some:

### Runtime backend operation support
  - ACL-CL backend: OneHot
  - CPU backend: FullyConnected for Float32 16x1 Block Sparsity

### Optimization
  - Speed up for ReduceSum, StrideSlice in CPU backend

**Comment by hseok-oh** [comment]
Updated packages are uploaded 

cc/ @dayo09
