### ISSUE TITLE
[onert] Support fp16 mode on acl

### ISSUE THREAD

**Issue by YongseopKim** [Samsung/ONE#48]
current armnn supports fp16 mode (v19_11)
- Iv3_2018 (fp32 -> fp16)
    - mem: 343388 kB -> 210848 kB
    - perf: 682.39 ms -> 426.48 ms

Tasks
- [x] Introduce Half lib from opensource `half_float`: https://github.com/Samsung/ONE/pull/44
- [x] Option fp16_enable: https://github.com/Samsung/ONE/pull/45
- [x] Introduce Converting Ops: https://github.com/Samsung/ONE/pull/47
  - [x] `ConvertFp32ToFp16`
  - [x] `ConvertFp16ToFp32`
- [x] Fix IConstantInitializer for type float16 #184 
- [x] Fix ACL_CL
  - [x] ShapeFixer #171 
  - [x] acl_common/Convert.cc asDataType() #183 
  - [x] Append KernelGenerator's the ops #170 
- [x] Introduce Fp32ToFp16Converter #200
- [x] Run Fp32ToFp16Converter by Option `FP16_ENABLE` #200
