### ISSUE TITLE
[circle-quantizer] Quantize FastStyleTransfer model

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#4874]
Let's quantize FastStyleTransfer (FST) model.
(Model repo: https://github.com/lengstrom/fast-style-transfer)

A major issue on quantizing FST is instance normalization. In FST, instance normalization is implemented as below.

![instnorm_pattern](https://user-images.githubusercontent.com/5449554/97844445-61b6c080-1d2e-11eb-8a5f-facd74307ce6.png)

Current `FuseInstanceNormPass` does not capture this pattern, so we need to update the pass to support this new pattern.

**ToDo**
- [x] Update `FuseInstanceNormPass` to support the new pattern
- [x] Support InstanceNorm Op in luci-interpreter #4902
- [x] Support InstanceNorm quantization in circle-quantizer

**Comment by jinevening** [comment]
Quantization failed as luci-interpreter fails to run Conv2D.

This is because a buffer for im2col is too large (about 6.7 GB), thus interpreter fails to allocate the buffer (std::bad_alloc is thrown)).

I've made Conv2D fall back to the reference kernel that does not use im2col (#4933) if memory allocation fails.

**Comment by jinevening** [comment]
Now FST can be quantized with fused IN. I close this PR.
