### ISSUE TITLE
Checklist for Release 1.11.0

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#4977]
### Release Action

- [x] Release Note : https://github.com/Samsung/ONE/pull/4922
- [x] Branch out 
  - [x] `master` branch version up : https://github.com/Samsung/ONE/pull/4994
    - [x] tizen spec file
    - [x] nnfw_version.h
    - [x] document version in `/docs/conf.py`
    - [x] onert aar version

### Release Package

- Runtime 
  - [x] arm64-android (tar.gz) for Android 10
  - [x] arm64-android (aar) for Android 10
  - [x] arm-tizen (rpm) for Tizen 6.0 M2
  - [x] arm-linux (tar.gz)  for Ubuntu 18.04
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
  - [x] nnfw-devel
  - [x] nnfw-plugin-devel
- Compiler
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
     - [x] test with public models
     - [x] test with in-hose models

### Release Criteria

- Runtime : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0)
  - [x] TC line coverage link : 85% http://npuci.mooo.com:8080/job/nnfw/job/release_1.11/job/daily-arm-runtime-coverage/3/
  - [x] TCM link : http://npuci.mooo.com/tcm/1.11.0/runtime/tcm-output/result.html (0/353/166) 55.2%
    - TCM result for base commit : http://npuci.mooo.com/tcm/base/runtime/tcm-output-base-ab1a04a7/result.html (0/56/2)
  - [x] Svace link : 0 critical, 0 major https://code.sec.samsung.net/ahub/service/analyses/247943
  - [x] Coverity link : 0 critical, 0 major https://code.sec.samsung.net/ahub/service/analyses/247946
  - [x] SAM link : [4.17/5.0](https://code.sec.samsung.net/architecturemanager/app/sam/NNAS/nnfw_runtime/20201112_23f78ee/overview)
  - [x] License Verification : http://10.40.203.158/p/projects/c_20_one_release_1110_33849
- Compiler : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0) 
  - [x] TC line coverage link : 89% http://npuci.mooo.com:8080/job/nnfw/job/release_1.11/job/daily-compiler-coverage/1/
  - [x] TCM link : http://npuci.mooo.com/tcm/1.11.0/compiler/tcm-output/result.html (0/1236/534) 62.7%
    - TCM result for base commit : http://npuci.mooo.com/tcm/base/compiler/tcm-output-base-ab2a31ca/result.html (10/391/4)
  - [x] Svace link : 0 critical, 0 major https://code.sec.samsung.net/ahub/service/analyses/248024
  - [x] Coverity link : 0 critical, 0 major https://code.sec.samsung.net/ahub/service/analyses/248152
  - [x] SAM link : [4.23/5.0](https://code.sec.samsung.net/architecturemanager/app/sam/NNAS/nnfw_compiler/20201112_23f78ee/overview)
  - [x] License Verification : http://10.40.203.158/p/projects/c_20_one_release_1110_33849

### Miscellaneous

- [x] nncc preset update if needed
- [x] SSMS
  - Runtime : 
    - [x] Svace_security :  0 critical, 0 major https://code.sec.samsung.net/ahub/service/analyses/247947
  - Compiler : 
    - [x] Svace_security : 0 critical, 0 major https://code.sec.samsung.net/ahub/service/analyses/248027

**Comment by seanshpark** [comment]
@jinevening , we need to fix https://github.com/Samsung/ONE/blob/master/compiler/one-cmds/tests/prepare_test_materials.sh#L55 

@chunseoklee , could you please wait for this fix ?

**Comment by seanshpark** [comment]
@chunseoklee , I think we need #4984 to land for 1.11.0

**Comment by hyunsik-yoon** [comment]
Could you share the dates (freeze date, release date, etc) for 1.11.0?

**Comment by lemmaa** [comment]
> Could you share the dates (freeze date, release date, etc) for 1.11.0?

As of now, we plan to release a new version around the 15th of every month. Freeze is one week before release. 
Therefore, 1.11.0 is expected to be released on Nov. 16th, and freeze was last Monday, Nov. 9th. This release is going a bit loose. :)

**Comment by hseok-oh** [comment]
Packages are uploaded https://art.sec.samsung.net/artifactory/rs7-runtimentools_generic/ONE/package/release/1.11.0/

**Comment by chunseoklee** [comment]
License(Protex) result on release/1.11.0 for now : 

```
(INFO) Files pending identification: 56
(INFO) Files scanned successfully with no discoveries: 3098
(INFO) Logged messages by severity: 4 info
```

**Comment by hseok-oh** [comment]
Please check compiler's coverity defects: https://code.sec.samsung.net/ahub/service/analyses/248026

**Comment by llFreetimell** [comment]
@hseok-oh When I checked, the number of defects was 0. I will check again.

**Comment by mhs4670go** [comment]
@hseok-oh Solved:)

**Comment by lemmaa** [comment]
@wateret , PTAL

Test | Test Case | Checker | File | Line
-- | -- | -- | -- | --
NN Runtime | GenModelTest.neg_OneOp_DepthwiseConv2D_InvalidPaddingType | GTEST.NO_ASSERTION | /home/sjlee/star/one-1.11.0/tests/nnfw_api/src/one_op_tests/DepthwiseConv2D.cc | 268

**Comment by chunseoklee** [comment]
All the license issues resolved.

**Comment by wateret** [comment]
> @wateret , PTAL
> 
> Test	Test Case	Checker	File	Line
> NN Runtime	GenModelTest.neg_OneOp_DepthwiseConv2D_InvalidPaddingType	GTEST.NO_ASSERTION	/home/sjlee/star/one-1.11.0/tests/nnfw_api/src/one_op_tests/DepthwiseConv2D.cc	268

#5027 will resolve it.

**Comment by hseok-oh** [comment]
@chunseoklee @seanshpark Updated packages are uploaded
https://art.sec.samsung.net/artifactory/rs7-runtimentools_generic/ONE/package/release/1.11.0/

**Comment by hseok-oh** [comment]
Not uploaded yet...

**Comment by lemmaa** [comment]
> #5027 will resolve it.

 TCM result updated. Done!

**Comment by hseok-oh** [comment]
Updated packages are uploaded
https://art.sec.samsung.net/artifactory/rs7-runtimentools_generic/ONE/package/release/1.11.0/

**Comment by seanshpark** [comment]
> Updated packages are uploaded

compiler testged with new upload and is OK

**Comment by cgbahk** [comment]
SAM updated

**Comment by hseok-oh** [comment]
Package will be updated: revert ubuntu version update (18.04 -> 16.04) for x86-64 package

**Comment by hseok-oh** [comment]
Updated packages (11/13): http://npuci.mooo.com:8080/job/nnfw_internal/job/release_1.11/job/daily-publish-package/

**Comment by chunseoklee** [comment]
done
