### ISSUE TITLE
Checklist for Release 1.11.1(runtime hotfix)

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#5185]
### Release Action

- [x] Release Note : https://github.com/Samsung/ONE/pull/5190
- [x] `1.11.0` branch version up : https://github.com/Samsung/ONE/pull/5193
    - [x] tizen spec file
    - [x] nnfw_version.h
    - [x] document version in `/docs/conf.py`
    - [x] onert aar version

### Release Package

- Runtime 
  - [x] arm64-android (tar.gz) for Android 10
  - [x] arm64-android (aar) for Android 10
  - [x] arm-tizen (rpm) for Tizen 6.0 M2
  - [x] arm-linux (tar.gz)  for Ubuntu 18.04
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
  - [x] nnfw-devel
  - [x] nnfw-plugin-devel

### Release Criteria

- Runtime : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0)
  - [x] TC line coverage link : http://npuci.mooo.com:8080/job/nnfw/job/release_1.11/job/daily-arm-runtime-coverage/5/ (85%)
  - [x] TCM link : http://npuci.mooo.com/tcm/1.11.1/runtime/tcm-output/result.html (0/353/166) 55.2%
    - TCM result for base commit : http://npuci.mooo.com/tcm/base/runtime/tcm-output-base-ab1a04a7/result.html (0/56/2)
  - [x] Svace link : https://analysishub.sec.samsung.net/service/analyses/259393
  - [x] Coverity link : https://analysishub.sec.samsung.net/service/analyses/259394 
  - [x] SAM link : [4.11/5.0](https://code.sec.samsung.net/architecturemanager/app/sam/NNAS/nnfw_runtime/20201130_e8c0122/overview)
  - [x] License Verification : not changed since Release 1.11.0

### Miscellaneous

- [x] SSMS
  - Runtime : 
    - [x] Svace_security : https://analysishub.sec.samsung.net/service/analyses/260736

**Comment by chunseoklee** [comment]
Fix PR : https://github.com/Samsung/ONE/pull/5175

**Comment by chunseoklee** [comment]
## ONE Runtime                                                                                                    
 
### Hot Fixes
 
 - Fix segfault due to the wrong BCQGather DynamicShapeInferer's behavior

**Comment by hseok-oh** [comment]
packages: https://art.sec.samsung.net/artifactory/rs7-runtimentools_generic/ONE/package/release/1.11.1/

**Comment by dayo09** [comment]
Q1) Should we release one-ext 1.1.1 as well? 
Q2) If yes, same binary and only version up? Or with [the exception patch](https://github.sec.samsung.net/STAR/nnfw/pull/11928)?

**Comment by chunseoklee** [comment]
> Q1) Should we release one-ext 1.1.1 as well?
> Q2) If yes, same binary and only version up? Or with [the exception patch](https://github.sec.samsung.net/STAR/nnfw/pull/11928)?

Q1) Yes
Q2) with PR

**Comment by chunseoklee** [comment]
tcm result on 24b64bc10db3787 : (353/166)
[tcm-output.tar.gz](https://github.com/Samsung/ONE/files/5614126/tcm-output.tar.gz)

**Comment by cgbahk** [comment]
SAM updated
