### ISSUE TITLE
Checklist for ONE 1.12.0 Release

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#5304]
### Release Action

- [x] Release Note : #5315
- [x] Branch out : https://github.com/Samsung/ONE/commits/release/1.12.0
  - [x] `master` branch version up : https://github.com/Samsung/ONE/pull/5314 
    - [x] tizen spec file
    - [x] nnfw_version.h
    - [x] document version in `/docs/conf.py`
    - [x] onert aar version

### Release Package

- Runtime  : http://npuci.mooo.com:8080/job/nnfw/job/release_1.12/job/daily-publish-package/3/
  - [x] arm64-android (tar.gz) for Android 10
  - [x] arm64-android (aar) for Android 10
  - [x] arm-tizen (rpm) for Tizen 6.0 M2
  - [x] arm-linux (tar.gz)  for Ubuntu 18.04
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
  - [x] nnfw-devel
  - [x] nnfw-plugin-devel
- Compiler
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
     - [x] test with public models
     - [x] test with in-house models

### Release Criteria

- Runtime : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0)
  - [x] TC line coverage link : 84%(http://npuci.mooo.com:8080/job/nnfw/job/release_1.12/job/daily-arm-runtime-coverage/1/)
  - [x] TCM link : http://npuci.mooo.com/tcm/1.12.0/runtime/tcm-output/result.html (0/379/180) 55.1%
    - TCM result for base commit : http://npuci.mooo.com/tcm/base/runtime/tcm-output-base-ab1a04a7/result.html (0/56/2)
  - [x] Svace link : https://analysishub.sec.samsung.net/service/analyses/271748
  - [x] Coverity link : https://analysishub.sec.samsung.net/service/analyses/271702
  - [x] SAM link : https://code.sec.samsung.net/architecturemanager/app/sam/NNAS/nnfw_runtime/20201209_6b1255c/overview (4.09/5.0)
  - [x] License Verification
- Compiler : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0) 
  - [x] TC line coverage link : 89% (http://npuci.mooo.com:8080/job/nnfw/job/release_1.12/job/daily-compiler-coverage/1/)
  - [x] TCM link : http://npuci.mooo.com/tcm/1.12.0/compiler/tcm-output/result.html (0/1251/536) 61.8%
    - TCM result for base commit : http://npuci.mooo.com/tcm/base/compiler/tcm-output-base-ab2a31ca/result.html (10/391/4)
  - [x] Svace link : https://analysishub.sec.samsung.net/service/analyses/271654
  - [x] Coverity link : https://analysishub.sec.samsung.net/service/analyses/271666
  - [x] SAM link : https://code.sec.samsung.net/architecturemanager/app/sam/NNAS/nnfw_compiler/20201209_6b1255c/overview (4.23/5.0)
  - [x] License Verification : 

### Miscellaneous

- [x] nncc preset update if needed
- [x] SSMS
  - Runtime : 
    - [x] Svace_security : https://analysishub.sec.samsung.net/service/analyses/271749
  - Compiler : 
    - [x] Svace_security : https://analysishub.sec.samsung.net/service/analyses/271729

**Comment by chunseoklee** [comment]
@nnfw Please write down feature list on the comment

**Comment by hseok-oh** [comment]
- CPU backend
  - float: DepthToSpace, LeakyRelu
  - uint8: DepthToSpace
  - int8: Concat, DepthToSpace

**Comment by seanshpark** [comment]
Compiler frontend
- Add optimization pass: ReplaceMulAddWithDepthwiseConvPass, SubstitutePackToReshape, RemoveRedundantTranspose, ShuffleWeightTo16x1Float32Pass
- Add quantization for InstanceNorm.
- Fix bug of one-import-bcq --v1, --v2 arguments.
- Fix FuseBCQPass to work with inter-subgraphs in the model file and minor BCQ related optimizations.

**Comment by chunseoklee** [comment]
- nnpkg defines configuration file, which allows users to set configuration variable in Config.lst

**Comment by hseok-oh** [comment]
Package is uploaded:
https://art.sec.samsung.net/artifactory/rs7-runtimentools_generic/ONE/package/release/1.12.0/

cc/ @dayo09

**Comment by lemmaa** [comment]
TCM result updated.

Test | Test Case | Checker | File | Line
-- | -- | -- | -- | --
NN Runtime | ValidationTestTwoSessionsCreated.two_sessions_run_simple_model | GTEST.NO_ASSERTION | /home/sjlee/star/one-1.12.0/tests/nnfw_api/src/ValidationTestMultipleSessions.cc | 44

**Comment by hseok-oh** [comment]
TCM no assertion fix: #5324

**Comment by cgbahk** [comment]
SAM updated

---

Note for runtime score :)
> 4.09/5.0

**Comment by lemmaa** [comment]
> TCM no assertion fix: #5324

TCM result updated. All done. Thank you!

**Comment by chunseoklee** [comment]
report from @mhs4670go : need a patch for NN Compiler (link: )

**Comment by chunseoklee** [comment]
@Samsung/nncc Please check the latest nncc package works ok : https://github.com/Samsung/ONE/releases/download/untagged-6b18211ef790bfcd54f8/nncc-1.12.0.tar.gz

**Comment by seanshpark** [comment]
> Please check the latest nncc package works ok

Test is OK.

**Comment by chunseoklee** [comment]
Released
