### ISSUE TITLE
Checklist for Release 1.12.1(compiler hotfix)

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#5376]
### Release Action

- [x] Release Note : #5382 

### Release Package

- Compiler
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
     - [x] test with public models
     - [x] test with in-house models

### Release Criteria

- Compiler : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0) 
  - [x] TC line coverage link : 89% http://npuci.mooo.com:8080/job/nnfw/job/release_1.12/job/daily-compiler-coverage/4/
  - [x] TCM link : http://npuci.mooo.com/tcm/1.12.1/compiler/tcm-output/result.html (0/1251/536) 61.8%
    - TCM result for base commit : http://npuci.mooo.com/tcm/base/compiler/tcm-output-base-ab2a31ca/result.html 
  - [x] Svace link : https://analysishub.sec.samsung.net/service/analyses/281575
  - [x] Coverity link : https://analysishub.sec.samsung.net/service/analyses/281577
  - [x] SAM link : [4.23/5.0](https://code.sec.samsung.net/architecturemanager/app/sam/NNAS/nnfw_compiler/20201215_2f10336/overview)
  - [x] License Verification : no change

### Miscellaneous

- [x] SSMS
  - Compiler : 
    - [x] Svace_security : https://analysishub.sec.samsung.net/service/analyses/281576

**Comment by hseok-oh** [comment]
Generated package (compiler only): https://art.sec.samsung.net/artifactory/rs7-runtimentools_generic/ONE/package/release/1.12.1/
