### ISSUE TITLE
[Compiler][luci] Refactoring shape/dtype inference

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE#5501]
Originated from #4372,#4796
Draft PR : #5502, #5756

---

## What?

- Supporting dynamic shape inference with refactoring shape/dtype inference in `luci/Service` like following diagram.
```
   circle file     ---- import --->   luci/IR   ---- export --->   circle file
====================================================================================

   [1, 2, 3, 1]                                                    [1, 2, 3, 1]
     (shape)                        [?, 2, 3, 1]                      (shape)
                        ----->      (TensorShape)    ----->
  [-1, 2, 3, 1]                                                    [-1, 2, 3, 1]
(shape_signature)                                                (shape_signature)

====================================================================================

   [1, 2, 3, 1]                                                    [1, 2, 3, 1]
     (shape)                        [1, 2, 3, 1]                      (shape)
                        ----->      (TensorShape)    ----->
       []                                                                []
(shape_signature)                                                (shape_signature)
```

- Keypoints
  -  type inference : refactoring structure
  - shape inference : refactoring structure + logic upgrade
  - shape_signature inference : Deprecation
  - shape_signature attribute : Deprecation

## Why?

- There are some models which include dynamic shape but current `luci` cannot handle it.
- Current shape/type inference rule file is big so it would be better to implement in each operation file.

## How?

As following codes, `CircleNode` is using `TensorShape`

https://github.com/Samsung/ONE/blob/030371d447c4e222fe9e782f93fc1055344e79ee/compiler/luci/lang/include/luci/IR/CircleNodeDecl.h#L38-L40

and `TensorShape` has `loco::Dimension` which has following methods.

- `unset(void)` : Represent unknown dimension. It matched with `?` in above diagram.
https://github.com/Samsung/ONE/blob/4e4f9ffcc5f149d22123d26a38aed9b31f9d79c4/compiler/loco/include/loco/IR/Dimension.h#L59-L63

- `known(void)` : Judge whether the dimension is known or unknown.
https://github.com/Samsung/ONE/blob/4e4f9ffcc5f149d22123d26a38aed9b31f9d79c4/compiler/loco/include/loco/IR/Dimension.h#L47

By using these methods, we can express both static and dynamic shape.
All we need to do is upgrading shape inference logic which enables dynamic shape inference.
Implementation of shape inference(upgraded version) will be written by each operation together with type inference.

---

### Background History

- `shape_signature` is introduced in TFLite to represent dynamic shape.
- To support `shape_signature` and dynamic shape inference using it, #4372 was done.
- However, during refactoring `luci/Service` in #4796, some opinions were made. (Started from [here](https://github.com/Samsung/ONE/issues/4796#issuecomment-737171151))
  - The only difference between `shape` and `shape_signature` is the value for unknown dimension, 1 or -1.
  - Inference algorithm for `shape` and `shape_signature` is actually same. As a result, it can cause code duplication.
  - Additional redundancy for keeping consistency between `shape` and `shape_signature` can be occurred.
  - Writing a code in `luci` would be tough.
- As a result, the overall direction is changed and re-opening a new issue looked better.

**Comment by llFreetimell** [comment]
## Todo

- [ ] Remove loco dependency such as `loco::shape_get`, `loco::dtype_get`
- [ ] Update not to use `value()` function without `known()` checking
- [ ] Deprecate shape_signature inference
- [ ] Deprecate shape_signature attribute
- [ ] Remove shape_signature attribute
- [ ] Introduce new shape inference pass
- [ ] Enable new shape/type inference pass and disable deprecated legacy pass
- Implementation of shape/type inference algorithm for each operation 
  - Will be handled by another issue

**Comment by llFreetimell** [comment]
Done! Now it's time to implement new inference algorithms!

**Comment by llFreetimell** [comment]
Finally done.... close!
