### ISSUE TITLE
[Compiler][luci] Introduce RemoveNoEffectStridedSlicePass optimization pass

### ISSUE THREAD

**Issue by a-zh** [Samsung/ONE#5757]
Parent Issue : https://github.com/Samsung/ONE/issues/4353
Draft: https://github.com/Samsung/ONE/pull/5876

**What to do in this Pass**
Remove no effect (input and output shape same) `CircleStridedSlice`.

**Input Type**
Example of `StridedSlice` Op with input output shape same:

![strided_slice3](https://user-images.githubusercontent.com/39411904/105168836-bd256d00-5b2b-11eb-9461-f2457fb89a39.jpg)

**TODO**

- [x] Introduce luci/Pass for above optimization. https://github.com/Samsung/ONE/pull/5721
- [x] Introduce this optimization on circle2circle. https://github.com/Samsung/ONE/pull/5759
- [x] Introduce command description. https://github.com/Samsung/ONE/pull/5760
- [x] Introduce `Net_Remove_Unnecessary_StridedSlice_000` test case https://github.com/Samsung/ONE/pull/5852
- [x] Enable `Net_Remove_Unnecessary_StridedSlice_000` test case https://github.com/Samsung/ONE/pull/5853
