### ISSUE TITLE
[Compiler][luci] Integration of inference rule tests

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE#5809]
Originated from https://github.com/Samsung/ONE/pull/5771#discussion_r562509788
Draft : #5811

## What?

Let's integrate tests of `CircleShapeInferenceRule.test.cpp` and `CircleTypeInferenceRule.test.cpp` to `luci_unit_readtest` and `luci_unit_writetest`.

## Why?

Current `CircleShapeInferenceRule.test.cpp` and `CircleTypeInferenceRule.test.cpp` have following problems.
- Tests of `*.test.cpp` are using `Shape(Type)InferencePass` and the passes are using `CircleShape(Type)InferenceRule`
  - Sort of cyclic dependency
- Some of recipes in the tests of `test.cpp` are duplicated with the recipes in `res/`
- `luci_unit_readtest` and `luci_unit_writetest` have same purpose with the tests in `test.cpp`

Thus, integrating the `test.cpp` to `luci_unit_read(write)test` seems better.

## To-do

- [ ] Create missing recipes #5798
- [ ] Update `luci/tests/test.lst` to enable missing recipes
- [ ] Remove `CircleShapeInferenceRule.test.cpp` and `CircleTypeInferenceRule.test.cpp`
- [ ] Add rest of tests to `luci/Service/src/Nodes` which are not available to integrate

**Comment by seanshpark** [comment]
@llFreetimell , I assume exsiting `CircleShapeInferenceRule.test.cpp` maybe one of two cases
- tests are to check algorthim with simple network or morerate network with necessary nodes
- there exist unit test of algorithm somewhere else and these are more complicated case tests

If you are planning to remove first case, then it would be better not to remove them but to refactor to use Rule directly.
If current codes don't permit this, we need to find a way how to do so.
I don't think this as urgent thing.  So, as I wrote before, if these tests get in the way for shape/dtype inference you are working on, you can disable them and then later re-enable them when situation is OK.

**Comment by llFreetimell** [comment]
@seanshpark 

> I assume exsiting CircleShapeInferenceRule.test.cpp maybe one of two cases
> 
> - tests are to check algorthim with simple network or morerate network with necessary nodes
> - there exist unit test of algorithm somewhere else and these are more complicated case tests

Yes, it's totally first case.

> If you are planning to remove first case, then it would be better not to remove them but to refactor to use Rule directly.

I created #5811 by refactoring to use Rule directly :D

> I don't think this as urgent thing. So, as I wrote before, if these tests get in the way for shape/dtype inference you are working on, you can disable them and then later re-enable them when situation is OK.

Yes this is not urgent. And that's why I didn't want to disable them for safe refactoring :)
Of course, if there are no more good options to do it, I will disable it.
But for now, if you are okay with #5811, we can proceed without disabling :)

**Comment by seanshpark** [comment]
> If you are okay with #5811, I will update top comments.

#5811 seems good :) thanks!

**Comment by llFreetimell** [comment]
Purpose and direction of this PR is changed a lot.
So I will close this issue and create another PR with #5811.

Close!
