### ISSUE TITLE
[onert] Update TFLite test version

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#5930]
### What?

Let's use ~`TFLite 2.3`~ `TFLite 2.8` for `onert` execution result verification and benchmark

### Why?

Current verification tools and benchmark tools are using `TFLite 1.13.1`. 
By version update
- Verify more new operations / models without golden data
- Compare with more optimized `TFLite` kernel

### TODO

- [x] Revise `TFLite 2.3` build  #5941
- [x] Update `runtime/libs/tflite` for `TFLite 2.8` to use current `TFLite C API`  #9956
- [x] Update benchmark libraries and binaries ~#5971~ #9671

**Comment by chunseoklee** [comment]
how about going to 2.4 ? (AFAIR, there is a issue that several kerns of 2.4 makes value mismatch)

**Comment by hseok-oh** [comment]
>how about going to 2.4 ?

One concern is that tizen is using TF 2.3

**Comment by chunseoklee** [comment]
> > how about going to 2.4 ?
> 
> Good. One concern is that tizen is using TF 2.3

Ah. I missed it.

**Comment by hseok-oh** [comment]
Done
