### ISSUE TITLE
Checklist for ONE 1.13.0 Release

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#6009]
### Release Action

- [x] Release Note : https://github.com/Samsung/ONE/pull/6019
- [x] Branch out :
  - [x] `master` branch version up : https://github.com/Samsung/ONE/pull/6018 (runtime)
    - [x] tizen spec file
    - [x] nnfw_version.h
    - [x] document version in `/docs/conf.py`
    - [x] onert aar version

### Release Package

- Compiler
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
     - [x] test with public models
     - [x] test with in-house models

### Release Criteria

- Compiler : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0) 
  - [x] TC line coverage link : 83% http://npuci.mooo.com:8080/job/nnfw/job/master/job/daily-compiler-coverage/184/
  - [x]  TCM link : http://npuci.mooo.com/tcm/1.13.0/compiler/tcm-output/result.html (0/1415/582) 56.4%
    - TCM result for base commit : http://npuci.mooo.com/tcm/base/compiler/tcm-output-base-ab2a31ca/result.html (10/391/4)
  - [x] Svace link : https://analysishub.sec.samsung.net/service/analyses/363755
  - [x] Coverity link : https://analysishub.sec.samsung.net/service/analyses/362193
  - [x] SAM link : [4.17/5.0](https://code.sec.samsung.net/architecturemanager/app/sam/NNAS/nnfw_compiler/20210210_f45d579/overview) for f45d579e
  - [x] License Verification : Verified

### Miscellaneous

- [x] SSMS
  - Compiler : 
    - [x] Svace_security : https://analysishub.sec.samsung.net/service/analyses/363870

**Comment by seanshpark** [comment]
Release Note for compiler:
- TBA

**Comment by hseok-oh** [comment]
packages: https://art.sec.samsung.net/artifactory/rs7-runtimentools_generic/ONE/package/release/1.13.0/

**Comment by mhs4670go** [comment]
@seanshpark When I run the test, 
```bash
one-build_008.test FAILED
one-build_009.test FAILED
...
one-import-onnx_001.test FAILED
...
one-import_005.test FAILED
```
```
$ cat one-import_005.log 
Traceback (most recent call last):
  File "/home/seongwoo/test/bin/one-import-onnx", line 161, in <module>
    main()
  File "/home/seongwoo/test/bin/one-import-onnx", line 157, in main
    _convert(args)
  File "/home/seongwoo/test/bin/one-import-onnx", line 96, in _convert
    tf_savedmodel = onnx_tf.backend.prepare(onnx_model)
  File "/home/seongwoo/test/bin/venv/lib/python3.6/site-packages/onnx_tf/backend.py", line 70, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict, **kwargs)
  File "/home/seongwoo/test/bin/venv/lib/python3.6/site-packages/onnx_tf/backend.py", line 91, in onnx_model_to_tensorflow_rep
    **kwargs)
  File "/home/seongwoo/test/bin/venv/lib/python3.6/site-packages/onnx_tf/backend.py", line 111, in _onnx_graph_to_tensorflow_rep
    handlers = cls._get_handlers(opset)
  File "/home/seongwoo/test/bin/venv/lib/python3.6/site-packages/onnx_tf/backend.py", line 303, in _get_handlers
    return get_all_backend_handlers(opset_dict)
  File "/home/seongwoo/test/bin/venv/lib/python3.6/site-packages/onnx_tf/common/handler_helper.py", line 28, in get_all_backend_handlers
    max_inclusive_version=version).since_version
onnx.onnx_cpp2py_export.defs.SchemaError: No schema registered for 'BitShift'!
```
Seems related with onnx. Could you take a look of it?

**Comment by seanshpark** [comment]
There's an issue https://github.com/onnx/onnx-tensorflow/issues 865

> chinhuang007 commented 11 days ago
The issue is that the most recent ONNX 1.8.1 changed an exception type. So you need to use the latest ONNX-TF from source.
Run git clone and pip install or just pip install git+https://github.com/onnx/onnx-tensorflow.git should work too.

Works with explicit setting ONNX version to 1.8.0. I'll prepare a patch both to master and 1.13.0

**Comment by seanshpark** [comment]
#6044 and #6045 posted

**Comment by mhs4670go** [comment]
@lemmaa I ran TCM with following configuration.
```yaml
version: 2
test:
  - name: GTEST_CPP_EXAMPLE
    testCaseLanguage: CPP
    testFW: GTEST
    testCaseFolder:
      - ./

    testFile:
      - extension: cpp
        ends:
          - test

    testCase:
      - condition:
        - functionName:
            starts:
              - 'TEST'

    negativeTestCase:
      - condition:
        - testName:
            ends:
              - NEG

    positiveTestCase:
      - condition:
        - inverse: negativeTestCase

```

And the result is (9/1883/592).
> TCM(New Negitive / New Positive > 1)

How can I calculate this ratio? Could you let me know about the offset to calculate "New" one?

**Comment by lemmaa** [comment]
> How can I calculate this ratio? Could you let me know about the offset to calculate "New" one?

@mhs4670go , you must calculate the ratio after subtracting the number of TC items in the base commit, (10/391/4), from the number of TC items in the final release commit, (9/1883/592) in your measurements. However, the number of NO_ASSERTION TCs in the release commit must be 0. 

According to your measurements, 9 TCs should be corrected. But, the result I ran was (0/1415/582). The reason is probably because you did not target only the `compiler`, but performed TCM for both the `runtime` and the `compiler`. The TCM for compiler should targets only under the `/compiler` folder, and the configuration file used to execute TCM is 
https://github.com/Samsung/ONE/blob/master/compiler/.ahub/tcchecker-tca/config.yaml .

The execution result was updated to the checklist. Please note.

P.S. Sorry for the delay in updating the TCM for release.
