### ISSUE TITLE
Checklist for ONE 1.14.0 Release

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE#6291]
### Release Action

- [x] Release Note : #6293
- [x] Branch out :
  - [x] `master` branch version up : #6305 
    - [x] tizen spec file
    - [x] nnfw_version.h
    - [x] document version in `/docs/conf.py`
    - [x] onert aar version

### Release Package

- Compiler
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
     - [x] test with public models
     - [x] test with in-house models

### Release Criteria

- Compiler : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0) 
  - [x] TC line coverage link : 84% http://npuci.mooo.com:8080/job/nnfw/job/master/job/daily-compiler-coverage/212/
  - [x]  TCM link : http://npuci.mooo.com/tcm/1.14.0/compiler/tcm-output/result.html 56.3% (0/1427/588)
    - TCM result for base commit : http://npuci.mooo.com/tcm/base/compiler/tcm-output-base-ab2a31ca/result.html (10/391/4)
  - [x] Svace link : https://analysishub.sec.samsung.net/service/analyses/412732
  - [x] Coverity link : https://analysishub.sec.samsung.net/service/analyses/412731
  - [x] SAM link : [4.29/5.0](https://code.sec.samsung.net/architecturemanager/app/sam/NNAS/nnfw_compiler/20210322_64873ed/overview)
  - [x] License Verification : Compiler Verified

### Miscellaneous

- [x] SSMS
  - Compiler : 
    - [x] Svace_security : https://analysishub.sec.samsung.net/service/analyses/412734

**Comment by mhs4670go** [comment]
Compiler frontend
- `one-codegen` interface now distinguishes own arguments from backend's.
- Introduces experimental support for generating profile data.
  - Adds `--generate_profile_data` option to `one-optimize`, `one-quantize`.

**Comment by llFreetimell** [comment]
Compiler frontend (More)

- `one-quantize` accepts options.
- Add optimization pass : `RemoveUnnecessaryStridedSlice`

**Comment by cgbahk** [comment]
As I understand, 1.14.0 branch will be revised to preserve `one-codegen` backward compatibility, right?

**Comment by cgbahk** [comment]
Will run SAM on 64873ed03

**Comment by mhs4670go** [comment]
@lemmaa Could you upload the tcm result to `npuci` server? Or you could let me know how to do it instead.

**Comment by lemmaa** [comment]
> @lemmaa Could you upload the tcm result to `npuci` server? I could run tcm but doesn't know how to upload it. 

Uploaded!

> Or you could let me know how to do it instead.

You can  upload the result by copying `tcm-output` folder to `npuci:/data/html/www/tcm/1.14.0/Compiler` folder.

From next time, I expect to be able to replace the result link on the analysishub. :)

**Comment by mhs4670go** [comment]
There's an issue that `one-cmds` cannot catch a segmentation fault(#6310). I think this bug can be fixed later release.

**Comment by llFreetimell** [comment]
1.14.0 was released, close!
