### ISSUE TITLE
Checklist for ONE 1.15.0 Release

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#6632]
### Release Action

- [x] Release Note : https://github.com/Samsung/ONE/pull/6642
- [x] Branch out 
  - [x] `master` branch version up  : https://github.com/Samsung/ONE/pull/6643
    - [x] tizen spec file
    - [x] nnfw_version.h
    - [x] document version in `/docs/conf.py`
    - [x] onert aar version
- [x] Tizen upstream branch update to released one

### Release Package

- Runtime 
  - [x] arm64-android (tar.gz) for Android 10
  - [x] arm64-android (aar) for Android 10
  - [x] arm-tizen (rpm) for Tizen 6.0 M2
  - [x] arm-linux (tar.gz)  for Ubuntu 18.04
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
  - [x] nnfw-devel
  - [x] nnfw-plugin-devel
- Compiler
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
     - [x] test with public models
     - [x] test with in-hose models

### Release Criteria

- Runtime : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0)
  - [x] TC line coverage link : 83%(http://npuci.mooo.com:8080/job/nnfw/job/master/job/daily-arm-runtime-coverage/911/cobertura/)
  - [x] TCM link : http://npuci.mooo.com/tcm/1.15.0/runtime/tcm-output/result.html 55.5% (0/373/178)
    - TCM result for base commit : http://npuci.mooo.com/tcm/base/runtime/tcm-output-base-ab1a04a7/result.html (0/56/2)
  - [x] Svace link : https://analysishub.sec.samsung.net/service/analyses/456541 ( 0 critical )
  - [x] Coverity link : https://analysishub.sec.samsung.net/service/analyses/456543 ( 0 critical )
  - [x] SAM link : [4.54/5.0](https://code.sec.samsung.net/architecturemanager/app/sam/NNAS/nnfw_runtime/20210420_1645e94/overview)
  - [x] License Verification : 
[SR_Tizen_Public_Release_MV_16409_platform+core+ml+nnfwReport_1.15.0.html.zip](https://github.com/Samsung/ONE/files/6340756/SR_Tizen_Public_Release_MV_16409_platform%2Bcore%2Bml%2BnnfwReport_1.15.0.html.zip)

- Compiler : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0) 
  - [x] TC line coverage link : http://npuci.mooo.com:8080/job/nnfw/job/release_1.15/job/daily-compiler-coverage/ (87%)
  - [x] TCM link : http://npuci.mooo.com/tcm/1.15.0/compiler/tcm-output/result.html 51.4% (0/1704/679)
    - TCM result for base commit : http://npuci.mooo.com/tcm/base/compiler/tcm-output-base-ab2a31ca/result.html (10/391/4)
  - [x] Svace link : https://analysishub.sec.samsung.net/service/analyses/466687 ( 0 critical )
  - [x] Coverity link : https://analysishub.sec.samsung.net/service/analyses/466688 ( 0 critical )
  - [x] SAM link : [4.43/5.0](https://code.sec.samsung.net/architecturemanager/app/sam/NNAS/nnfw_compiler/20210420_1645e94/overview)
  - [x] License Verification : 

### Miscellaneous

- [x] nncc preset update if needed
- [x] SSMS
  - Runtime : 
    - [x] Svace_security : https://analysishub.sec.samsung.net/service/analyses/463849 ( 0 critical )
  - Compiler : 
    - [x] Svace_security : https://analysishub.sec.samsung.net/service/analyses/466690 ( 0 critical )

**Comment by chunseoklee** [comment]
Note that tizen's armcl verison is still v20.05. Thus, svace/coverity is done with the past commit (https://github.com/Samsung/ONE/tree/6ecf22edd3960d572b0d6589698093b97d0acc92)

**Comment by mhs4670go** [comment]
@seanshpark Could you write the change for release note? I'll add what I think should be added to yours.

**Comment by seanshpark** [comment]
# Release Note 1.15.0

## ONE Compiler

### Compiler Frontend
- Support more Ops for quantization
- Fix `record-minmax` tool for bool type, NaN values
- Fix `one-cmds` test scripts

**Comment by mhs4670go** [comment]
@lemmaa Could you take a look?
https://analysishub.sec.samsung.net/service/v1/analyses/464541/log

```
15:30:44,638 INFO  -   Analyze local directory. Directory: /home/buildbot/buildagents/tmp-dir-base/build-_wuvvohm/ONE/compiler
15:30:44,640 INFO  -   Project configuration: /home/buildbot/buildagents/tmp-dir-base/build-_wuvvohm/ONE/.ahub/tcchecker-tca/config.yaml
15:30:44,640 INFO  -   Output directory: /home/buildbot/buildagents/tmp-dir-base/result-9lxt5ucc/workspace/tcchecker-tca
15:30:44,948 INFO  -   Checker configuration: /home/buildbot/buildagents/tmp-dir-base/result-9lxt5ucc/workspace/tcchecker-tca/checker_uknec1gz.json
```
I think project configuration is not set properly.

**Comment by hseok-oh** [comment]
### Runtime backend operation supports more operations and types

- CPU backend
  - Add: int8
  - AvgPool2d: int8
  - Conv2D: int8
  - DepthwiseConv2D: int8
  - Div: uint8
  - Elu: float
  - ExpandDims: int8
  - LogicalAnd: boolean
  - Maximum: uint8
  - MaxPool2D: int8
  - Minimum: uint8
  - Mul: int8 
  - Pad: int8
  - PadV2: int8
  - Quantize: uint8, int8
  - Reshape: int8
  - Resizebiliear: int8
  - Softmax: int8
  - Squeeze: int8
  - Sub: int8

**Comment by lemmaa** [comment]
https://github.com/Samsung/ONE/issues/6632#issuecomment-822211511
> @lemmaa Could you take a look?
> https://analysishub.sec.samsung.net/service/v1/analyses/464541/log

@mhs4670 , yes it hasn't been fully set up yet. I have tried following the manual in the past, but there was a problem, and I tried to ask the person in charge how to solve it, but I haven't yet. I will inquire tomorrow, but I think this release should be conducted as a manual test as before.

By the way, where is the 1.15.0 release branch? I tried to test it myself, but I can't find the branch. 
When the 1.15.0 branch is ready, I will post the test results.

**Comment by mhs4670go** [comment]
@cgbahk Could you post the TCM result with 1.15.0 branch?

**Comment by cgbahk** [comment]
> @cgbahk Could you post the SAM result with 1.15.0 branch?

Let me do that with `release/1.15.0` branch, 1645e944

---

BTW What is `svace_1.15.0` branch for? I guess I can just ignore this branch (in terms of SAM)

**Comment by mhs4670go** [comment]
@cgbahk That's for testing svace. It will be deleted soon=)

**Comment by hseok-oh** [comment]
Packages: https://art.sec.samsung.net/artifactory/rs7-runtimentools_generic/ONE/package/release/1.15.0/

**Comment by cgbahk** [comment]
> Let me do that with `release/1.15.0` branch, [1645e94](https://github.com/Samsung/ONE/commit/1645e94493b00440a67f7ba8fa23adc1ce7a1072), both for compiler / runtime

Sorry for lagging :confused: There's issue on making SAM report. Will update as soon as possible

<details>

- CircleCI aborts when there's no output for 10 minutes.
- SAM analysis is heavy task, it sometimes took very long for each step.
- Daily job ran on CI on night, when I guess the actual machine is not very busy. So such 'No output abort' happens less frequently. (1 in 10?)
- For this release, Circle CI infra looks busy, so 'No output abort' is occurring 4 times in a row :sob:
- One SAM analysis usually took about 1.5 ~ 2 hrs...
- I found how to extend 'No output timeout' [:link:](https://support.circleci.com/hc/en-us/articles/360007188574-Build-has-hit-timeout-limit), now trying with this.

**Comment by cgbahk** [comment]
~After all the hours~ SAM updated..!

**Comment by lemmaa** [comment]
TCM updated!

**Comment by lemmaa** [comment]
https://github.com/Samsung/ONE/issues/6632#issuecomment-822488222
> I will inquire tomorrow, ...

https://github.sec.samsung.net/RS-TCM/tcm/issues/663
