### ISSUE TITLE
[Compiler FE] Update docs directory

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE#6651]
## What?

We are providing https://nnfw.readthedocs.io/en/latest/contents.html for documents.

However, some of them should be updated for
- Better Alignment
- Deprecated Files/Contents
- Missing contents

So let's update following things and make readability more easier!

:speaker:  **NOTE for SOS Masters participants** This issue only includes very easy things and little bit difficult things such as writing empty documents are excluded. So don't be afraid to challenge :)

## Todo

- [ ] `docs/overview/workgroup.md`
  - Remove file
- [ ] `docs/compiler/tools.rst`
  - Remove not existing files in the list
- [ ] `docs/release/index.rst`
  - There are no version 1.0~1.3
  - There are so many unnecessary "1.0" title
  - Release document 1.7.0 has no title
  - Release document 1.14.0 did not appear
- [ ] `docs/overview/roadmap.md`
  - Remove workgroup section
- [ ] `docs/overview/supported-operations.md`
  - Update table
- [ ] `docs/compiler/middleend.rst`
  - Remove `compiler/moco-tf/doc/Conversion.md` in the list. Not proper alignment.
- [ ] docs/compiler/ir.rst`
  - Make an alignment for submodules like `luci-export`, etc.
- [ ] `docs/compiler/interpreters.rst`
  - Update `compiler/locomotiv/README.md` for align
- [ ] `docs/compiler/libraries.rst`
  - Some of `README.md` files in the file has improper alignment. Need to fix.
- [ ] `docs/compiler/tools.rst`
  - Some of `README.md` files in the file has improper alignment. Need to fix.

**Comment by seanshpark** [comment]
close as nonactive for some time
