### ISSUE TITLE
Checklist for ONE 1.16.0 Release

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#6833]
### Release Action

- [x] Release Note : #6860 
- [x] Branch out 
  - [ ] `master` branch version up  :
    - [ ] tizen spec file
    - [ ] nnfw_version.h
    - [ ] document version in `/docs/conf.py`
    - [ ] onert aar version
- [ ] Tizen upstream branch update to released one

### Release Package

- Compiler
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
     - [x] test with public models
     - [x] test with in-hose models

### Release Criteria

- Compiler : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0) 
  - [x] TC line coverage link :
  - [x] TCM link : https://analysishub.sec.samsung.net/service/analyses/541167 50.79% (808 / 1591)
  - [x] Svace link : https://analysishub.sec.samsung.net/service/analyses/542666
  - [x] Coverity link : https://analysishub.sec.samsung.net/service/analyses/538484
  - [x] SAM link : https://analysishub.sec.samsung.net/service/analyses/542666 4.13/5.0
  - [x] License Verification : [SR_Tizen_Public_Release_MV_16409_platform+core+ml+nnfwReport_bff45.zip](https://github.com/Samsung/ONE/files/6529999/SR_Tizen_Public_Release_MV_16409_platform%2Bcore%2Bml%2BnnfwReport_bff45.zip)

### Miscellaneous

- [ ] nncc preset update if needed
- [x] SSMS
  - Compiler : 
    - [x] Svace_security : https://analysishub.sec.samsung.net/service/analyses/542667

**Comment by mhs4670go** [comment]
@seanshpark Please post a comment if there's anything to add to compiler release note.

**Comment by seanshpark** [comment]
> Please post a comment if there's anything to add to compiler release note.

I'll check...

**Comment by seanshpark** [comment]
Compiler frontend
- Enable `PadV2` in luci-interpreter and quantization
- Provide `circle-tensordump`, `circledump` as a development tool
- Provide `luci-eval-driver` as test tool
- Enable `STRING` type as constant values in CircleConst
- Fix CircleCustom may have 0 input, 0 output
- Enable debian package generation
- More optimization pass
   - Min(6)+ReLU to ReLU6
   - Remove FakeQuant Op
- Experimental support of ONNX upgraded to version 1.8.0 with additional patch

**Comment by cgbahk** [comment]
On SAM,
1. if https://github.com/Samsung/ONE/pull/6863 merged, we can run SAM analysis with svace. (Need to trigger svace once more after merge)
2. Or we can do run SAM separately as usual.

I plan to go `1.`, is it okay?

cc @lemmaa @chunseoklee @seanshpark @mhs4670go

**Comment by lemmaa** [comment]
> On SAM,
> 
> 1. if #6863 merged, we can run SAM analysis with svace. (Need to trigger svace once more after merge)
> 2. Or we can do run SAM separately as usual.
> 
> I plan to go `1.`, is it okay?

+1 to plan 1. :)

**Comment by lemmaa** [comment]
On TCM, I look forward to pulling the report through AHUB after merge https://github.com/Samsung/ONE/pull/6862 and another PR that follows. :)

**Comment by lemmaa** [comment]
> On TCM, I look forward to pulling the report through AHUB after merge #6862 and another PR that follows. :)

Done!

**Comment by chunseoklee** [comment]
License Report is uploaded(done)

**Comment by hseok-oh** [comment]
Packages are uploaded: https://art.sec.samsung.net/artifactory/rs7-runtimentools_generic/ONE/package/release/1.16.0/
