### ISSUE TITLE
Checklist for ONE 1.16.1 Release (compiler hotfix)

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#6886]
### Release Action

- [x] Release Note : https://github.com/Samsung/ONE/pull/6892
- [x] Branch out 

### Release Package

- Compiler
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
     - [x] test with public models
     - [x] test with in-hose models

### Release Criteria

- Compiler : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0) 
  - [x] TC line coverage link : http://npuci.mooo.com:8080/job/nnfw/job/master/job/daily-compiler-coverage/28/
  - [x] TCM link : https://analysishub.sec.samsung.net/service/analyses/555523
  - [x] Svace link : https://analysishub.sec.samsung.net/service/analyses/555520
  - [x] Coverity link : https://analysishub.sec.samsung.net/service/analyses/555522
  - [x] SAM link : https://analysishub.sec.samsung.net/service/analyses/555522
  - [x] License Verification : 

### Miscellaneous

- [x] SSMS
  - Compiler : 
    - [x] Svace_security : https://analysishub.sec.samsung.net/service/analyses/555521
