### ISSUE TITLE
[Compiler FE] Preserve initial nodes list in source_table for profiling

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE#6952]
### What?

Let's export `source_table` metadata with following criteria
- If `source_table` metadata is originally included in circle model, export it.
- Otherwise, export `source_table` with initially imported nodes list.

### Why?

Currently, `source_table` is updated every moment when circle graph is exported.
(For example, if there were `node1` and `node2` but `node` is removed by optimization, only `node2` is exported to `source_table`).
However, for profiling, `source_table` with all of initial nodes is more meaningful.

### Todo

- [x] Introduce `source_table` in `luci::Module` #6962
- [x] Introduce getter of `source_table` in `luci::ImportMetadata` #6963
- [x] Initialize `Module::source_table` #6965
- [x] Export `Module::source_table` instead of current new `source_table`. #6966 
- [x] Deprecated unused functions #6967 

---

Draft : #6953

/cc @ejjeong

**Comment by llFreetimell** [comment]
With `Net_Squeeze_Squeeze_000.circle` (in `res/TensorFlowLiteRecipes/Net_Squeeze_Squeeze_000/`).

### Command

```bash
circle2circle \
--generate_profile_data \
--substitute_squeeze_to_reshape \
--remove_redundant_reshape \
build/compiler/common-artifacts/Net_Squeeze_Squeeze_000.circle \
Net_Squeeze_Squeeze_000.opt.circle
```

### Before

```bash
$ circledump Net_Squeeze_Squeeze_000.opt.circle
...
metadata : B(index) name
B(2) ONE_source_table
    [node_id : node_name]
    [1 : ofm]
B(3) ONE_op_table
    [node_id : origin_ids]
    [0 : 1]
```

### After

```
$ circledump Net_Squeeze_Squeeze_000.opt.circle
...
metadata : B(index) name
B(2) ONE_source_table
    [node_id : node_name]
    [0 : t1]
    [1 : ofm]
B(3) ONE_op_table
    [node_id : origin_ids]
    [0 : 1]
```

**Comment by llFreetimell** [comment]
Done!
