### ISSUE TITLE
[Compiler] Post-training Quantization Support

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#696]
**Update: 2020/06/05**. layer-wise quantization -> channel-wise quantization.
List of channel-wise quantized Ops (conv, depthwise_conv, fc, transpose_conv)

**Update: 2020/05/22**. Step 0 was added to consider quantization loss when recording min/max.

We plan to support post-training quantization. Quantization algorithm is channel-wise affine quantization using representative dataset (similar to: TensorFlow [calibrator](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/python/optimize/calibrator.py#L57)).

### Quantization using representative dataset 

**Brief overview**: Record min-max values of tensors while performing inference on the given representative dataset. Next, calculate zero point and scale using the recorded min-max values. Finally, quantize the model using the derived zero point and scale.
(Quantization formula: real value = scale * (quantized value - zero point))

<center><img src="https://user-images.githubusercontent.com/5449554/82645539-faa8c200-9c4d-11ea-94b9-50f49531966f.png" width="600"></center>

**Step 0. Quantize and dequantize the weights of the model (by luci)**
**Input**: circle model (fp32)
**Output**: circle model (fp32) whose weights are quantized and dequantized.
**Details**: Users run ```circle2circle``` with the option ```--quantize_dequantize_weights```. ```circle2circle``` imports the fp32 circle model, runs an optimization pass named ```QuantizeDequantizeWeightsPass```, and exports the model as the fp32 circle model. ```QuantizeDequantizeWeightsPass``` quantizes weights and then dequantizes the weights back. This is to further consider quantization loss during profiling.

**Step 1. Record min-max value of each tensor while running the representative dataset (by luci-interpreter)**
**Input**: circle model (fp32), representative dataset (~~format is TBD. hdf5?~~ format is hdf5)
**Output**: circle model (fp32) where min-max values of tensors are saved in [QuantizationParameters](https://github.com/Samsung/ONE/blob/master/nnpackage/schema/circle_schema.fbs#L67).
**Details**: Users run executable named ```record-minmax```, which invokes luci-interpreter to perform inference on the given dataset. Whenever performing inference on each data, ```record-minmax``` records the moving average of min and the moving average of max for each tensor. After the whole dataset is fed to the interpreter, the recorded average min-max values are saved in the ```QuantizationParameters``` of each tensor in the circle model. 

**Step 2. Quantize the model using the embedded information (by luci)**
**Input**: circle model (fp32) where min-max values of activations are saved in QuantizationParameters
**Output**: circle model (uint8)
**Details**: Users run ```circle2circle``` with the option ```--quantize_with_minmax```. ```circle2circle``` imports the fp32 circle model embedded with min-max values, runs an optimization pass named ```QuantizeWithMinMaxPass```, and exports the model as the quantized uint8 circle model. ```QuantizeWithMinMaxPass``` calculates scale and zero point of each tensor using min-max values saved in QuantizationParameters. For constant tensors with no recorded min-max values (e.g., weights, bias), ```QuantizeWithMinMaxPass``` finds min-max values on the fly and quantizes the tensor using the values. 

**Goal**:  Support the above quantization scheme for ResNet, Inception, and MobileNet.

**TODO list**
1. luci-interpreter part (Step 1)

- [x] Extend luci-interpreter to support logging functionality. #1098
- [x] Implement a driver (```record-minmax```) that runs luci-interpreter for a given dataset and records moving avg of min/max. #1605
- [x] Support operators in Inception, ResNet, and MobileNet (optional: quantized version of the operators would be useful for testing accuracy). #1157
- [x] Test #1948 

2. luci part (Step 0, 2)
- [x] Prepare reference models and datasets
- [x] Prepare a sample circle model (to start work in parallel with luci-interpreter).
- [x] Add options for quantization to circle2circle. #1120
- [x] Implement QuantizeDequantizeWeights and QuantizeWithMinMaxPass in luci. #1459, [internal link](https://github.sec.samsung.net/STAR/nnapps/issues/379)
([uint8, int16] [LWQ, CWQ]])
- [x] Test #2088

More issues
1. How to test the accuracy of a quantized circle model?
- To test accuracy, we need a runtime for a quantized circle model. What would be the choice? (onert, luci-interpreter?) Or is it possible to convert circle to tflite and run the tflite model on TFLite Interpreter?

**Comment by jinevening** [comment]
I close this PR as post-training affine (`pota`) quantization has been implemented. Issues for details and extensions will be discussed in new issues.
