### ISSUE TITLE
Checklist for ONE 1.17.0 Release

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#6983]
### Release Action

- [ ] Release Note
- [ ] Branch out 
  - [ ] Update debian package `changelog`

### Release Package

- Compiler
  - [ ] x64-linux (tar.gz) for Ubuntu 18.04
     - [ ] test with public models
     - [ ] test with in-hose models

### Release Criteria

- Compiler : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0) 
  - [ ] TC line coverage link : 
  - [ ] TCM link : 
  - [ ] Svace link : 
  - [ ] Coverity link : 
  - [ ] SAM link : 
  - [ ] License Verification : 

### Miscellaneous

- [ ] nncc preset update if needed
- [ ] SSMS
  - Compiler : 
    - [ ] Svace_security :

**Comment by lemmaa** [comment]
Let's think a little bit about the schedule for this release. I'm thinking about what the main purpose of this release will be, and considering a code freeze around the 25th.

**Comment by mhs4670go** [comment]
@lemmaa I agree on that schedule. Actually, I saw the code freeze be 22th in calendar last week, which has been changed.

**Comment by chunseoklee** [comment]
## runtime release note
### gpu_cl backend added
- New backend(gpu_cl) added. This backend exploits tensorflow lite's gpu delegate.
- This backends supports the following operations : Add, Convolution, Depthwise Convolution, Pooling, Reshape, Relu, Softmax

**Comment by mhs4670go** [comment]
## ONE Compiler

### Compiler Frontend

- More optimization pass
  - Remove Quant-Dequant sequence
  - Replace Sub with Add
  - Substitute StridedSlice to Reshape
  - Fuse Mean with Mean
  - Fuse Transpose with Mean
  - Substitute PadV2 to Padd
- Add new InstanceNorm pattern in `FuseInstanceNormPass`
- Add verbose option
- Introduce `onecc` driver to `one-cmds`
- Introduce `one-profile` driver to `one-cmds`

@seanshpark Could you check this release note?

**Comment by seanshpark** [comment]
`PadV2 to Padd` -> `PadV2 to Pad` ?

**Comment by cgbahk** [comment]
FYI

> * SAM link : https://code.sec.samsung.net/architecturemanager/app/sam/NNAS/nnfw_compiler/20210819_2d3a33c/overview

We can now get SAM score just from same SVACE link now, and IMHO that is done for more accurate commit:

> * [x]  Svace link : https://analysishub.sec.samsung.net/service/analyses/770472
