### ISSUE TITLE
runtime: create debian package on launchpad.net

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#7190]
## Background

There is a request for running NN model on x86_64 Ubuntu via nnstreamer. nnstreamer already have been published in launchpad PPA(w/o ONE plugin).

## TODO

- [ ] PPA naming / launchpad accont naming
- [ ] Package build on launchpad.net
- [ ] Integration with nnstreamer
 
## Link
- nnstreamer ppa :  https://launchpad.net/~nnstreamer/+archive/ubuntu/ppa
