### ISSUE TITLE
[luci-interpreter] Enable MCU configurable build

### ISSUE THREAD

**Issue by binarman** [Samsung/ONE#7288]
This task is generalization of #6302

## Goal

Enable MCU build of luci-interpreter along with the regular version in ONE.

## Rationale

To run NN on MCUs we need lightweights runtime, luci-interpreter seems suitable for this task.

## Details

During offline discussions we found several challenges:
1. Make MCU build developer friendly. For now build of luci-micro requires a lot of manual actions, like toolchain downloading, project configuration, etc.
2. Make it possible to build luci-interpreter for different platforms in ONE repo without interference between them: enabling of one platform **should not degrade features/performance** of other supported platforms. Currently if we want to build interpreter for bare metal we need to switch to slower kernels on all platforms.
3. Require as little RAM as possible for interpreter itself. For now there are no convenient mechanism to build subset of all available kernels (described as a **Build time configurable** approach mentioned above).

To achieve goals above we came up with several steps:

- [x] Refactor `KernelBuilder`, to simplify it's configuration with set of supported operators during build for different platforms. (Current design contains multiple `KernelBuilders` and make it hard to configure subset of used kernels.
  - One possible solution is to revive old "large" `KernelBuilder`, put it's visit methods into different files and generate declaration of `KernelBuilder` during CMake stage. (need to check if SAM is ok with this solution)
  - Another possible solution is to make `KernelBuilder` dynamic and fill opcode->builder mapping in runtime. (I suppose SAM score will be ok, but need to check readability of such code)
- [x] Enable partial interpreter build from list of operators.
  - Introduce list of supported operations for each target platform and implement infrastructure to build only selected kernels from this list.
- [x] Implement Hardware Abstraction Layer (maybe "Platform Abstraction Layer", we need to decide terminology yet) to abstract from available OS resources, for example threads (unavailable on bare metal).
  - Implement Abstract layer to specialize different luci-interpreter builds variants without interference between them. See draft #7237 for example of such AL.
- [x] Build integration of luci-interpteter for MCU into main build system.
  - Add wrappers around OS dependent components in various `CMakeList.txt`, to conditionally enable/disable these builds for different platforms.
  - Automate download and configuration of target MCU toolchain.
  - Integrate MCU specific build into main build sequence.

**Upd**. We have all part in form of drafts, but it is hard to merge them like this, because they have a lot of dependencies between them. Instead we will break large DRAFTs in smaller PRs, plan TBD below.
  
**Related PRs**

- `KernelBuilder` refactoring:
  - case 1: draft #7289
  - case 2: draft #7298
  - case 3: draft #7338
- Partial build:
  - draft #7289
- PAL (Platform Abstraction Layer):
  - draft #7336
- Build integration
  - draft #7304

**Merge plan** (subject to change, because of large modified/added code size)
- [x] Fix naming of Prelu (should be PRelu) and Reverse (should be ReverseV2) kernels #7444
- [x] Rename Reverse kernel #7445
- [x] Add test for MirrorPad (there are no test, this is a problem for building tests from list of supported operators) (workaround introduced in #7479)
- [x] Introduce Linux PAL #7363
- [x] Introduce MCU PAL #7363
- [x] Introduce lists of kernels to build + CMakeList changes: part of  #7479
- [x] refactor kernel builder to use list of kernels to build #7509
- [x] split kernel builders to separate files to enable partial build draft #7605
  - [x] Move collectOutputNodes function #7615
  - [x] Introduce kernel builders in separate files #7614
  - [x] Switch to separate files #7649
- [x] Introduce wrappers for computational code to abstract kernels from platform dependent code #7650
- [x] add luci-micro build system
  - [x] install toolchain in docker #7508
  - [x] fix problems with arm toolchain build #7463
  - [x] Enable build of luci-micro in ci #7717
    - [x] Add cmake files for luci-micro #7757
    - [x] Download TF 2.6.0 related ruy and Eigen libraries #7739
    - [x] Bump TF version to 2.6.0 #7742 
    - [x] Fix type mismatch problems #7755 
    - [x] Add kernels to KernelsToBuild.lst #7758
    - [x] Introduce basic infrastructure for arm build #7764
- [ ] host tests for MCU profile?
- [ ] HW tests for MCU profile?
- [ ] Add HOWTO add new kernels and documentation describing new structure of interpreter

**Comment by binarman** [comment]
+cc @SlavikMIPT @Bronnikoff

**Comment by Bronnikoff** [comment]
For steps 1-2 draft is #7289.

**Comment by SlavikMIPT** [comment]
https://github.com/Samsung/ONE/pull/7304 related PR

**Comment by SlavikMIPT** [comment]
Introduce Linux PAL https://github.com/Samsung/ONE/pull/7362

**Comment by SlavikMIPT** [comment]
https://github.com/Samsung/ONE/pull/7443
https://github.com/Samsung/ONE/pull/7444

**Comment by SlavikMIPT** [comment]
https://github.com/Samsung/ONE/pull/7479

**Comment by SlavikMIPT** [comment]
https://github.com/Samsung/ONE/pull/5475

**Comment by binarman** [comment]
I've worked on arm interpreter build and found that not all tflite code is portable, so some kernels should be disabled for arm32 MCU build =(
This is number of operations supported for different configurations:

configuration | number of supported ops
--- | ---
linux (full list of operations) |  68
ARM + TF 2.3.0 kernels | 45
ARM + TF 2.6.0 kernels | 56

TF 2.6.0 provides more compatible kernels, so I am going to bump tf version (if possible) to 2.6.0

**Comment by SlavikMIPT** [comment]
https://github.com/Samsung/ONE/pull/7818
https://github.com/Samsung/ONE/pull/7809
https://github.com/Samsung/ONE/pull/7817

**Comment by SlavikMIPT** [comment]
https://github.com/Samsung/ONE/pull/8030

**Comment by SlavikMIPT** [comment]
https://github.com/Samsung/ONE/pull/8045

**Comment by seanshpark** [comment]
we have MCU support with `onert-micro`
