### ISSUE TITLE
Compiler FE: Fix typo in MaxPoolWithArgmax 

### ISSUE THREAD

**Issue by Bronnikoff** [Samsung/ONE#7306]
### What?

Let's change `MaxPoolWithArgMax` to `MaxPoolWithArgmax` in all modules.

### Why? 

Currently, in *compiler/tflchef* and *res/TensorflowLiteRecipes* we use `MaxPoolWithArgMax` as name for castom op, but Tensorflow provides node with name [MaxPoolWithArgmax](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/max-pool-with-argmax) and conversion of corresponding `tf` models to `tflite` produces castom node with name `MaxPoolWithArgmax`. 

![image](https://user-images.githubusercontent.com/43731397/126882491-a9f6f0bd-c44a-48be-b994-6e125cc00520.png)

This misleading makes harder to provide `circle2circle-dredd-recipe-test` for #7236.

- [x] Support both variants of tests in tflchef #7344
- [x] Disable new tests in common-artifacts #7345
- [x] Fix resources #7390 
- [x] Apply changes in tflchef #7407
- [x] Cleanup common-artifacts (remove old names) #7406

**Comment by Bronnikoff** [comment]
Draft: #7307

**Comment by binarman** [comment]
everything is merged, closing
