### ISSUE TITLE
Support pre-built binary on runtime

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#7400]
### TODO

- [ ] Define pre-built binary format on nnpackage(#7395)
- [ ] Define operation for PBB(pre-built binary)
- [ ] Loader for PBB
- [ ] TBD

**Comment by chunseoklee** [comment]
Here is a picture which depicts the whole flow during model conversion from pb/tflite to nnpkg with pre-built(e.g. NPU) binary :  
<img src=https://user-images.githubusercontent.com/4862887/133561973-c5c34080-fa3d-4fb8-80cb-691054c6d287.png height=300px>

Here is TODOs on compiler side, IMHO.

- Define nnpkg format for partitioned models with pre-built binaries(This is both for runtime and compiler)
    + Consider the nnpkg containing both circle model and pre-built binary
- Toolchain(in one-cmd) for generating the multi-model nnpkg
    + This tool will compile pre-built binary, generate pkg information(e.g. meta info about prebuilt bin), and make an nnpkg.
