### ISSUE TITLE
[circle2circle] Constant folding for DepthwiseConv2D

### ISSUE THREAD

**Issue by ai-moiseev** [Samsung/ONE#7505]
## What

Implement folding optimization to simplify DepthwiseConv2D nodes with constant inputs.

## Why

There's need to optimize models with such a pattern.

## Steps

* [x] DepthwiseConv2D constant folding pass #7576 
* [x] Optimization option in `circle2circle` #7597 
* [x] Option in `one-cmd` #7613 
* [x] Unit tests #7576 

Draft: #7570

**Comment by seanshpark** [comment]
Also need to add option to `one-cmds`

**Comment by llFreetimell** [comment]
When trying to build `luci` only, following header file causes build error.

https://github.com/Samsung/ONE/blob/072c4c0377bdbc600a035a3faa1d6a389fa7c906/compiler/luci/pass/src/FoldDepthwiseConv2DPass.cpp#L19

Cannot find the header file... :(
