### ISSUE TITLE
[luci-interpreter] Improve memory management

### ISSUE THREAD

**Issue by binarman** [Samsung/ONE#7572]
This is an umbrella issue, to harness luci-interpreter memory related issues.

### Goal

Reduce amount of memory required by luci-interpreter for inference.

### Rationale

Currently luci-interpreter copies a lot of data of luci model and rely on dynamic allocations (new/delete).
This technique works fine on platforms with relatively large RAM and paged memory (like Windows or Linux), but performs poor in more restricted environments, like MCU or ARM TrustZone without MMU.

### Related issue

- [x] Move tensor memory management to separate class #7355
- [x] Design and implement Buddy memory manager #7571
- [ ] Design and implement static memory planner and manager #7522
- [ ] Remove duplication of constants in RAM #7604
- [ ] TBD

**Comment by seanshpark** [comment]
requirement is now for `onert-micro`
