### ISSUE TITLE
[circle2circle] Broadcast removal for contstant inputs

### ISSUE THREAD

**Issue by ai-moiseev** [Samsung/ONE#7602]
## What

Implement transformation pass to expand constant node inputs following broadcasting rules.

## Why

There's need to transform models with such a pattern.

## Steps

* [x] RemoveBroadcast transformation pass #7603 
* [x] Option in `circle2circle` #7646
* [x] Option in `one-cmd` #7675 
* [x] Unit tests

**Comment by seanshpark** [comment]
@ai-moiseev , could you please share which models needs this and the reason?

**Comment by ai-moiseev** [comment]
@seanshpark This pattern appears in one of the internal models, I've emailed you link to it...

**Comment by seanshpark** [comment]
Thanks for the mail :)

For the record; see compiler backend issue 9567

**Comment by seanshpark** [comment]
close as done
