### ISSUE TITLE
[Circle-OpSelector] Let's make a GUI tool for Circle-OpSelector

### ISSUE THREAD

**Issue by kevin622** [Samsung/ONE#7760]
Hi! This is team Cosmos developing `Circle-OpSelector`(#7596)

This Issue introduces the GUI tool for `Circle-OpSelector`.

## why

`Circle-OpSelector` is a tool to slice a `circle` model for convenience in debugging. An user can slice a `circle` model by typing code in **CLI**.

We thought that if this could be done by **GUI**, that is, if the slicing can be done in a graphical environment, the convenience would increase. That is why we are trying to develop a GUI tool for `Circle-OpSelector`.

## goal

The main purpose of this tool is to enable `Circle-OpSelector` features using **mouse cursor**. Slicing the graph should be done by just a couple of mouse clicks.

The picture below is the blueprint of the usage of the tool. Visualization is done using `inception_v3` file and [Netron](https://github.com/lutzroeder/netron) .

![image-20210925003521103](https://user-images.githubusercontent.com/46149751/134800608-f1c8678d-fc40-482d-8ac9-8fd07f0d203b.png)

By selecting several nodes with the cursor, the user would be able to create a subgraph(a new `circle` file).

## how

I'm using [Vue](https://vuejs.org/) to create this application. `Vue` is a JS framework for creating web pages, web applications, etc. The only reason why I chose this framework is because I am used to using `Vue`,  so I can't guarantee that this is the best option.

### Todo List

- [ ] create `flatbuffers.js`
- [ ] create a `Vue` project
- [ ] make the application read `Circle` file input(using `flatbuffers.js`)
- [ ] visualize the graph
- [ ] enable selecting nodes by `click` event
- [ ] create a new subgraph using the selected nodes. 

For creating a new subgraph, there are 2 options I'm considering. 
1. Activate the developed `Circle-OpSelector` via the application.
2. Develop the `Circle-OpSelector` in `Javascript`.  

Currently I'm considering the first option and looking for a way to enable it.

*ps. I wanted to make sure I know all the codes in the visualization app, so I know where to apply the `Circle-OpSelector`code. This is the reason why I'm developing this tool from scratch and not using the codes in [Netron](https://github.com/lutzroeder/netron).*

**Comment by seanshpark** [comment]
>  The only reason why I chose this framework is because I am used to using Vue

Are you going to maintain the codes after you land these?
Or do we have any maintainers here to do so?

**Comment by seanshpark** [comment]
@kevin622 , we don't have any development (verification, validation and others) infra for JS nor Vue in ONE.
What is your schedule for that?

**Comment by lemmaa** [comment]
@kevin622 , how about starting this work as a sub project in `ONE-vscode` repo?

**Comment by glistening** [comment]
@seanshpark Thank you for feedback. 

First, SSAFY program will end in Oct 8. There are additional job including preparing final presentation and so so. Thus, the development should be finished about 2 days before Oct 8.

> @kevin622 , we don't have any development (verification, validation and others) infra for JS nor Vue in ONE.
> What is your schedule for that?

Second, I am not sure `ONE` is the proper location to put this code. But I let him to make issue and share information in `ONE` to get feedback. 

https://github.com/Samsung/ONE-vscode may be an alternative option. This tool will not be developed as `VSCode Extension` at this early development stage.

I've found https://github.com/Samsung/ONE/issues/7760#issuecomment-927441489 during this writing. I like this idea.

**Comment by glistening** [comment]
@kevin622 Please create issue in https://github.com/Samsung/ONE-vscode. Let's make a gui tool for `circle-opselector` as a subproject of `ONE-VSCode`. This code may put under `experimental`.

**Comment by kevin622** [comment]
> @kevin622 Please create issue in https://github.com/Samsung/ONE-vscode. Let's make a gui tool for `circle-opselector` as a subproject of `ONE-VSCode`. This code may put under `experimental`.

I will do as so. As soon as I create the issue(identical to the current one) in `ONE-VSCode`, I will close this issue.

**Comment by kevin622** [comment]
I wrote the new issue [here](https://github.com/Samsung/ONE-vscode/issues/147).
