### ISSUE TITLE
[luci/plan] Add unit tests

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#7831]
We need to add unit tests for `luci/plan`. Also 1:1 negative tests, that is one ore more negative test(s) for one positive test.

- [x] Tests for luci/plan #7883 
- [x] Tests for luci/import #7903 
- [x] Tests for luci/export #7884

**Comment by seanshpark** [comment]
I think we can close this issue. Please reopen if necessary.
