### ISSUE TITLE
Checklist for ONE Release 1.18.0

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#7843]
### Release Action

- [x] Release Note
- [x] Branch out 
  - [x] Update debian package `changelog`

### Release Package

- Compiler
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
     - [x] test with public models
     - [x] test with in-hose models

### Release Criteria

- Compiler : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0) 
  - [x] TC line coverage link : http://npuci.mooo.com:8080/job/nnfw/job/release_1.18/job/daily-compiler-coverage/
  - [x] TCM link : https://analysishub.sec.samsung.net/service/analyses/899201
  - [x] Svace link : https://analysishub.sec.samsung.net/service/analyses/899285
  - [x] Coverity link : https://analysishub.sec.samsung.net/service/analyses/898168
  - [x] SAM link : https://analysishub.sec.samsung.net/service/analyses/899201
  - [x] License Verification : [21_one_1180Report.html.zip](https://github.com/Samsung/ONE/files/7362517/21_one_1180Report.html.zip)

- Runtime : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0)
  - [x] TC line coverage link :  83%(http://npuci.mooo.com:8080/job/nnfw/job/release_1.18/job/daily-arm-runtime-coverage/2/cobertura/)
  - [x] TCM link : https://analysishub.sec.samsung.net/service/analyses/899714
       - base : (2/56), thus 54%(158/290) TCM
  - [x] Svace link : https://analysishub.sec.samsung.net/service/analyses/899709
  - [x] Coverity link : https://analysishub.sec.samsung.net/service/analyses/899711
  - [x] SAM link : 
  - [x] License Verification : [21_one_1180Report.html.zip](https://github.com/Samsung/ONE/files/7362517/21_one_1180Report.html.zip)
