### ISSUE TITLE
[CI] Migration format check and commit check 

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#7859]
Let's migrate format check and commit check from jenkins to github actions

### TODO

- [ ] Initial commit
- [ ] Format checker (main, PR)
- [ ] Commit body check (PR)
- [ ] Signed-off check (PR)
