### ISSUE TITLE
[luci-interpreter] Generalize temporary buffer handling in conv, depthwise_conv and avg_pool2d operations

### ISSUE THREAD

**Issue by binarman** [Samsung/ONE#7906]
### What?

Support temporary buffer of different sizes for different target platforms.

### Why?

CMSIS NN requires temporary buffers for conv2d and depthwise_conv2d operations.

- luci-interpreter creates im2col for Conv2d operation, but cmsis-nn buffer is significantly smaller, os use of ordinary im2col buffer would be a waste of RAM.
- luci-interpreter does not allocate any temporary buffers for depthwise_conv2d.

### Plan

Need to:
- [ ] Implement and use PAL interface for temporary buffers allocation for Conv2d #7987
- [ ] Implement and use PAL interface for temporary buffers allocation for Depthwise_Conv2d #8044 
- [ ] Implement and use PAL interface for temporary buffers allocation for AvgPool2d #8047 
- [ ] Support different planning modes in execution planer #8048

**Comment by binarman** [comment]
PRs exposed this problem: #7895 #7890

**Comment by binarman** [comment]
+cc @BalyshevArtem @SlavikMIPT

**Comment by seanshpark** [comment]
seems applied now
