### ISSUE TITLE
Checklist for ONE release 1.19.0

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#7943]
### Release Action

- [x] Release Note
- [x] Branch out 
  - [x] Update debian package `changelog`

### Release Package

- Compiler
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
     - [x] test with public models
     - [x] test with in-hose models

### Release Criteria

- Compiler : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0) 
  - [x] TC line coverage link : http://npuci.mooo.com:8080/job/nnfw/job/release_1.19/job/daily-compiler-coverage/ (86%)
  - [x] TCM link : https://analysishub.sec.samsung.net/service/analyses/961988
  - [x] Svace link : https://analysishub.sec.samsung.net/service/analyses/961986
  - [x] Coverity link : https://analysishub.sec.samsung.net/service/analyses/961989
  - [x] SAM link : https://analysishub.sec.samsung.net/service/analyses/961986
  - [x] License Verification : [Report.zip](https://github.com/Samsung/ONE/files/7518639/21_one_1180Report.zip)
