### ISSUE TITLE
[one-cmds] Refactor onnx_legalizer

### ISSUE THREAD

**Issue by binarman** [Samsung/ONE#8148]
## Problem

onnx_legalizer.py code is hard to understand, need to improve it's readability.

## What to do

- [x] replace general `transformer.make_node` method with specialized methods, like `make_gemm` #8202
- [x] add '_' to hide internal functions #8419
- [x] add more comments to main functions #8405
- [ ] add helper methods to change output tensor in operations (need them to remove reset of `make_node` calls)
- [x] Remove unused variables #8419

**Comment by seanshpark** [comment]
Title typo?

**Comment by seanshpark** [comment]
close as done
