### ISSUE TITLE
[luci/pass] Refactoring VerifyQuantizedNode*Type

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE#8297]
### What?

There are `VerifyQuantizedNodeU8Type` and `VerifyQuantizedNodeS16Type` in `luci/pass`.
Let's refactor following things!

- Reduce duplicated codes
- Reduce if-else statement
- Increase cohesion of `QuantizedNodeType` related codes.

### How?

- Apply strategy pattern by introducing `VerifyQuantizedNodeType` as base Strategy interface class
  - Introduce `create` function which creates `VerifyQuantizedNodeType` according to `datatype`
- Introduce `VerifyQuantizedNodeTypeNormalStrategy` as concrete Strategy class with template
  - Grouping similar `visit` functions to here
  - Different `visit` functions are implemented in derived class
  - Introduce helper function to reduce similar codes

---

#### Related PRs

- Draft : #8298
- [x] Introduce `VerifyQuantizedNodeType`
  - [x] Declaration of base and derived class #8333
  - [x] Declaration of helper function #8351
- [x] Apply `VerifyQuantizedNodeType` #8350
- [x] Remove unused codes #8378

**Comment by llFreetimell** [comment]
Done!
