### ISSUE TITLE
[luci/logex] Refactoring NodeSummaryBuilder

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE#8357]
#### Removing LoC Workarounds

Currently, we applied following workarounds to avoid large LoC.

- Separating visit functions with alphabet grouping
https://github.com/Samsung/ONE/blob/3265df39970d76db5433815b8ba68a8180532645/compiler/luci/logex/src/FormattedGraph.cpp#L2248-L2256
- Just moving implementation to another function
https://github.com/Samsung/ONE/blob/3265df39970d76db5433815b8ba68a8180532645/compiler/luci/logex/src/FormattedGraph.cpp#L1468

Let's try to remove the workarounds!

#### Trivial updates

- Add `CircleBidirectionalSequenceLSTMOut`
- Remove unused codes
- Remove dependency with `pepper-str`

### How?

I will apply following things

- Strategy pattern for creating NodeSummaryBuilder
- Template method pattern for building summary
- Remove duplicated code with class inheritance

Then I expect following result :)

#### Before

![before](https://user-images.githubusercontent.com/24720192/151469394-12bdf759-af6b-4f9b-90aa-c755384db4c7.png)

#### After

![after](https://user-images.githubusercontent.com/24720192/151469406-666a1a34-968c-4442-8140-26e39fbfb0be.png)

---

#### Related PR/Issue

- Draft : #8358

#### Todo

- [x] Introduce helper functions as separate file #8391
- [x] Introduce `CircleNodeSummaryBuilder`
  - [x] #8403
  - [x] #8565
- [x] Implement `Circle*SummaryBuilder` for each CircleNode
  - [x] ABC #8483 
  - [x] DEF #8490 
  - [x] GHIJ #8514
  - [x] KLMN #8518
  - [x] OPQR #8533 
  - [x] STUV #8544
  - [x] WXYZ #8564
  - [x] CIRC, VIRT #8571
- [x] Replace `SummaryBuilderLet` with `CircleNodeSummaryBuilder` #8469
- [x] Remove unused codes #8576

**Comment by llFreetimell** [comment]
Finally Done!
