### ISSUE TITLE
[circle-quantizer] Quantization configuration file

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#8399]
## What

Let's design & implement quantization configuration file for mixed-precision quantization

## Attributes
- `default_quantization_dtype` : `uint8` or `int16`
- `layers` : Array of layers that will have quantization schemes different from `default_quantization_dtype`
  - Each layer will have following attributes
    - `name`
    - `precision` : `uint8` or `int16`
    - `granularity` : `layer` or `channel`

## TODO
- [x] infra: Add jsoncpp library
- [x] luci: Introduce Context to QuantizeWithMinMax and QuantizeDequantizeWeights
- [x] luci: Introduce LayerInfo to QuantizeWithMinMax and QuantizeDequantizeWeights
- [x] circle-quantizer: Parse quant config file using jsoncpp
- ~one-quantize: Update cmdline interface to accept quant config file (this will be done after mixed-precision is actually supported)~

Related to: https://github.com/Samsung/ONE/issues/8398

**Comment by jinevening** [comment]
Copied from #8398 

@seanshpark : Have you decided which format to use? and which library?

@jinevening : JSON looks good to me due to the following reasons
- Widely used, MIT licensed parser: jsoncpp (https://github.com/open-source-parsers/jsoncpp)
- More concise than XML
- Allow array

**Comment by seanshpark** [comment]
> Widely used, MIT licensed parser: jsoncpp 

@llFreetimell , can you please proceed internal license checking?

**Comment by llFreetimell** [comment]
`jsoncpp` itself can be used.
Detailed license verification is available when actual source code is written.

**Comment by jinevening** [comment]
Done.
