### ISSUE TITLE
[onert] Prepare Tizen M1 Release

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#8775]
## Objective 

Track the progress of Tizen M1 Release

## Tizen M1 Goal

- Run nnpkg (with single trix binary) on onert

## Limitation note

Trix-engine devel package is available for gbs build(armv7l). Thus, we are working on gbs build.

## TODO
- [x] Define nnpkg for trix(+ trix metadata definition) 
    - [x] add trix into nnpkg spec (@hseok-oh, @glistening)
      + #8784, #8794 
    - [x] prepare example nnpkg (mobilenet)
    - [x] support trix in nnpkg tool
      - [x] #8836 (@glistening) 
- [x] onert API support for trix (.tvn) (@glistening)
  - [x] #8884
- [x] trix loader (#8832) (@glistening, _@dayo09_, @jyoungyun )
- [x] #8795
- [x] #8788
- [x] #8820
  - [x] #8891 (@glistening)
- [x] SE Release Criteria
  + [x] DC #8786 (@hseok-oh, _@glistening_ )
  + [x] Enable x86_64 Coverage test with trix simulator (@hseok-oh )
  + [x] Function coverage over 80% #8950 ( @hseok-oh, @glistening )
  + sam score : 4.47 (DC : 4.03) on [link](https://analysishub.sec.samsung.net/service/analyses/1273416)
- [x] Security Verfificaiton (@chunseoklee)
  + in progress internally

**Comment by chunseoklee** [comment]
cc @Samsung/one_onert

**Comment by glistening** [comment]
@hseok-oh I've put my names on items to work together with you. I put my name in italic on backend since others also seem to have interest on backend.

**Comment by glistening** [comment]
I added one item

> onert API support for trix (.tvn)

to support `trix (tvn)` model_types.

**Comment by hseok-oh** [comment]
Function coverage issue

- Hit/Total: 4672/5920 - 78%
  - Need more 120 hit
  - Major miss directory: `.compute/cker/include/cker/operation`
    - 370/604 61.3% (line coverage: 3105/3582 86.7%)
    - `Comparision.h`
      - Line coverage 100%, Function coverage 47.6% (80/168)
      - Maybe `template` 's type issue

**Comment by chunseoklee** [comment]
I will make a SR(tizen submit request) with 189a3680 since 1) SR takes too much time to be accepted(tizen's SR CI test takes about 1 days), and 2) M1 feature is done on 189a3680

**Comment by chunseoklee** [comment]
Tizen SR failed due to x86_64 build break. This will fixed by #8928

**Comment by chunseoklee** [comment]
SR for "M1 feature complete" has been accepted in https://dashboard.tizen.org/index.code?sr=submit/tizen/20220415.122003 

Let's prepare ONE public release

**Comment by glistening** [comment]
@hseok-oh function coverage 점수는 어디에서 확인할 수 있을까요? analysis hub 에서 뒤져 봤는데 못 찾겠네요~

**Comment by lemmaa** [comment]
> @hseok-oh function coverage 점수는 어디에서 확인할 수 있을까요? analysis hub 에서 뒤져 봤는데 못 찾겠네요~

https://code.sec.samsung.net/testhub/daily-test/http%253A%252F%252Fnpuci.mooo.com%252Fnnfw_ci_daily%252Fruntime%252Fmaster%252F?sub_project=NNRuntime&commit_id=90647c43655dbc1506ecf6766c97d36eb82c9c1d&release=%5BTrinity%202022%5D%20NN%20Runtime%20Tizen%20M1%20Release

**Comment by chunseoklee** [comment]
> function coverage 점수는 어디에서 확인할 수 있을까요?

@glistening You can also see daily coverage result in 
[link](http://npuci.mooo.com:8080/job/nnfw/job/master/job/daily-arm-runtime-coverage/263/cobertura/)

**Comment by chunseoklee** [comment]
Tizen's own svace, coverity report shows defects which is not detected by previous report. (since all in external, I will mark it "ignore" on the system.)

svace : 
```
493861Critical/home/abuild/rpmbuild/BUILD/nnfw-1.20.0/externals/ABSEIL/absl/debugging/internal/493860Major/home/abuild/rpmbuild/BUILD/nnfw-1.20.0/externals/TENSORFLOW_GPU/tensorflow/lite/delegates/gpu/cl/kernels/493859Major/home/abuild/rpmbuild/BUILD/nnfw-1.20.0/externals/TENSORFLOW_GPU/tensorflow/lite/delegates/gpu/cl/selectors/475677Major/home/abuild/rpmbuild/BUILD/nnfw-1.20.0/externals/TENSORFLOW_GPU/tensorflow/lite/delegates
```
coverity

```
1216786[OPENM] ML_MLFrameworkMajor/home/abuild/rpmbuild/BUILD/nnfw-1.20.0/externals/TENSORFLOW_GPU/tensorflow/lite/delegates/gpu/common/1286616[OPENM] ML_MLFrameworkCritical/home/abuild/rpmbuild/BUILD/nnfw-1.20.0/externals/TENSORFLOW_GPU/tensorflow/lite/delegates/gpu/cl/selectors/1286620[OPENM] ML_MLFrameworkCritical/home/abuild/rpmbuild/BUILD/nnfw-1.20.0/externals/TENSORFLOW_GPU/tensorflow/lite/delegates/gpu/cl/selectors/1286621[OPENM] ML_MLFrameworkCritical/home/abuild/rpmbuild/BUILD/nnfw-1.20.0/externals/TENSORFLOW_GPU/tensorflow/lite/delegates/gpu/cl/selectors/1286624[OPENM] ML_MLFrameworkCritical/home/abuild/rpmbuild/BUILD/nnfw-1.20.0/externals/TENSORFLOW_GPU/tensorflow/lite/delegates/gpu/cl/selectors/1286617[OPENM] ML_MLFrameworkCritical/home/abuild/rpmbuild/BUILD/nnfw-1.20.0/externals/TENSORFLOW_GPU/tensorflow/lite/delegates/gpu/cl/kernels/1286626[OPENM] ML_MLFrameworkCritical/home/abuild/rpmbuild/BUILD/nnfw-1.20.0/externals/TENSORFLOW_GPU/tensorflow/lite/delegates/gpu/cl/kernels/1216809[OPENM] ML_MLFrameworkCritical/home/abuild/rpmbuild/BUILD/nnfw-1.20.0/externals/TENSORFLOW_GPU/tensorflow/lite/delegates/gpu/cl/1216843[OPENM] ML_MLFrameworkCritical/home/abuild/rpmbuild/BUILD/nnfw-1.20.0/externals/TENSORFLOW_GPU/tensorflow/lite/delegates/gpu/cl/1286615[OPENM] ML_MLFrameworkCritical/home/abuild/rpmbuild/BUILD/nnfw-1.20.0/externals/TENSORFLOW_GPU/tensorflow/lite/delegates/gpu/cl/1286618[OPENM] ML_MLFrameworkCritical/home/abuild/rpmbuild/BUILD/nnfw-1.20.0/externals/TENSORFLOW_GPU/tensorflow/lite/delegates/gpu/cl/1286619[OPENM] ML_MLFrameworkCritical/home/abuild/rpmbuild/BUILD/nnfw-1.20.0/externals/TENSORFLOW_GPU/tensorflow/lite/delegates/gpu/cl/1286622[OPENM] ML_MLFrameworkCritical/home/abuild/rpmbuild/BUILD/nnfw-1.20.0/externals/TENSORFLOW_GPU/tensorflow/lite/delegates/gpu/cl/1286623[OPENM] ML_MLFrameworkCritical/home/abuild/rpmbuild/BUILD/nnfw-1.20.0/externals/TENSORFLOW_GPU/tensorflow/lite/delegates/gpu/cl/1286625[OPENM] ML_MLFrameworkCritical/home/abuild/rpmbuild/BUILD/nnfw-1.20.0/externals/TENSORFLOW_GPU/tensorflow/lite/delegates/gpu/cl/1286627[OPENM] ML_MLFrameworkCritical/home/abuild/rpmbuild/BUILD/nnfw-1.20.0/externals/TENSORFLOW_GPU/tensorflow/lite/delegates/gpu/cl/1286628[OPENM] ML_MLFrameworkCritical/home/abuild/rpmbuild/BUILD/nnfw-1.20.0/externals/TENSORFLOW_GPU/tensorflow/lite/delegates/gpu/cl/

```

**Comment by glistening** [comment]
@chunseoklee I thought it was finished. Is it still in progress due to last item (security verification) ?

**Comment by chunseoklee** [comment]
> @chunseoklee I thought it was finished. Is it still in progress due to last item (security verification) ?

Yes I will close
