### ISSUE TITLE
[onert] Prepare validation for Tizen Feature

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#8820]
Let's prepare validation !

## TODO

- [x] TVN for Reference Model : Mobilenet, Simple one op model
- [x] Golden Data for reference models

**Comment by glistening** [comment]
I am working for raw file input/output in `nnpackage_run` so that we can read and write the raw input and output to check using existing trix model runner's raw input and output.

**Comment by glistening** [comment]
When golden (e.g. mv1in.0.in and mv1out.0.expected below) is prepared (using existing tvn executor), you can check trix bring the same result by:
```
$ BACKENDS="trix;cpu" \
./Product/x86_64-linux.debug/out/bin/nnpackage_run \
--load:raw mv1in.0.in \
--dump:raw mv1out \
mv1

$ ls mv1*
-rw-rw-r-- 1 gyu gyu  150528 Apr 15 07:28 mv1in.0.in
-rw-rw-r-- 1 gyu gyu    1000 Apr 15 12:22 mv1out.0
-rw-rw-r-- 1 gyu gyu    1000 Apr 15 07:28 mv1out.0.expected

$ diff mv1out.0 mv1out.0.expected
$ echo $?
0
```

**Comment by glistening** [comment]
Here are the next items related validation:

- [ ] Raw input/output
  - [ ] multiple input/output validation
    - [ ] update nnpkg_run
    - [ ] prepare multiple input/output tvn models and nnpkgs, golden...
    - [ ] make sure it works
- [ ] (optional) HDF5 support
  - [ ] prepare mobilenet quantized model golden data in h5 format
- [ ] Update gen_golden for trix support
- [ ] Make or update script to add raw input/output validation for CI
- [ ] (optional) #8890

**Comment by glistening** [comment]
@chunseoklee I think we can close this issue. If there are remaining items before M1 release, please add item or comment.
