### ISSUE TITLE
Checklist for ONE Release 1.20.0

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#8985]
### Release Action

- [x] Release Note #9046
- [x] Update debian package changelog ( before branch out ) #9048
- [x] After Branch out 
  - [x] `master` branch version up #9047
    - [x] tizen spec file
    - [x] nnfw_version.h
    - [x] document version in `/docs/conf.py`
    - [x] onert aar version
- [x] Tizen upstream branch update to released one https://dashboard.tizen.org/index.code?sr=submit/tizen/20220427.061713

### Release Package

- Runtime 
  - [x] arm64-android (tar.gz) for Android 10
  - [x] arm64-android (aar) for Android 10
  - [x] arm-tizen (rpm) for Tizen 6.0 M2
  - [x] arm-linux (tar.gz)  for Ubuntu 18.04
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
  - [x] nnfw-devel
  - [x] nnfw-plugin-devel
- Compiler
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
     - [x] test with public models
     - [x] test with in-hose models

### Release Criteria

- Runtime : TEM (>4.0), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0, DC > 4.0)
  - [x] TEM coverage link : [4.0 link](https://code.sec.samsung.net/testhub/release-test/detail?release_key=SRRELEASE-1203&baseDate=2022-04-19)
  - [x] TCM link : [link](https://analysishub.sec.samsung.net/service/analyses/1280551) 53% (235 / 443, Negative / Total TC)
  - [x] Coverity link : [link](https://analysishub.sec.samsung.net/service/analyses/1281567)
  - [x] Svace link : [link](https://analysishub.sec.samsung.net/service/analyses/1280736)
  - [x] SAM link : [link](https://analysishub.sec.samsung.net/service/analyses/1280736)
  - [x] License Verification : [one_1200Report.zip](https://github.com/Samsung/ONE/files/8552265/one_1200Report.zip)
- Compiler : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0) 
  - [x] TEM coverage link : [link](http://npuci.mooo.com:8080/job/nnfw/job/master/job/daily-compiler-coverage/266/cobertura/)
  - [x] TCM link : [link](https://analysishub.sec.samsung.net/service/analyses/1290142)
  - [x] Svace link : [link](https://analysishub.sec.samsung.net/service/analyses/1290146)
  - [x] Coverity link : [link](https://analysishub.sec.samsung.net/service/analyses/1290145)
  - [x] SAM link : [link](https://analysishub.sec.samsung.net/service/analyses/1290146) (shown in svace link)
  - [x] License Verification : [one_1200Report.zip](https://github.com/Samsung/ONE/files/8552265/one_1200Report.zip)

### Miscellaneous

- [x] nncc preset update if needed
- [x] SSMS
  - Runtime : 
    - [x] Svace_security : [link](https://analysishub.sec.samsung.net/service/analyses/1280726)
  - Compiler : 
    - [x] Svace_security : [link](https://analysishub.sec.samsung.net/service/analyses/1290317)

**Comment by chunseoklee** [comment]
@Samsung/nncc Svace_security build failed. PTAL

**Comment by seanshpark** [comment]
### Compiler Frontend
- luci-interpreter supports multiple kernels with PAL layer including Cortext-M
- luci-interpreter supports integer tensor for partly kernels
- luci import support constant without coping to reduce memory for luci-interpreter
- Reduce duplicate codes to package released modules
- Limited support for ONNX LSTM/RNN unrolling while importing
- Limited support for ARM32 cross build
- Limited support for Tizen ARM32 GBS build
- Support new operator: SVDF
- New virtual CircleVariable to support tensor with variable
- Quantize support for BatchMatMul Op
- Support mixed(UINT8 + INT16) quantization
- (more about quantization...)
- Upgrade default python to version 3.8
- Support TensorFlow 2.8.0, ONNX-TF 1.10.0
- Upgrade circle schema to follow tflite v3b
- Refactor to mio-tflite280, mio-circle04 with version and helpers methods
- Use one flatbuffers 2.0 version
- Drop support for TensorFlow 1.x
- Fix for several bugs, performance enhancements, and typos

**Comment by chunseoklee** [comment]
> Limited support for Tizen ARM32 GBS build

@seanshpark Is this is done ?

**Comment by llFreetimell** [comment]
Following things seems not related with users' perspective..?

- Reduce duplicate codes to package released modules
- Refactor to mio-tflite280, mio-circle04 with version and helpers methods
- Use one flatbuffers 2.0 version

**Comment by seanshpark** [comment]
>> Limited support for Tizen ARM32 GBS build
>
> @seanshpark this is done ?

@chunseoklee , it's about your task :) please update to what you want to describe.

**Comment by chunseoklee** [comment]
> @chunseoklee , it's about your task :) please update to what you want to describe.

Then, I will remove this from 1.20.0 release.

**Comment by seanshpark** [comment]
> Following things seems not related with users' perspective..?

We also release `-dev` package for developers too.
I am also not confident about the message so @chunseoklee can decide to exclude or not.

**Comment by chunseoklee** [comment]
> nncc preset update if needed

@seanshpark @mhs4670go I just found that the quoted item is not marked. Is this OK ?

**Comment by mhs4670go** [comment]
> > nncc preset update if needed
> 
> @seanshpark @mhs4670go I just found that the quoted item is not marked. Is this OK ?

Yes:)

**Comment by chunseoklee** [comment]
Done.
