### ISSUE TITLE
[npud] Introduce initial npud code

### ISSUE THREAD

**Issue by jyoungyun** [Samsung/ONE#9304]
## What

Introduce initial npud code

Related issue: #9258
Draft PR: #9267

## To do

- [x] Implement event loop core (#9493)
- [x] Implement logger (#9509)
- [x] Implement signal handler (#9507)
- [x] Define HAL interface (#9971)
- [x] Implement Device plugins
   - [x] trix (#10012)
- [ ] ~~Define User APIs~~
- [x] Implement DBus handler (#9929)
   - [x] DBus test (#9952)
- [x] Add DBus configuration file (#10058)

**Comment by jyoungyun** [comment]
I will make a new issue for `Define User APIs`.

**Comment by jyoungyun** [comment]
No more progress.
