### ISSUE TITLE
Checklist for ONE 1.21.0 Release

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#9672]
### Release Action

- [x] Release Note #9674 
- [x] Update debian package changelog ( before branch out ) #9675 
- [x] After Branch out  
  - [x] `master` branch version up  #9677
    - [x] tizen spec file
    - [x] nnfw_version.h
    - [x] document version in `/docs/conf.py`
    - [x] onert aar version
- [x] #9676

### Release Package

- Runtime 
  - [x] arm64-android (tar.gz) for Android 10
  - [x] arm64-android (aar) for Android 10
  - [x] arm-tizen (rpm) for Tizen 6.0 M2
  - [x] arm-linux (tar.gz)  for Ubuntu 18.04
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
  - [x] nnfw-devel
  - [x] nnfw-plugin-devel
- Compiler
  - [x] x64-linux (tar.gz) for Ubuntu 18.04
     - [x] test with public models
     - [x] test with in-hose models

### Release Criteria

- Runtime : TEM (>4.0), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0, DC > 4.0)
  - [x] TEM coverage link : 4.05 [link](https://code.sec.samsung.net/testhub/release-test/detail?release_key=SRRELEASE-1204&baseDate=2022-09-05&page=0)
  - [x] TCM link : (248 / 468, Negative / Total TC) [link](https://analysishub.sec.samsung.net/service/analyses/1556051) 
  - [x] Coverity link : [link](https://analysishub.sec.samsung.net/service/analyses/1557243)
  - [x] Svace link : [link](https://analysishub.sec.samsung.net/service/analyses/1557242)
  - [x] SAM link : 4.48 [link](https://analysishub.sec.samsung.net/service/analyses/1557242) 
  - [x] License Verification : [one_1.21.0 Report.zip](https://github.com/Samsung/ONE/files/9496805/one_1.21.0.Report.zip)

- Compiler : TC line coverage (>80%), TCM(New Negitive / New Positive > 1), Svace & Coverity (critical=0), SAM (>4.0) 
  - [x] TEM coverage link : 4.09 [link](http://npuci.mooo.com:8080/job/nnfw/job/master/job/daily-compiler-coverage/365/)
  - [x] TCM link : (1014 / 2021) [link](https://analysishub.sec.samsung.net/service/analyses/1557828)  
  - [x] Svace link : [link](https://analysishub.sec.samsung.net/service/analyses/1557827)
  - [x] Coverity link : [link](https://analysishub.sec.samsung.net/service/analyses/1557826)
  - [x] SAM link : 4.48 [link](https://analysishub.sec.samsung.net/service/analyses/1557827)
  - [x] License Verification : [one_1.21.0 Report.zip](https://github.com/Samsung/ONE/files/9496805/one_1.21.0.Report.zip)

### Miscellaneous

- [x] nncc preset update if needed
- [x] Security 
  - Runtime : 
    - [x] Svace_security : [link](https://analysishub.sec.samsung.net/service/analyses/1556881)
  - Compiler : 
    - [x] Svace_security : [link](https://analysishub.sec.samsung.net/service/analyses/1557829)

**Comment by chunseoklee** [comment]
@seanshpark Could you please post compiler's release candidate as comment ?

**Comment by seanshpark** [comment]
Compiler frontend
- TBD

**Comment by seanshpark** [comment]
@jinevening , please take a look and edit https://github.com/Samsung/ONE/issues/9672#issuecomment-1237554355 if necessary :)

**Comment by jinevening** [comment]
I slightly updated the contents as follows. PTAL :)

1. Rephrase some items
2. Add some missing items
3. Remove new Op support in `luci-interpreter` (it seems duplicate with support for quantization).

**Comment by seanshpark** [comment]
@mhs4670go , if you have anything to change, please update.

**Comment by seanshpark** [comment]
@chunseoklee , I think we can go with compiler frontend comments

**Comment by chunseoklee** [comment]
@Samsung/nncc_committers 

> nncc preset update if needed

not need in this release ? Then, I will branch out soon

**Comment by chunseoklee** [comment]
> @Samsung/nncc_committers
> 
> > nncc preset update if needed
> 
> not need in this release ? Then, I will branch out soon

@mhs4670go confirmed that not needed. Thus I will make a new branch release/1.21.0
