### ISSUE TITLE
[one-cmds] Question about ONE Dockerizing Process

### ISSUE THREAD

**Issue by holawan** [Samsung/ONE#9697]
## why

Regarding #8232 issue, we are going to do Dockerizing so that more users can easily use `one-cmds`.

I would like to ask for a view on the way in which I carry out.

## how

I currently proceeded with Dockerizing in the following way.

### summary

1. Import TensorFlow Model for Dockerizing and write Configure File.
2. Write a Dockerfile to create a Docker image and run the container.
    - When `onecc` is finished running, the container is terminated and deleted.
3. Check that circle file and nnpackage have been created.

### Import Tensorflow model for testing

First, I created the path '/home/test/' for Linux (wsl) and downloaded the model file to test. After downloading [inception_v3](https://storage.googleapis.com/download.tensorflow.org/models/tflite/model_zoo/upload_20180427/inception_v3_2018_04_27.tgz), the Configure file was created.

```
# /home/test/
$ wget https://storage.googleapis.com/download.tensorflow.org/models/tflite/model_zoo/upload_20180427/inception_v3_2018_04_27.tgz

$ tar -xvf inception_v3_2018_04_27.tgz

$ vi onecc.template.cfg

$ tree
.
├── inception_v3.pb
├── inception_v3.tflite
├── inception_v3_2018_04_27.tgz
├── labels.txt
└── onecc.template.cfg
```

- onecc.template.cfg

    ```
    [onecc]
    one-import-tf=True
    one-import-tflite=False
    one-import-bcq=False
    one-import-onnx=False
    one-optimize=True
    one-quantize=False
    one-parition=False
    one-pack=True
    one-codegen=False
    
    [one-import-tf]
    input_path=inception_v3.pb
    output_path=inception_v3.circle
    input_arrays=input
    input_shapes=1,299,299,3
    output_arrays=InceptionV3/Predictions/Reshape_1
    converter_version=v1
    model_format=graph_def
    
    [one-optimize]
    input_path=inception_v3.circle
    output_path=inception_v3.opt.circle
    generate_profile_data=False
    
    [one-pack]
    input_path=inception_v3.opt.circle
    output_path=inception_v3_pack
    ```

### Create Dockerfile and run container

Write Dockerfile to create Docker image.

I used `ubuntu:18.04` image and wanted to run `onecc`using the current latest release version of `1.21.0` Debian package.

You created a Docker image and mounted the local path and the internal path of the Docker container.

If the container is successfully run, a circle file will be created and the container will be deleted after shutdown.

- docker version

    ```
    $ docker -v
    Docker version 20.10.17, build 100c701
    ```

    

- Dockerfile

    ```dockerfile
    FROM ubuntu:18.04
    
    RUN apt-get update
    
    RUN apt-get install -y sudo
    
    RUN apt-get install -y wget
    
    RUN wget https://github.com/Samsung/ONE/releases/download/1.21.0/one-compiler_1.21.0_amd64.deb
    
    RUN sudo apt install -y ./one-compiler_1.21.0_amd64.deb
    
    WORKDIR /home/
    
    RUN mkdir test
    
    WORKDIR /home/test
    
    CMD["onecc", "-C", "onecc.template.cfg"]
    ```

    - I wrote it for the syntax test that I put in the CMD, and will replace it with the Configure File that the user entered in the command line.

- create docker image

    ```
    $ docker build -t test:1 .
    ```

- Run docker container

    ```
    $ docker run --rm --name test_docker -v /home/test:/home/test test:1
    ```

    - The local path will be replaced by the path where the user's TensorFlow model is located.
   
### Execution Results 

This is my execution result. The circle file and nnpackage have been created well, and I don't think there is any problem with my method so far. 

Docker container was also successfully removed. 

```
$ tree
.
├── inception_v3.circle
├── inception_v3.circle.log
├── inception_v3.opt.circle
├── inception_v3.opt.circle.log
├── inception_v3.pb
├── inception_v3.tflite
├── inception_v3_2018_04_27.tgz
├── inception_v3_pack
│   └── inception_v3.opt
│       ├── inception_v3.opt.circle
│       └── metadata
│           └── MANIFEST
├── inception_v3_pack.log
├── labels.txt
└── onecc.template.cfg
```

## Todo

If the method is ok, I would like to write `onecc-docker` (working title) as a shell script so that if the user runs `onecc-docker`, the above process will be executed.

Furthermore, The user can also select a version of the Debian package for the desired results.

Of course, my current method is not perfect, and depending on the various options of `onecc` (`-O`, `-W` ...), I think a lot of additional modifications are needed.

I'd appreciate it if you could leave a comment.

Additionally, based on my linux, it took about 10 minutes to create a Docker image (using `one-compiler_1.21.0_amd64.deb`). I want to ask if the speed of creating an image is appropriate.

/cc @Samsung/ootpg

**Comment by mhs4670go** [comment]
The way you do it, the time it takes to build docker image. Seems good to me:)

Actually, I think what matters is not how you do it but what it looks like. I mean, prior to deciding implementation detail, we should decide user interface and user scenario things. Everything else is secondary.

If you draft them and share them with us, it would be helpful to look over the design.

**Comment by holawan** [comment]
Thank you for your comments.
I am attaching the scenario we planned. I don't know if the format you wanted is correct, but if you give me your opinion, I will revise it and upload it again. Thank you!
# ONE_Dockerizing_Scenario

## User Scenario

### Who?

- Users who cannot or do not want to use Linux OS (Ubuntu 18.04 or Ubuntu 20.04)
- Users who want to convert the TensorFlow model to Circle file using ONE

### What 

- Convert to TensorFlow model Circlefile using 'one-cmds' regardless of operating system

### When?

- Available when the TensorFlow Model file is ready to run `onecc` and when the `onecc` related Configure file is ready.

### Where?

- User's operating system

### Why?

- Currently, `onecc` and `one-build` are only available in Ubuntu 18.04 and Ubuntu 20.04, but this is to make the service available even if it is not in that environment.

### How 

1. Create a '*.cfg' containing the option you want to perform related to the TensorFlow Model file(`.pb`, `.tfilte` ..) and `onecc`

2. Execute `onec-docker` command

    - ex

        ```
        $ onecc-docker -C *.cfg
        $ onecc-docker -W *.workflow.json
        $ onecc-docekr -C *.cfg -O *.cfg
        ```

3. Select the `one-compiler` version 

4. Run Docker Container

    - When Docker Image is not present

        - Automatically create the docker image version that you want.

        - Run Docker Container

    - When Docker Image is present
        - Run the container with the desired version of Docker Image by the user

5. Create circle files and `nnpackages` with `*.cfg` and TensorFlow models shared as volumes inside the Docker container

## User Interface

###  `-v` , `--version`

- Run 'onecc-docker'

```
$ onecc-docker -v 
onecc-docker version 0.00.0
Copyright (c) 2020-2022 Samsung Electronics Co., Ltd. All Rights Reserved
Licensed under the Apache License, Version 2.0
https://github.com/Samsung/ONE
```

### `-h`, `--help`

- Run 'onecc-docker'

```
$ onecc-docker -h
Run ONE driver via several commands or configuration file

optional arguments:
  -h, --help            show this help message and exit
  -v, --version         show program's version number and exit
  -V, --verbose         output additional information to stdout or stderr
  -C CONFIG, --config CONFIG
                        run with configuation file
  -O OPTIMIZATION       optimization name to use (Available optimization options: -O1)
  -W WORKFLOW, --workflow WORKFLOW
                        run with workflow file

compile to circle model:
  import                Convert given model to circle
  optimize              Optimize circle model
  quantize              Quantize circle model

package circle model:
  pack                  Package circle and metadata into nnpackage

run backend tools:
  codegen               Code generation tool
  profile               Profile backend model file
  infer                 Infer backend model file
```

###  `-C`

- TensorFlow Model file and 'onec' related '*.cfg' preparation

```
$ tree
.
├── inception_v3.pb
├── inception_v3.tflite
├── inception_v3_2018_04_27.tgz
├── labels.txt
└── onecc.template.cfg
```

- Run 'onecc-docker'

```
$ onecc-docker -C *.cfg
```

- Execution Results

```
$ tree
.
├── inception_v3.circle
├── inception_v3.circle.log
├── inception_v3.opt.circle
├── inception_v3.opt.circle.log
├── inception_v3.pb
├── inception_v3.tflite
├── inception_v3_2018_04_27.tgz
├── inception_v3_pack
│   └── inception_v3.opt
│       ├── inception_v3.opt.circle
│       └── metadata
│           └── MANIFEST
├── inception_v3_pack.log
├── labels.txt
└── onecc.template.cfg
```

**Comment by holawan** [comment]
I have an additional question.
We think 'onecc' is available from release version 1.17.0.
If the user can select the version when running 'onecc-docker', is it correct to provide the user to select the version after 1.17.0?

**Comment by jyoungyun** [comment]
Welcome to ONE github for the first time. :)

Your progress looks good to me. The Dockerfile worked well and generated the intended outputs.
There is room for modifications such as reducing unnecessary commands and cleaning up unnecessary things after installing package but I don't think this is important at this stage.

The overall user interface is likely to be shared as it is by delivering it to the existing `onecc`.

> If the user can select the version when running 'onecc-docker', is it correct to provide the user to select the version after 1.17.0?

Can't we choose the previous versions as well? Why did you think you could only choose the version after 1.17.0?

**Comment by holawan** [comment]
@jyoungyun 

Thank you for your welcome :)

https://github.com/Samsung/ONE/releases/tag/1.17.0
I would appreciate it if you could check the link.

As a result of checking the release version of `ONE`,  `onecc` was introduced in version 1.17.0.
Also, We recognize that the Debian package is available from version 1.17.0 or later.

The scenario we thought of is as follows.
- We use `onecc` to dockerizing.
- We think we download the Debian package from Dockerfile.

I'd appreciate it if you could tell me if there's anything wrong.

**Comment by jyoungyun** [comment]
> As a result of checking the release version of ONE, onecc was introduced in version 1.17.0.
> Also, We recognize that the Debian package is available from version 1.17.0 or later.

Ah, it's right. we have introduced the `onecc` to v1.17.0, so we need support after v1.17.0.

> - We use `onecc` to dockerizing.
> - We think we download the Debian package from Dockerfile.

Both are correct approaches. :)

**Comment by seanshpark** [comment]
>  so we need support after v1.17.0

Q) why is `v1.17.0` discussed here?

Q) how is this version number going to be used with `onecc-docker` ?

**Comment by holawan** [comment]
@seanshpark 

Q1) Our goal is primarily
  It is to make `onecc` available on multiple operating systems through dockerizing. The next step is to allow users to select the release version of ONE and use 'onecc'.

Therefore, the mention of `v1.17.0` is not the primary implementation purpose at present, but it is a reference to considerations in the future.

Q2)  The version number allows the user to build the docker image of the desired version and get the result with the corresponding version of `onecc`.(circle file, nnpackage ..)

**Comment by seanshpark** [comment]
> The next step is to allow users to select a release version of ONE and use 'onecc'.

My question is about this, why do need to provide the user to select the version of `onecc` ?

**Comment by seanshpark** [comment]
> but it is a reference to considerations in the future.

What do you mean but `future` ? on what consideration?

**Comment by seanshpark** [comment]
The help option `-h, --help` does not provide an option to select which release version of onecc.

From my point of view, providing user to select `onecc` version is an option.
First we can provide this `onecc-docker` with latest `onecc` version.
When `onecc-docker` itself is all ready and working and also can be used in `ONE-vscode`,
then we can provide addition option to select `onecc` package version.

Why do I think like this?
- We can imagine that there are lots old version and it would be nice to provide an option to select this... but what's the goodness for this? is there real requirement?
- or is this just an feature that just came up from some dicussion that sounds good ?
- adding features require more work and more testing that may hold your main task
- we can always upgrade when needed, later
- I suggest you guys to focus on core features first and then expand later when you have time

**Comment by lemmaa** [comment]
https://github.com/Samsung/ONE/issues/9697#issuecomment-1244913574
> Why not just provide to build a docker with latest version?

I guess, in an environment that supports multiple versions of a toolchain, such as `ONE-vscode`, it is necessary to create a docker image for each version of the toolchain, including the old version. :)

**Comment by lemmaa** [comment]
> > but it is a reference to considerations in the future.
> 
> What do you mean ~but~ by `future` ? on what consideration?

IIUC, he doesn't plan to implement this feature right now. It looks like it will be expanded in the future. It is thought that he left a record just to not forget it at that time. :)

**Comment by seanshpark** [comment]
@holawan , about this issue

- this issue's first comment containus like a detaild plan for some feature
- title is a question which makes readers, like me get confused and hard to catch what the question is

It would be better to just add some summerized text in first comment and add comments about detailed stuff from different views if necessary. And then add a question in another issue with a link for that particular question or questions.

**Comment by holawan** [comment]
Hello. When I first heard the assignment explanation, I understood that the mission was included as a long-term goal.

I think I misunderstood or confused you by mentioning something that is not important right away.

I immediately re-confirmed my important goal, and I will focus on realizing it.
Thank you for your opinion.

I would appreciate it if you could comment on any additional comments or if there were any that I did not respond to.

**Comment by seanshpark** [comment]
> I would appreciate it if you could comment on any additional comments or if there were any that I did not respond to.

Detailed descrtiption for providing `onecc-docker` looks good in the main comment :)
I'm curious about these for now;
- how long (in weeks? or in days?) do you plan to work on this?
- can you describe them in some activites in checkbox bullets?
  - [ ] do some ...
  - [ ] and then ...
  - [ ] finally ...

**Comment by holawan** [comment]
@seanshpark 

I will reply to you after organizing it in the way you want within the team.

Can I start answering this question with a new issue?

**Comment by seanshpark** [comment]
> I will reply to you after organizing it in the way you want within the team.

I'm not sure I understood this correctly but I think organizing this issue
would be burden and maybe a waste of time.
It was a suggestion for new issues and for better communication.
If you feel current format is comfortable, you can go as-is.

> Can I start answering this question with a new issue?

I think question itself is in this issue so it would be better to add comments here.

**Comment by holawan** [comment]
I tried to close the issue because it seemed to have caused damage by creating a confusing issue. 

I'm sorry that I'm still not good at creating issues. 

As you said, we will proceed with the answer in the current issue.

Thank you for your comment :)

**Comment by holawan** [comment]
> how long (in weeks? or in days?) do you plan to work on this?


Our project started in earnest on September 1st, and we are planning to finish it on September 30th.
So we have about three weeks.


> can you describe them in some activites in checkbox bullets?


Let me explain our plan through the check box.
- [ ] Creating a Dockerfile for 'onecc' dockerizng
- [ ] Create 'onecc-docker' and run 'onecc' in the docker container when running 'onecc-docker'.
- [ ] Testing our work
- [ ] Create debian package with 'onecc-docker'

This is not the final plan, and I think it will be finally decided after the meeting with @jyoungyun on September 14th. I'd appreciate it if you could give me your opinion.

**Comment by seanshpark** [comment]
> we are planning to finish it on September 30th.

Thanks for sharing your plan :)
You have about 12 workdays, which I think you can finish these in time or maybe not, depending on how you work on the tests. That is the usage scenario and the tests for those scenarios.

> This is not the final plan

I hope so, but please don't get disappointed if your times up without finishing your plan.
My experience from last year with SSAFY guys was that progress won't go as expected.
Please concentrate on the feature and quality, not on like "We've put all our codes here!".

> and I think it will be finally decided after the meeting with @jyoungyun on September 14th. 

Good luck!

> I'd appreciate it if you could give me your opinion.

Please define the scope and scenario and features to develop in quantity and quality.
And maybe items you won't do in this period.
Provide working draft codes in draft PR and describe in words about the purpose and background.
Others like me won't understand as you, as the author, unless you explain enough.

**Comment by seanshpark** [comment]
Q) what is your given objective of participating on open source projects?
Q) what is your personal achievement you want to get from this period?

If it's not comfortable to share these here, you may skip these. I understand.

**Comment by holawan** [comment]
> Please define the scope and scenario and features to develop in quantity and quality.

We will organize our plans in detail by referring to your opinion. Thank you.

> Q) what is your given objective of participating on open source projects?

Our goal is to make 'oneec' available to various operating systems through Docker, and finally implement the Debian package that provides 'one-compiler' that includes script files and docker files.

> Q) what is your personal achievement you want to get from this period?

We hope that the code we contributed to will be used by 'ONE' users without any problems after various tests. My purpose of participating in the open source project is experience. I've used open source a lot, but I've never contributed directly. I think that experiencing open source culture in person and increasing communication and technology capabilities will have a good impact on living as a developer in the future. I think it is a great achievement for me to communicate with 'ONE' developers and think and apply ideas in various scenarios. Finally, I hope that our contribution project will be useful.


Is the answer correct for your intentions? Thank you.

**Comment by seanshpark** [comment]
> Our goal is to make 'onecc' available to various operating systems through Docker, and finally implement the Debian package that provides 'one-compiler' that includes script files and docker files.

Not this particular project but from SSAFY managers in general :)

**Comment by seanshpark** [comment]
> My purpose of participating in the open source project is experience.

I also have not much experience from other open source projects. Personally learned a lot from .NET project. I'm not sure this repo can be a general culture. Hope you join other open source projects too. :)

**Comment by holawan** [comment]
> Not this particular project but from SSAFY managers in general :)


I'm not sure I fully understand your words. Do you mean the overall goal of SSAFY projects?

If you ask me about the purpose of SSAFY's open source project, I'll tell you this

SSAFY wants to give us an open-source contribution experience. We can also have a good experience by getting the opportunity to make a presentation at SSDC based on the results.

**Comment by seanshpark** [comment]
> SSAFY wants to give us an open-source contribution experience. We can also have a good experience by getting the opportunity to make a presentation at SSDC based on the results.

I think this is the one.
Hope you enjoy the `experience` you get and mostly have fun :)

**Comment by holawan** [comment]
Thanks @seanshpark , I understand a lot of things because of you!

Additional discussions would like to start with PR and new issues.

Can I close this issue now?

**Comment by seanshpark** [comment]
> Can I close this issue now?

Yes :) it's your creation.
