### ISSUE TITLE
[onert/test] Replace benchmark tools using NNAPI fronend

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#9864]
### What?

Let's deprecate benchmark tools using NNAPI driver (`tflite_run` with `USE_NNAPI` environment variable setting). 
Currently, it is not working on ubuntu envrionment. (working on android only)
Instead of this, let's use `nnpackage_run` ~introduce and use new NNFW API driver: `onert_run` https://github.com/Samsung/ONE/pull/9858~

### Why?

It's difficult to maintain NNAPI delegate porting for TensorFlow Lite to work on ubuntu with ONE Runtime. And currently, TFLite's NNAPI delegate porting implementation is removed so test driver `tflite_run` with `USE_NNAPI` is not working on ubuntu. 

Current operator and model benchmark framework uses `tflite_run` to use ONE Runtime's NNAPI frontend. But because of above reason, getting performance of ONE Runtime is not working now. So we need new test driver to replace `tflite_run`, which is using NNFW API frontend.

- [x] Introduce new option for single model on `nnpackage_run` #9870
- [x] Deprecate `tflite_run`'s `USE_NNAPI` environment variable usage #9875
- ~Deprecate benchmark tools using TFLite with NNAPI~
- [x] Deprecate `NNAPISession` on `libs/tflite`. #9902
- [x] Rename `nnpackage_run` to `onert_run` (or make alias) #10092

**Comment by glistening** [comment]
@hseok-oh I agree to deprecate `tflite_run` with `USE_NNAPI`. However, I am not sure we need another runner to run `tflite`:

- Apparently, `onert_run` in #9858 has many duplicated logic and code with `nnpackage_run`. (maintenance cost)
- I think we have been used `nnpackage_run` to run benchmark.
- The same thing can be done by 
```
$ model2nnpkg your.tflite
$ nnpackage_run your
``` 
Please let me know if I am missing something.

**Comment by hseok-oh** [comment]
> many duplicated logic and code

Then we can introduce new option in `nnpackage_run` (ex. `--modelfile`) to load supported model file type. (and rename it if need)

> I think we have been used `nnpackage_run` to run benchmark.

You're right. I checked that we are using `nnpackage_run` for model benchmark. But operator benchmark test (not working now) is using `tflite_run`. 

>The same thing can be done by 

Right. But I suggested to replace `tflite_run` to other test driver for
- Small change on test framework
- Using model download cache directory without any process

**Comment by glistening** [comment]
Considering things above, what about just introducing an option for getting a single model (tflite or circle) in `nnpackage_run`, and we may rename it to `onert_run`. But it may require much change in test framework scripts. : )

**Comment by chunseoklee** [comment]
> we may rename it to onert_run

Or alias ?

**Comment by hseok-oh** [comment]
>Considering things above, what about just introducing an option for getting a single model (tflite or circle) in `nnpackage_run`, and we may rename it to `onert_run`

Good. I'll introduce new option for single model first. And I'll try to change name as next step.

**Comment by hseok-oh** [comment]
Tools using `NNAPISession`

- `runtime/contrib/android_benchmark_app`
- `runtime/contrib/mlapse/tfl`
- `runtime/contrib/tflite_classify`
- `runtime/contrib/tflite_test`
