### ISSUE TITLE
[runtime/infra] Remove TFLite 1.13.1

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#9985]
Let's remove TFLite 1.13.1 related implementation and cmake config.

- [x] Remove tools usnig TFLite 1.13.1
  - [x] Remove deprecated `tests/tools/tflite_benchmark_model` #9983
  - [x] Remove deprecated `runtime/contrib/android_tflite` #9986
- [x] Remove cmake config `infra/nnfw/cmake/packages/TensorFlowLite-1.13.1` #9993

**Comment by hseok-oh** [comment]
Done
